// Code generated by go-swagger; DO NOT EDIT.

package xprocess

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// GetXprocessIDInfoReader is a Reader for the GetXprocessIDInfo structure.
type GetXprocessIDInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetXprocessIDInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetXprocessIDInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /xprocess/{id}/info] GetXprocessIDInfo", response, response.Code())
	}
}

// NewGetXprocessIDInfoOK creates a GetXprocessIDInfoOK with default headers values
func NewGetXprocessIDInfoOK() *GetXprocessIDInfoOK {
	return &GetXprocessIDInfoOK{}
}

/*
GetXprocessIDInfoOK describes a response with status code 200, with default header values.

Response
*/
type GetXprocessIDInfoOK struct {
	Payload *models.GetXprocessIDInfoOKBody
}

// IsSuccess returns true when this get xprocess Id info o k response has a 2xx status code
func (o *GetXprocessIDInfoOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get xprocess Id info o k response has a 3xx status code
func (o *GetXprocessIDInfoOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get xprocess Id info o k response has a 4xx status code
func (o *GetXprocessIDInfoOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get xprocess Id info o k response has a 5xx status code
func (o *GetXprocessIDInfoOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get xprocess Id info o k response a status code equal to that given
func (o *GetXprocessIDInfoOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get xprocess Id info o k response
func (o *GetXprocessIDInfoOK) Code() int {
	return 200
}

func (o *GetXprocessIDInfoOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /xprocess/{id}/info][%d] getXprocessIdInfoOK %s", 200, payload)
}

func (o *GetXprocessIDInfoOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /xprocess/{id}/info][%d] getXprocessIdInfoOK %s", 200, payload)
}

func (o *GetXprocessIDInfoOK) GetPayload() *models.GetXprocessIDInfoOKBody {
	return o.Payload
}

func (o *GetXprocessIDInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetXprocessIDInfoOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
