// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for BatchRetestVulnConfigBodyHTTPConfigCookiesItems

// register flags to command
func registerModelBatchRetestVulnConfigBodyHTTPConfigCookiesItemsFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerBatchRetestVulnConfigBodyHTTPConfigCookiesItemsPropAllowOverride(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerBatchRetestVulnConfigBodyHTTPConfigCookiesItemsPropKey(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerBatchRetestVulnConfigBodyHTTPConfigCookiesItemsPropValue(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerBatchRetestVulnConfigBodyHTTPConfigCookiesItemsPropAllowOverride(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagAllowOverrideDescription := ``

	var flagAllowOverrideName string
	if cmdPrefix == "" {
		flagAllowOverrideName = "allow_override"
	} else {
		flagAllowOverrideName = fmt.Sprintf("%v.allow_override", cmdPrefix)
	}

	var flagAllowOverrideDefault bool

	_ = cmd.PersistentFlags().Bool(flagAllowOverrideName, flagAllowOverrideDefault, flagAllowOverrideDescription)

	return nil
}

func registerBatchRetestVulnConfigBodyHTTPConfigCookiesItemsPropKey(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagKeyDescription := ``

	var flagKeyName string
	if cmdPrefix == "" {
		flagKeyName = "key"
	} else {
		flagKeyName = fmt.Sprintf("%v.key", cmdPrefix)
	}

	var flagKeyDefault string

	_ = cmd.PersistentFlags().String(flagKeyName, flagKeyDefault, flagKeyDescription)

	return nil
}

func registerBatchRetestVulnConfigBodyHTTPConfigCookiesItemsPropValue(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagValueDescription := ``

	var flagValueName string
	if cmdPrefix == "" {
		flagValueName = "value"
	} else {
		flagValueName = fmt.Sprintf("%v.value", cmdPrefix)
	}

	var flagValueDefault string

	_ = cmd.PersistentFlags().String(flagValueName, flagValueDefault, flagValueDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelBatchRetestVulnConfigBodyHTTPConfigCookiesItemsFlags(depth int, m *models.BatchRetestVulnConfigBodyHTTPConfigCookiesItems, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, AllowOverrideAdded := retrieveBatchRetestVulnConfigBodyHTTPConfigCookiesItemsPropAllowOverrideFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || AllowOverrideAdded

	err, KeyAdded := retrieveBatchRetestVulnConfigBodyHTTPConfigCookiesItemsPropKeyFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || KeyAdded

	err, ValueAdded := retrieveBatchRetestVulnConfigBodyHTTPConfigCookiesItemsPropValueFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ValueAdded

	return nil, retAdded
}

func retrieveBatchRetestVulnConfigBodyHTTPConfigCookiesItemsPropAllowOverrideFlags(depth int, m *models.BatchRetestVulnConfigBodyHTTPConfigCookiesItems, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagAllowOverrideName := fmt.Sprintf("%v.allow_override", cmdPrefix)
	if cmd.Flags().Changed(flagAllowOverrideName) {

		var flagAllowOverrideName string
		if cmdPrefix == "" {
			flagAllowOverrideName = "allow_override"
		} else {
			flagAllowOverrideName = fmt.Sprintf("%v.allow_override", cmdPrefix)
		}

		flagAllowOverrideValue, err := cmd.Flags().GetBool(flagAllowOverrideName)
		if err != nil {
			return err, false
		}
		m.AllowOverride = flagAllowOverrideValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveBatchRetestVulnConfigBodyHTTPConfigCookiesItemsPropKeyFlags(depth int, m *models.BatchRetestVulnConfigBodyHTTPConfigCookiesItems, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagKeyName := fmt.Sprintf("%v.key", cmdPrefix)
	if cmd.Flags().Changed(flagKeyName) {

		var flagKeyName string
		if cmdPrefix == "" {
			flagKeyName = "key"
		} else {
			flagKeyName = fmt.Sprintf("%v.key", cmdPrefix)
		}

		flagKeyValue, err := cmd.Flags().GetString(flagKeyName)
		if err != nil {
			return err, false
		}
		m.Key = flagKeyValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveBatchRetestVulnConfigBodyHTTPConfigCookiesItemsPropValueFlags(depth int, m *models.BatchRetestVulnConfigBodyHTTPConfigCookiesItems, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagValueName := fmt.Sprintf("%v.value", cmdPrefix)
	if cmd.Flags().Changed(flagValueName) {

		var flagValueName string
		if cmdPrefix == "" {
			flagValueName = "value"
		} else {
			flagValueName = fmt.Sprintf("%v.value", cmdPrefix)
		}

		flagValueValue, err := cmd.Flags().GetString(flagValueName)
		if err != nil {
			return err, false
		}
		m.Value = flagValueValue

		retAdded = true
	}

	return nil, retAdded
}
