// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for CreateWhiteListBody

// register flags to command
func registerModelCreateWhiteListBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerCreateWhiteListBodyPropDesc(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateWhiteListBodyPropDisableDiscover(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateWhiteListBodyPropDisableVuln(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateWhiteListBodyPropEnabled(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateWhiteListBodyPropHostTarget(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateWhiteListBodyPropName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateWhiteListBodyPropProjectID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateWhiteListBodyPropSubProjectApply(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateWhiteListBodyPropURIForbiddenKey(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateWhiteListBodyPropWebTarget(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerCreateWhiteListBodyPropDesc(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagDescDescription := ``

	var flagDescName string
	if cmdPrefix == "" {
		flagDescName = "desc"
	} else {
		flagDescName = fmt.Sprintf("%v.desc", cmdPrefix)
	}

	var flagDescDefault string

	_ = cmd.PersistentFlags().String(flagDescName, flagDescDefault, flagDescDescription)

	return nil
}

func registerCreateWhiteListBodyPropDisableDiscover(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagDisableDiscoverDescription := `Required. 不进行资产发现`

	var flagDisableDiscoverName string
	if cmdPrefix == "" {
		flagDisableDiscoverName = "disable_discover"
	} else {
		flagDisableDiscoverName = fmt.Sprintf("%v.disable_discover", cmdPrefix)
	}

	var flagDisableDiscoverDefault bool

	_ = cmd.PersistentFlags().Bool(flagDisableDiscoverName, flagDisableDiscoverDefault, flagDisableDiscoverDescription)

	return nil
}

func registerCreateWhiteListBodyPropDisableVuln(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagDisableVulnDescription := `Required. 不进行漏洞检测`

	var flagDisableVulnName string
	if cmdPrefix == "" {
		flagDisableVulnName = "disable_vuln"
	} else {
		flagDisableVulnName = fmt.Sprintf("%v.disable_vuln", cmdPrefix)
	}

	var flagDisableVulnDefault bool

	_ = cmd.PersistentFlags().Bool(flagDisableVulnName, flagDisableVulnDefault, flagDisableVulnDescription)

	return nil
}

func registerCreateWhiteListBodyPropEnabled(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagEnabledDescription := `Required. 应用配置`

	var flagEnabledName string
	if cmdPrefix == "" {
		flagEnabledName = "enabled"
	} else {
		flagEnabledName = fmt.Sprintf("%v.enabled", cmdPrefix)
	}

	var flagEnabledDefault bool

	_ = cmd.PersistentFlags().Bool(flagEnabledName, flagEnabledDefault, flagEnabledDescription)

	return nil
}

func registerCreateWhiteListBodyPropHostTarget(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: host_target []string array type is not supported by go-swagger cli yet

	return nil
}

func registerCreateWhiteListBodyPropName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagNameDescription := `Required. `

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "name"
	} else {
		flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

func registerCreateWhiteListBodyPropProjectID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagProjectIDDescription := `Required. `

	var flagProjectIDName string
	if cmdPrefix == "" {
		flagProjectIDName = "project_id"
	} else {
		flagProjectIDName = fmt.Sprintf("%v.project_id", cmdPrefix)
	}

	var flagProjectIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagProjectIDName, flagProjectIDDefault, flagProjectIDDescription)

	return nil
}

func registerCreateWhiteListBodyPropSubProjectApply(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagSubProjectApplyDescription := `Required. 同步应用到子组织单位`

	var flagSubProjectApplyName string
	if cmdPrefix == "" {
		flagSubProjectApplyName = "sub_project_apply"
	} else {
		flagSubProjectApplyName = fmt.Sprintf("%v.sub_project_apply", cmdPrefix)
	}

	var flagSubProjectApplyDefault bool

	_ = cmd.PersistentFlags().Bool(flagSubProjectApplyName, flagSubProjectApplyDefault, flagSubProjectApplyDescription)

	return nil
}

func registerCreateWhiteListBodyPropURIForbiddenKey(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: uri_forbidden_key []string array type is not supported by go-swagger cli yet

	return nil
}

func registerCreateWhiteListBodyPropWebTarget(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: web_target []string array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelCreateWhiteListBodyFlags(depth int, m *models.CreateWhiteListBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, DescAdded := retrieveCreateWhiteListBodyPropDescFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DescAdded

	err, DisableDiscoverAdded := retrieveCreateWhiteListBodyPropDisableDiscoverFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DisableDiscoverAdded

	err, DisableVulnAdded := retrieveCreateWhiteListBodyPropDisableVulnFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DisableVulnAdded

	err, EnabledAdded := retrieveCreateWhiteListBodyPropEnabledFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || EnabledAdded

	err, HostTargetAdded := retrieveCreateWhiteListBodyPropHostTargetFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || HostTargetAdded

	err, NameAdded := retrieveCreateWhiteListBodyPropNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NameAdded

	err, ProjectIDAdded := retrieveCreateWhiteListBodyPropProjectIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ProjectIDAdded

	err, SubProjectApplyAdded := retrieveCreateWhiteListBodyPropSubProjectApplyFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || SubProjectApplyAdded

	err, URIForbiddenKeyAdded := retrieveCreateWhiteListBodyPropURIForbiddenKeyFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || URIForbiddenKeyAdded

	err, WebTargetAdded := retrieveCreateWhiteListBodyPropWebTargetFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || WebTargetAdded

	return nil, retAdded
}

func retrieveCreateWhiteListBodyPropDescFlags(depth int, m *models.CreateWhiteListBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDescName := fmt.Sprintf("%v.desc", cmdPrefix)
	if cmd.Flags().Changed(flagDescName) {

		var flagDescName string
		if cmdPrefix == "" {
			flagDescName = "desc"
		} else {
			flagDescName = fmt.Sprintf("%v.desc", cmdPrefix)
		}

		flagDescValue, err := cmd.Flags().GetString(flagDescName)
		if err != nil {
			return err, false
		}
		m.Desc = flagDescValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreateWhiteListBodyPropDisableDiscoverFlags(depth int, m *models.CreateWhiteListBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDisableDiscoverName := fmt.Sprintf("%v.disable_discover", cmdPrefix)
	if cmd.Flags().Changed(flagDisableDiscoverName) {

		var flagDisableDiscoverName string
		if cmdPrefix == "" {
			flagDisableDiscoverName = "disable_discover"
		} else {
			flagDisableDiscoverName = fmt.Sprintf("%v.disable_discover", cmdPrefix)
		}

		flagDisableDiscoverValue, err := cmd.Flags().GetBool(flagDisableDiscoverName)
		if err != nil {
			return err, false
		}
		m.DisableDiscover = &flagDisableDiscoverValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreateWhiteListBodyPropDisableVulnFlags(depth int, m *models.CreateWhiteListBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDisableVulnName := fmt.Sprintf("%v.disable_vuln", cmdPrefix)
	if cmd.Flags().Changed(flagDisableVulnName) {

		var flagDisableVulnName string
		if cmdPrefix == "" {
			flagDisableVulnName = "disable_vuln"
		} else {
			flagDisableVulnName = fmt.Sprintf("%v.disable_vuln", cmdPrefix)
		}

		flagDisableVulnValue, err := cmd.Flags().GetBool(flagDisableVulnName)
		if err != nil {
			return err, false
		}
		m.DisableVuln = &flagDisableVulnValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreateWhiteListBodyPropEnabledFlags(depth int, m *models.CreateWhiteListBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagEnabledName := fmt.Sprintf("%v.enabled", cmdPrefix)
	if cmd.Flags().Changed(flagEnabledName) {

		var flagEnabledName string
		if cmdPrefix == "" {
			flagEnabledName = "enabled"
		} else {
			flagEnabledName = fmt.Sprintf("%v.enabled", cmdPrefix)
		}

		flagEnabledValue, err := cmd.Flags().GetBool(flagEnabledName)
		if err != nil {
			return err, false
		}
		m.Enabled = &flagEnabledValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreateWhiteListBodyPropHostTargetFlags(depth int, m *models.CreateWhiteListBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagHostTargetName := fmt.Sprintf("%v.host_target", cmdPrefix)
	if cmd.Flags().Changed(flagHostTargetName) {
		// warning: host_target array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveCreateWhiteListBodyPropNameFlags(depth int, m *models.CreateWhiteListBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNameName := fmt.Sprintf("%v.name", cmdPrefix)
	if cmd.Flags().Changed(flagNameName) {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "name"
		} else {
			flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = &flagNameValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreateWhiteListBodyPropProjectIDFlags(depth int, m *models.CreateWhiteListBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagProjectIDName := fmt.Sprintf("%v.project_id", cmdPrefix)
	if cmd.Flags().Changed(flagProjectIDName) {

		var flagProjectIDName string
		if cmdPrefix == "" {
			flagProjectIDName = "project_id"
		} else {
			flagProjectIDName = fmt.Sprintf("%v.project_id", cmdPrefix)
		}

		flagProjectIDValue, err := cmd.Flags().GetInt64(flagProjectIDName)
		if err != nil {
			return err, false
		}
		m.ProjectID = &flagProjectIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreateWhiteListBodyPropSubProjectApplyFlags(depth int, m *models.CreateWhiteListBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagSubProjectApplyName := fmt.Sprintf("%v.sub_project_apply", cmdPrefix)
	if cmd.Flags().Changed(flagSubProjectApplyName) {

		var flagSubProjectApplyName string
		if cmdPrefix == "" {
			flagSubProjectApplyName = "sub_project_apply"
		} else {
			flagSubProjectApplyName = fmt.Sprintf("%v.sub_project_apply", cmdPrefix)
		}

		flagSubProjectApplyValue, err := cmd.Flags().GetBool(flagSubProjectApplyName)
		if err != nil {
			return err, false
		}
		m.SubProjectApply = &flagSubProjectApplyValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreateWhiteListBodyPropURIForbiddenKeyFlags(depth int, m *models.CreateWhiteListBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagURIForbiddenKeyName := fmt.Sprintf("%v.uri_forbidden_key", cmdPrefix)
	if cmd.Flags().Changed(flagURIForbiddenKeyName) {
		// warning: uri_forbidden_key array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveCreateWhiteListBodyPropWebTargetFlags(depth int, m *models.CreateWhiteListBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagWebTargetName := fmt.Sprintf("%v.web_target", cmdPrefix)
	if cmd.Flags().Changed(flagWebTargetName) {
		// warning: web_target array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
