// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for CreatePlanBody

// register flags to command
func registerModelCreatePlanBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerCreatePlanBodyPropActive(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreatePlanBodyPropBasicSetting(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreatePlanBodyPropDisabledWhitelistIds(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreatePlanBodyPropExecRightNow(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreatePlanBodyPropProjectID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreatePlanBodyPropTaskSetting(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreatePlanBodyPropTaskTemplateID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerCreatePlanBodyPropActive(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagActiveDescription := `Required. NOW 类型的不管这个属性, 是否循环`

	var flagActiveName string
	if cmdPrefix == "" {
		flagActiveName = "active"
	} else {
		flagActiveName = fmt.Sprintf("%v.active", cmdPrefix)
	}

	var flagActiveDefault bool

	_ = cmd.PersistentFlags().Bool(flagActiveName, flagActiveDefault, flagActiveDescription)

	return nil
}

func registerCreatePlanBodyPropBasicSetting(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagBasicSettingDescription := `Required. Plan 的一些设置，是个 json`

	var flagBasicSettingName string
	if cmdPrefix == "" {
		flagBasicSettingName = "basic_setting"
	} else {
		flagBasicSettingName = fmt.Sprintf("%v.basic_setting", cmdPrefix)
	}

	var flagBasicSettingDefault string

	_ = cmd.PersistentFlags().String(flagBasicSettingName, flagBasicSettingDefault, flagBasicSettingDescription)

	return nil
}

func registerCreatePlanBodyPropDisabledWhitelistIds(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: disabled_whitelist_ids []int64 array type is not supported by go-swagger cli yet

	return nil
}

func registerCreatePlanBodyPropExecRightNow(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagExecRightNowDescription := `默认是 true，true 为保存并立即执行，即立即执行一次，不影响排期`

	var flagExecRightNowName string
	if cmdPrefix == "" {
		flagExecRightNowName = "exec_right_now"
	} else {
		flagExecRightNowName = fmt.Sprintf("%v.exec_right_now", cmdPrefix)
	}

	var flagExecRightNowDefault bool

	_ = cmd.PersistentFlags().Bool(flagExecRightNowName, flagExecRightNowDefault, flagExecRightNowDescription)

	return nil
}

func registerCreatePlanBodyPropProjectID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagProjectIDDescription := `对应的工作区的 ID`

	var flagProjectIDName string
	if cmdPrefix == "" {
		flagProjectIDName = "project_id"
	} else {
		flagProjectIDName = fmt.Sprintf("%v.project_id", cmdPrefix)
	}

	var flagProjectIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagProjectIDName, flagProjectIDDefault, flagProjectIDDescription)

	return nil
}

func registerCreatePlanBodyPropTaskSetting(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagTaskSettingDescription := `Plan 的一些设置，默认是 task template 的 task setting`

	var flagTaskSettingName string
	if cmdPrefix == "" {
		flagTaskSettingName = "task_setting"
	} else {
		flagTaskSettingName = fmt.Sprintf("%v.task_setting", cmdPrefix)
	}

	var flagTaskSettingDefault string

	_ = cmd.PersistentFlags().String(flagTaskSettingName, flagTaskSettingDefault, flagTaskSettingDescription)

	return nil
}

func registerCreatePlanBodyPropTaskTemplateID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagTaskTemplateIDDescription := `Required. 对应的模板的 ID`

	var flagTaskTemplateIDName string
	if cmdPrefix == "" {
		flagTaskTemplateIDName = "task_template_id"
	} else {
		flagTaskTemplateIDName = fmt.Sprintf("%v.task_template_id", cmdPrefix)
	}

	var flagTaskTemplateIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagTaskTemplateIDName, flagTaskTemplateIDDefault, flagTaskTemplateIDDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelCreatePlanBodyFlags(depth int, m *models.CreatePlanBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, ActiveAdded := retrieveCreatePlanBodyPropActiveFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ActiveAdded

	err, BasicSettingAdded := retrieveCreatePlanBodyPropBasicSettingFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || BasicSettingAdded

	err, DisabledWhitelistIdsAdded := retrieveCreatePlanBodyPropDisabledWhitelistIdsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DisabledWhitelistIdsAdded

	err, ExecRightNowAdded := retrieveCreatePlanBodyPropExecRightNowFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ExecRightNowAdded

	err, ProjectIDAdded := retrieveCreatePlanBodyPropProjectIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ProjectIDAdded

	err, TaskSettingAdded := retrieveCreatePlanBodyPropTaskSettingFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || TaskSettingAdded

	err, TaskTemplateIDAdded := retrieveCreatePlanBodyPropTaskTemplateIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || TaskTemplateIDAdded

	return nil, retAdded
}

func retrieveCreatePlanBodyPropActiveFlags(depth int, m *models.CreatePlanBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagActiveName := fmt.Sprintf("%v.active", cmdPrefix)
	if cmd.Flags().Changed(flagActiveName) {

		var flagActiveName string
		if cmdPrefix == "" {
			flagActiveName = "active"
		} else {
			flagActiveName = fmt.Sprintf("%v.active", cmdPrefix)
		}

		flagActiveValue, err := cmd.Flags().GetBool(flagActiveName)
		if err != nil {
			return err, false
		}
		m.Active = &flagActiveValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreatePlanBodyPropBasicSettingFlags(depth int, m *models.CreatePlanBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagBasicSettingName := fmt.Sprintf("%v.basic_setting", cmdPrefix)
	if cmd.Flags().Changed(flagBasicSettingName) {

		var flagBasicSettingName string
		if cmdPrefix == "" {
			flagBasicSettingName = "basic_setting"
		} else {
			flagBasicSettingName = fmt.Sprintf("%v.basic_setting", cmdPrefix)
		}

		flagBasicSettingValue, err := cmd.Flags().GetString(flagBasicSettingName)
		if err != nil {
			return err, false
		}
		m.BasicSetting = &flagBasicSettingValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreatePlanBodyPropDisabledWhitelistIdsFlags(depth int, m *models.CreatePlanBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDisabledWhitelistIdsName := fmt.Sprintf("%v.disabled_whitelist_ids", cmdPrefix)
	if cmd.Flags().Changed(flagDisabledWhitelistIdsName) {
		// warning: disabled_whitelist_ids array type []int64 is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveCreatePlanBodyPropExecRightNowFlags(depth int, m *models.CreatePlanBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagExecRightNowName := fmt.Sprintf("%v.exec_right_now", cmdPrefix)
	if cmd.Flags().Changed(flagExecRightNowName) {

		var flagExecRightNowName string
		if cmdPrefix == "" {
			flagExecRightNowName = "exec_right_now"
		} else {
			flagExecRightNowName = fmt.Sprintf("%v.exec_right_now", cmdPrefix)
		}

		flagExecRightNowValue, err := cmd.Flags().GetBool(flagExecRightNowName)
		if err != nil {
			return err, false
		}
		m.ExecRightNow = flagExecRightNowValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreatePlanBodyPropProjectIDFlags(depth int, m *models.CreatePlanBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagProjectIDName := fmt.Sprintf("%v.project_id", cmdPrefix)
	if cmd.Flags().Changed(flagProjectIDName) {

		var flagProjectIDName string
		if cmdPrefix == "" {
			flagProjectIDName = "project_id"
		} else {
			flagProjectIDName = fmt.Sprintf("%v.project_id", cmdPrefix)
		}

		flagProjectIDValue, err := cmd.Flags().GetInt64(flagProjectIDName)
		if err != nil {
			return err, false
		}
		m.ProjectID = flagProjectIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreatePlanBodyPropTaskSettingFlags(depth int, m *models.CreatePlanBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagTaskSettingName := fmt.Sprintf("%v.task_setting", cmdPrefix)
	if cmd.Flags().Changed(flagTaskSettingName) {

		var flagTaskSettingName string
		if cmdPrefix == "" {
			flagTaskSettingName = "task_setting"
		} else {
			flagTaskSettingName = fmt.Sprintf("%v.task_setting", cmdPrefix)
		}

		flagTaskSettingValue, err := cmd.Flags().GetString(flagTaskSettingName)
		if err != nil {
			return err, false
		}
		m.TaskSetting = flagTaskSettingValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreatePlanBodyPropTaskTemplateIDFlags(depth int, m *models.CreatePlanBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagTaskTemplateIDName := fmt.Sprintf("%v.task_template_id", cmdPrefix)
	if cmd.Flags().Changed(flagTaskTemplateIDName) {

		var flagTaskTemplateIDName string
		if cmdPrefix == "" {
			flagTaskTemplateIDName = "task_template_id"
		} else {
			flagTaskTemplateIDName = fmt.Sprintf("%v.task_template_id", cmdPrefix)
		}

		flagTaskTemplateIDValue, err := cmd.Flags().GetInt64(flagTaskTemplateIDName)
		if err != nil {
			return err, false
		}
		m.TaskTemplateID = &flagTaskTemplateIDValue

		retAdded = true
	}

	return nil, retAdded
}
