// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for CreateXProcessReportBody

// register flags to command
func registerModelCreateXProcessReportBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerCreateXProcessReportBodyPropExportRelatedAssetInfo(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateXProcessReportBodyPropExportRelatedVulnInfo(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateXProcessReportBodyPropName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateXProcessReportBodyPropReportTemplateID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateXProcessReportBodyPropReportType(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateXProcessReportBodyPropTargetFileFormat(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateXProcessReportBodyPropXprocessID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCreateXProcessReportBodyPropXprocessIDList(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerCreateXProcessReportBodyPropExportRelatedAssetInfo(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagExportRelatedAssetInfoDescription := `Required. 导出相关联的资产信息`

	var flagExportRelatedAssetInfoName string
	if cmdPrefix == "" {
		flagExportRelatedAssetInfoName = "export_related_asset_info"
	} else {
		flagExportRelatedAssetInfoName = fmt.Sprintf("%v.export_related_asset_info", cmdPrefix)
	}

	var flagExportRelatedAssetInfoDefault bool

	_ = cmd.PersistentFlags().Bool(flagExportRelatedAssetInfoName, flagExportRelatedAssetInfoDefault, flagExportRelatedAssetInfoDescription)

	return nil
}

func registerCreateXProcessReportBodyPropExportRelatedVulnInfo(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagExportRelatedVulnInfoDescription := `Required. 导出相关联的漏洞`

	var flagExportRelatedVulnInfoName string
	if cmdPrefix == "" {
		flagExportRelatedVulnInfoName = "export_related_vuln_info"
	} else {
		flagExportRelatedVulnInfoName = fmt.Sprintf("%v.export_related_vuln_info", cmdPrefix)
	}

	var flagExportRelatedVulnInfoDefault bool

	_ = cmd.PersistentFlags().Bool(flagExportRelatedVulnInfoName, flagExportRelatedVulnInfoDefault, flagExportRelatedVulnInfoDescription)

	return nil
}

func registerCreateXProcessReportBodyPropName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagNameDescription := `Required. 报表命名(最大54位字符长度)`

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "name"
	} else {
		flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

func registerCreateXProcessReportBodyPropReportTemplateID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagReportTemplateIDDescription := `报表模板id，默认为内置模板`

	var flagReportTemplateIDName string
	if cmdPrefix == "" {
		flagReportTemplateIDName = "report_template_id"
	} else {
		flagReportTemplateIDName = fmt.Sprintf("%v.report_template_id", cmdPrefix)
	}

	var flagReportTemplateIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagReportTemplateIDName, flagReportTemplateIDDefault, flagReportTemplateIDDescription)

	return nil
}

func registerCreateXProcessReportBodyPropReportType(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagReportTypeDescription := `Enum: ["XPROCESS"]. Required. `

	var flagReportTypeName string
	if cmdPrefix == "" {
		flagReportTypeName = "report_type"
	} else {
		flagReportTypeName = fmt.Sprintf("%v.report_type", cmdPrefix)
	}

	var flagReportTypeDefault string

	_ = cmd.PersistentFlags().String(flagReportTypeName, flagReportTypeDefault, flagReportTypeDescription)

	if err := cmd.RegisterFlagCompletionFunc(flagReportTypeName,
		func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
			var res []string
			if err := json.Unmarshal([]byte(`["XPROCESS"]`), &res); err != nil {
				panic(err)
			}
			return res, cobra.ShellCompDirectiveDefault
		}); err != nil {
		return err
	}

	return nil
}

func registerCreateXProcessReportBodyPropTargetFileFormat(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: target_file_format []string array type is not supported by go-swagger cli yet

	return nil
}

func registerCreateXProcessReportBodyPropXprocessID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagXprocessIDDescription := `xprocess的id，如果同时指定了xprocess_id_list，则xprocess_id_list优先`

	var flagXprocessIDName string
	if cmdPrefix == "" {
		flagXprocessIDName = "xprocess_id"
	} else {
		flagXprocessIDName = fmt.Sprintf("%v.xprocess_id", cmdPrefix)
	}

	var flagXprocessIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagXprocessIDName, flagXprocessIDDefault, flagXprocessIDDescription)

	return nil
}

func registerCreateXProcessReportBodyPropXprocessIDList(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: xprocess_id_list []int64 array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelCreateXProcessReportBodyFlags(depth int, m *models.CreateXProcessReportBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, ExportRelatedAssetInfoAdded := retrieveCreateXProcessReportBodyPropExportRelatedAssetInfoFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ExportRelatedAssetInfoAdded

	err, ExportRelatedVulnInfoAdded := retrieveCreateXProcessReportBodyPropExportRelatedVulnInfoFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ExportRelatedVulnInfoAdded

	err, NameAdded := retrieveCreateXProcessReportBodyPropNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NameAdded

	err, ReportTemplateIDAdded := retrieveCreateXProcessReportBodyPropReportTemplateIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ReportTemplateIDAdded

	err, ReportTypeAdded := retrieveCreateXProcessReportBodyPropReportTypeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ReportTypeAdded

	err, TargetFileFormatAdded := retrieveCreateXProcessReportBodyPropTargetFileFormatFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || TargetFileFormatAdded

	err, XprocessIDAdded := retrieveCreateXProcessReportBodyPropXprocessIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || XprocessIDAdded

	err, XprocessIDListAdded := retrieveCreateXProcessReportBodyPropXprocessIDListFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || XprocessIDListAdded

	return nil, retAdded
}

func retrieveCreateXProcessReportBodyPropExportRelatedAssetInfoFlags(depth int, m *models.CreateXProcessReportBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagExportRelatedAssetInfoName := fmt.Sprintf("%v.export_related_asset_info", cmdPrefix)
	if cmd.Flags().Changed(flagExportRelatedAssetInfoName) {

		var flagExportRelatedAssetInfoName string
		if cmdPrefix == "" {
			flagExportRelatedAssetInfoName = "export_related_asset_info"
		} else {
			flagExportRelatedAssetInfoName = fmt.Sprintf("%v.export_related_asset_info", cmdPrefix)
		}

		flagExportRelatedAssetInfoValue, err := cmd.Flags().GetBool(flagExportRelatedAssetInfoName)
		if err != nil {
			return err, false
		}
		m.ExportRelatedAssetInfo = &flagExportRelatedAssetInfoValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreateXProcessReportBodyPropExportRelatedVulnInfoFlags(depth int, m *models.CreateXProcessReportBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagExportRelatedVulnInfoName := fmt.Sprintf("%v.export_related_vuln_info", cmdPrefix)
	if cmd.Flags().Changed(flagExportRelatedVulnInfoName) {

		var flagExportRelatedVulnInfoName string
		if cmdPrefix == "" {
			flagExportRelatedVulnInfoName = "export_related_vuln_info"
		} else {
			flagExportRelatedVulnInfoName = fmt.Sprintf("%v.export_related_vuln_info", cmdPrefix)
		}

		flagExportRelatedVulnInfoValue, err := cmd.Flags().GetBool(flagExportRelatedVulnInfoName)
		if err != nil {
			return err, false
		}
		m.ExportRelatedVulnInfo = &flagExportRelatedVulnInfoValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreateXProcessReportBodyPropNameFlags(depth int, m *models.CreateXProcessReportBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNameName := fmt.Sprintf("%v.name", cmdPrefix)
	if cmd.Flags().Changed(flagNameName) {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "name"
		} else {
			flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = &flagNameValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreateXProcessReportBodyPropReportTemplateIDFlags(depth int, m *models.CreateXProcessReportBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagReportTemplateIDName := fmt.Sprintf("%v.report_template_id", cmdPrefix)
	if cmd.Flags().Changed(flagReportTemplateIDName) {

		var flagReportTemplateIDName string
		if cmdPrefix == "" {
			flagReportTemplateIDName = "report_template_id"
		} else {
			flagReportTemplateIDName = fmt.Sprintf("%v.report_template_id", cmdPrefix)
		}

		flagReportTemplateIDValue, err := cmd.Flags().GetInt64(flagReportTemplateIDName)
		if err != nil {
			return err, false
		}
		m.ReportTemplateID = flagReportTemplateIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreateXProcessReportBodyPropReportTypeFlags(depth int, m *models.CreateXProcessReportBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagReportTypeName := fmt.Sprintf("%v.report_type", cmdPrefix)
	if cmd.Flags().Changed(flagReportTypeName) {

		var flagReportTypeName string
		if cmdPrefix == "" {
			flagReportTypeName = "report_type"
		} else {
			flagReportTypeName = fmt.Sprintf("%v.report_type", cmdPrefix)
		}

		flagReportTypeValue, err := cmd.Flags().GetString(flagReportTypeName)
		if err != nil {
			return err, false
		}
		m.ReportType = &flagReportTypeValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreateXProcessReportBodyPropTargetFileFormatFlags(depth int, m *models.CreateXProcessReportBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagTargetFileFormatName := fmt.Sprintf("%v.target_file_format", cmdPrefix)
	if cmd.Flags().Changed(flagTargetFileFormatName) {
		// warning: target_file_format array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveCreateXProcessReportBodyPropXprocessIDFlags(depth int, m *models.CreateXProcessReportBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagXprocessIDName := fmt.Sprintf("%v.xprocess_id", cmdPrefix)
	if cmd.Flags().Changed(flagXprocessIDName) {

		var flagXprocessIDName string
		if cmdPrefix == "" {
			flagXprocessIDName = "xprocess_id"
		} else {
			flagXprocessIDName = fmt.Sprintf("%v.xprocess_id", cmdPrefix)
		}

		flagXprocessIDValue, err := cmd.Flags().GetInt64(flagXprocessIDName)
		if err != nil {
			return err, false
		}
		m.XprocessID = flagXprocessIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCreateXProcessReportBodyPropXprocessIDListFlags(depth int, m *models.CreateXProcessReportBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagXprocessIDListName := fmt.Sprintf("%v.xprocess_id_list", cmdPrefix)
	if cmd.Flags().Changed(flagXprocessIDListName) {
		// warning: xprocess_id_list array type []int64 is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
