// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for DeleteScannerDictResponseItem

// register flags to command
func registerModelDeleteScannerDictResponseItemFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerDeleteScannerDictResponseItemPropName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerDeleteScannerDictResponseItemPropName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagNameDescription := `Required. 删除了的字典名`

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "name"
	} else {
		flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelDeleteScannerDictResponseItemFlags(depth int, m *models.DeleteScannerDictResponseItem, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, NameAdded := retrieveDeleteScannerDictResponseItemPropNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NameAdded

	return nil, retAdded
}

func retrieveDeleteScannerDictResponseItemPropNameFlags(depth int, m *models.DeleteScannerDictResponseItem, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNameName := fmt.Sprintf("%v.name", cmdPrefix)
	if cmd.Flags().Changed(flagNameName) {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "name"
		} else {
			flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = &flagNameValue

		retAdded = true
	}

	return nil, retAdded
}
