// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for GetSystemDNSEngineIDOKBodyData

// register flags to command
func registerModelGetSystemDNSEngineIDOKBodyDataFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerGetSystemDNSEngineIDOKBodyDataPropDNS(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerGetSystemDNSEngineIDOKBodyDataPropDNS(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: dns []string array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelGetSystemDNSEngineIDOKBodyDataFlags(depth int, m *models.GetSystemDNSEngineIDOKBodyData, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, DNSAdded := retrieveGetSystemDNSEngineIDOKBodyDataPropDNSFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DNSAdded

	return nil, retAdded
}

func retrieveGetSystemDNSEngineIDOKBodyDataPropDNSFlags(depth int, m *models.GetSystemDNSEngineIDOKBodyData, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDNSName := fmt.Sprintf("%v.dns", cmdPrefix)
	if cmd.Flags().Changed(flagDNSName) {
		// warning: dns array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
