// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for GetTemplateOKBodyData

// register flags to command
func registerModelGetTemplateOKBodyDataFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerGetTemplateOKBodyDataPropContent(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerGetTemplateOKBodyDataPropTotal(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerGetTemplateOKBodyDataPropContent(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: content []*TaskTemplateResponse array type is not supported by go-swagger cli yet

	return nil
}

func registerGetTemplateOKBodyDataPropTotal(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagTotalDescription := `Required. `

	var flagTotalName string
	if cmdPrefix == "" {
		flagTotalName = "total"
	} else {
		flagTotalName = fmt.Sprintf("%v.total", cmdPrefix)
	}

	var flagTotalDefault int64

	_ = cmd.PersistentFlags().Int64(flagTotalName, flagTotalDefault, flagTotalDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelGetTemplateOKBodyDataFlags(depth int, m *models.GetTemplateOKBodyData, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, ContentAdded := retrieveGetTemplateOKBodyDataPropContentFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ContentAdded

	err, TotalAdded := retrieveGetTemplateOKBodyDataPropTotalFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || TotalAdded

	return nil, retAdded
}

func retrieveGetTemplateOKBodyDataPropContentFlags(depth int, m *models.GetTemplateOKBodyData, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagContentName := fmt.Sprintf("%v.content", cmdPrefix)
	if cmd.Flags().Changed(flagContentName) {
		// warning: content array type []*TaskTemplateResponse is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveGetTemplateOKBodyDataPropTotalFlags(depth int, m *models.GetTemplateOKBodyData, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagTotalName := fmt.Sprintf("%v.total", cmdPrefix)
	if cmd.Flags().Changed(flagTotalName) {

		var flagTotalName string
		if cmdPrefix == "" {
			flagTotalName = "total"
		} else {
			flagTotalName = fmt.Sprintf("%v.total", cmdPrefix)
		}

		flagTotalValue, err := cmd.Flags().GetInt64(flagTotalName)
		if err != nil {
			return err, false
		}
		m.Total = &flagTotalValue

		retAdded = true
	}

	return nil, retAdded
}
