// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/xray/client/vulnerability"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationVulnerabilityGetVulnRetestTaskIDCmd returns a command to handle operation getVulnRetestTaskId
func makeOperationVulnerabilityGetVulnRetestTaskIDCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "GetVulnRetestTaskID",
		Short: `漏洞资产复测结果获取`,
		RunE:  runOperationVulnerabilityGetVulnRetestTaskID,
	}

	if err := registerOperationVulnerabilityGetVulnRetestTaskIDParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationVulnerabilityGetVulnRetestTaskID uses cmd flags to call endpoint api
func runOperationVulnerabilityGetVulnRetestTaskID(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := vulnerability.NewGetVulnRetestTaskIDParams()
	if err, _ = retrieveOperationVulnerabilityGetVulnRetestTaskIDTaskIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationVulnerabilityGetVulnRetestTaskIDResult(appCli.Vulnerability.GetVulnRetestTaskID(params, nil))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationVulnerabilityGetVulnRetestTaskIDParamFlags registers all flags needed to fill params
func registerOperationVulnerabilityGetVulnRetestTaskIDParamFlags(cmd *cobra.Command) error {
	if err := registerOperationVulnerabilityGetVulnRetestTaskIDTaskIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationVulnerabilityGetVulnRetestTaskIDTaskIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagTaskIDDescription := `Required. 要获取的漏洞复测任务的 task_id`

	var flagTaskIDName string
	if cmdPrefix == "" {
		flagTaskIDName = "task_id"
	} else {
		flagTaskIDName = fmt.Sprintf("%v.task_id", cmdPrefix)
	}

	var flagTaskIDDefault string

	_ = cmd.PersistentFlags().String(flagTaskIDName, flagTaskIDDefault, flagTaskIDDescription)

	return nil
}

func retrieveOperationVulnerabilityGetVulnRetestTaskIDTaskIDFlag(m *vulnerability.GetVulnRetestTaskIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("task_id") {

		var flagTaskIDName string
		if cmdPrefix == "" {
			flagTaskIDName = "task_id"
		} else {
			flagTaskIDName = fmt.Sprintf("%v.task_id", cmdPrefix)
		}

		flagTaskIDValue, err := cmd.Flags().GetString(flagTaskIDName)
		if err != nil {
			return err, false
		}
		m.TaskID = flagTaskIDValue

	}

	return nil, retAdded
}

// parseOperationVulnerabilityGetVulnRetestTaskIDResult parses request result and return the string content
func parseOperationVulnerabilityGetVulnRetestTaskIDResult(resp0 *vulnerability.GetVulnRetestTaskIDOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		var iResp0 any = respErr
		eresp0, ok := iResp0.(*vulnerability.GetVulnRetestTaskIDOK)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp0) && !swag.IsZero(eresp0.Payload) {
				msgStr, err := json.Marshal(eresp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}
	return "", nil
}
