// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for LicenseResponse

// register flags to command
func registerModelLicenseResponseFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerLicenseResponsePropCannotUpgradeAfter(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerLicenseResponsePropCannotUpgradeBefore(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerLicenseResponsePropClientName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerLicenseResponsePropEdition(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerLicenseResponsePropEditiontype(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerLicenseResponsePropExtensivePermissions(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerLicenseResponsePropInitialPassword(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerLicenseResponsePropLicenseID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerLicenseResponsePropMachineIds(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerLicenseResponsePropMaxConcurrentScan(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerLicenseResponsePropNotValidAfter(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerLicenseResponsePropNotValidBefore(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerLicenseResponsePropPermissions(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerLicenseResponsePropPlatformVersions(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerLicenseResponsePropScanEngineNum(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerLicenseResponsePropTemplate(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerLicenseResponsePropCannotUpgradeAfter(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCannotUpgradeAfterDescription := `版本型维保日期结束时间,控制引擎和漏洞库升级期的参数,日期范围内可升级`

	var flagCannotUpgradeAfterName string
	if cmdPrefix == "" {
		flagCannotUpgradeAfterName = "cannot_upgrade_after"
	} else {
		flagCannotUpgradeAfterName = fmt.Sprintf("%v.cannot_upgrade_after", cmdPrefix)
	}

	var flagCannotUpgradeAfterDefault string

	_ = cmd.PersistentFlags().String(flagCannotUpgradeAfterName, flagCannotUpgradeAfterDefault, flagCannotUpgradeAfterDescription)

	return nil
}

func registerLicenseResponsePropCannotUpgradeBefore(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCannotUpgradeBeforeDescription := `维保日期开始时间`

	var flagCannotUpgradeBeforeName string
	if cmdPrefix == "" {
		flagCannotUpgradeBeforeName = "cannot_upgrade_before"
	} else {
		flagCannotUpgradeBeforeName = fmt.Sprintf("%v.cannot_upgrade_before", cmdPrefix)
	}

	var flagCannotUpgradeBeforeDefault string

	_ = cmd.PersistentFlags().String(flagCannotUpgradeBeforeName, flagCannotUpgradeBeforeDefault, flagCannotUpgradeBeforeDescription)

	return nil
}

func registerLicenseResponsePropClientName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagClientNameDescription := `Required. 客户名称`

	var flagClientNameName string
	if cmdPrefix == "" {
		flagClientNameName = "client_name"
	} else {
		flagClientNameName = fmt.Sprintf("%v.client_name", cmdPrefix)
	}

	var flagClientNameDefault string

	_ = cmd.PersistentFlags().String(flagClientNameName, flagClientNameDefault, flagClientNameDescription)

	return nil
}

func registerLicenseResponsePropEdition(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagEditionDescription := `Required. 版本型`

	var flagEditionName string
	if cmdPrefix == "" {
		flagEditionName = "edition"
	} else {
		flagEditionName = fmt.Sprintf("%v.edition", cmdPrefix)
	}

	var flagEditionDefault string

	_ = cmd.PersistentFlags().String(flagEditionName, flagEditionDefault, flagEditionDescription)

	return nil
}

func registerLicenseResponsePropEditiontype(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagEditiontypeDescription := `版本名称`

	var flagEditiontypeName string
	if cmdPrefix == "" {
		flagEditiontypeName = "editiontype"
	} else {
		flagEditiontypeName = fmt.Sprintf("%v.editiontype", cmdPrefix)
	}

	var flagEditiontypeDefault string

	_ = cmd.PersistentFlags().String(flagEditiontypeName, flagEditiontypeDefault, flagEditiontypeDescription)

	return nil
}

func registerLicenseResponsePropExtensivePermissions(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: extensive_permissions []string array type is not supported by go-swagger cli yet

	return nil
}

func registerLicenseResponsePropInitialPassword(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagInitialPasswordDescription := `Required. 初始密码`

	var flagInitialPasswordName string
	if cmdPrefix == "" {
		flagInitialPasswordName = "initial_password"
	} else {
		flagInitialPasswordName = fmt.Sprintf("%v.initial_password", cmdPrefix)
	}

	var flagInitialPasswordDefault string

	_ = cmd.PersistentFlags().String(flagInitialPasswordName, flagInitialPasswordDefault, flagInitialPasswordDescription)

	return nil
}

func registerLicenseResponsePropLicenseID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagLicenseIDDescription := `Required. license id`

	var flagLicenseIDName string
	if cmdPrefix == "" {
		flagLicenseIDName = "license_id"
	} else {
		flagLicenseIDName = fmt.Sprintf("%v.license_id", cmdPrefix)
	}

	var flagLicenseIDDefault string

	_ = cmd.PersistentFlags().String(flagLicenseIDName, flagLicenseIDDefault, flagLicenseIDDescription)

	return nil
}

func registerLicenseResponsePropMachineIds(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagMachineIdsDescription := `机器码`

	var flagMachineIdsName string
	if cmdPrefix == "" {
		flagMachineIdsName = "machine_ids"
	} else {
		flagMachineIdsName = fmt.Sprintf("%v.machine_ids", cmdPrefix)
	}

	var flagMachineIdsDefault string

	_ = cmd.PersistentFlags().String(flagMachineIdsName, flagMachineIdsDefault, flagMachineIdsDescription)

	return nil
}

func registerLicenseResponsePropMaxConcurrentScan(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagMaxConcurrentScanDescription := `Required. 最大并发扫描数`

	var flagMaxConcurrentScanName string
	if cmdPrefix == "" {
		flagMaxConcurrentScanName = "max_concurrent_scan"
	} else {
		flagMaxConcurrentScanName = fmt.Sprintf("%v.max_concurrent_scan", cmdPrefix)
	}

	var flagMaxConcurrentScanDefault int64

	_ = cmd.PersistentFlags().Int64(flagMaxConcurrentScanName, flagMaxConcurrentScanDefault, flagMaxConcurrentScanDescription)

	return nil
}

func registerLicenseResponsePropNotValidAfter(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagNotValidAfterDescription := `截止授权日期`

	var flagNotValidAfterName string
	if cmdPrefix == "" {
		flagNotValidAfterName = "not_valid_after"
	} else {
		flagNotValidAfterName = fmt.Sprintf("%v.not_valid_after", cmdPrefix)
	}

	var flagNotValidAfterDefault string

	_ = cmd.PersistentFlags().String(flagNotValidAfterName, flagNotValidAfterDefault, flagNotValidAfterDescription)

	return nil
}

func registerLicenseResponsePropNotValidBefore(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagNotValidBeforeDescription := `授权开始日期，租用型，日期范围内平台可访问`

	var flagNotValidBeforeName string
	if cmdPrefix == "" {
		flagNotValidBeforeName = "not_valid_before"
	} else {
		flagNotValidBeforeName = fmt.Sprintf("%v.not_valid_before", cmdPrefix)
	}

	var flagNotValidBeforeDefault string

	_ = cmd.PersistentFlags().String(flagNotValidBeforeName, flagNotValidBeforeDefault, flagNotValidBeforeDescription)

	return nil
}

func registerLicenseResponsePropPermissions(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: permissions []string array type is not supported by go-swagger cli yet

	return nil
}

func registerLicenseResponsePropPlatformVersions(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: platform_versions [][]string array type is not supported by go-swagger cli yet

	return nil
}

func registerLicenseResponsePropScanEngineNum(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagScanEngineNumDescription := `Required. 授权引擎数量`

	var flagScanEngineNumName string
	if cmdPrefix == "" {
		flagScanEngineNumName = "scan_engine_num"
	} else {
		flagScanEngineNumName = fmt.Sprintf("%v.scan_engine_num", cmdPrefix)
	}

	var flagScanEngineNumDefault int64

	_ = cmd.PersistentFlags().Int64(flagScanEngineNumName, flagScanEngineNumDefault, flagScanEngineNumDescription)

	return nil
}

func registerLicenseResponsePropTemplate(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: template []string array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelLicenseResponseFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, CannotUpgradeAfterAdded := retrieveLicenseResponsePropCannotUpgradeAfterFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CannotUpgradeAfterAdded

	err, CannotUpgradeBeforeAdded := retrieveLicenseResponsePropCannotUpgradeBeforeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CannotUpgradeBeforeAdded

	err, ClientNameAdded := retrieveLicenseResponsePropClientNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ClientNameAdded

	err, EditionAdded := retrieveLicenseResponsePropEditionFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || EditionAdded

	err, EditiontypeAdded := retrieveLicenseResponsePropEditiontypeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || EditiontypeAdded

	err, ExtensivePermissionsAdded := retrieveLicenseResponsePropExtensivePermissionsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ExtensivePermissionsAdded

	err, InitialPasswordAdded := retrieveLicenseResponsePropInitialPasswordFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || InitialPasswordAdded

	err, LicenseIDAdded := retrieveLicenseResponsePropLicenseIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || LicenseIDAdded

	err, MachineIdsAdded := retrieveLicenseResponsePropMachineIdsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MachineIdsAdded

	err, MaxConcurrentScanAdded := retrieveLicenseResponsePropMaxConcurrentScanFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MaxConcurrentScanAdded

	err, NotValidAfterAdded := retrieveLicenseResponsePropNotValidAfterFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NotValidAfterAdded

	err, NotValidBeforeAdded := retrieveLicenseResponsePropNotValidBeforeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NotValidBeforeAdded

	err, PermissionsAdded := retrieveLicenseResponsePropPermissionsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PermissionsAdded

	err, PlatformVersionsAdded := retrieveLicenseResponsePropPlatformVersionsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PlatformVersionsAdded

	err, ScanEngineNumAdded := retrieveLicenseResponsePropScanEngineNumFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ScanEngineNumAdded

	err, TemplateAdded := retrieveLicenseResponsePropTemplateFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || TemplateAdded

	return nil, retAdded
}

func retrieveLicenseResponsePropCannotUpgradeAfterFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCannotUpgradeAfterName := fmt.Sprintf("%v.cannot_upgrade_after", cmdPrefix)
	if cmd.Flags().Changed(flagCannotUpgradeAfterName) {

		var flagCannotUpgradeAfterName string
		if cmdPrefix == "" {
			flagCannotUpgradeAfterName = "cannot_upgrade_after"
		} else {
			flagCannotUpgradeAfterName = fmt.Sprintf("%v.cannot_upgrade_after", cmdPrefix)
		}

		flagCannotUpgradeAfterValue, err := cmd.Flags().GetString(flagCannotUpgradeAfterName)
		if err != nil {
			return err, false
		}
		m.CannotUpgradeAfter = flagCannotUpgradeAfterValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveLicenseResponsePropCannotUpgradeBeforeFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCannotUpgradeBeforeName := fmt.Sprintf("%v.cannot_upgrade_before", cmdPrefix)
	if cmd.Flags().Changed(flagCannotUpgradeBeforeName) {

		var flagCannotUpgradeBeforeName string
		if cmdPrefix == "" {
			flagCannotUpgradeBeforeName = "cannot_upgrade_before"
		} else {
			flagCannotUpgradeBeforeName = fmt.Sprintf("%v.cannot_upgrade_before", cmdPrefix)
		}

		flagCannotUpgradeBeforeValue, err := cmd.Flags().GetString(flagCannotUpgradeBeforeName)
		if err != nil {
			return err, false
		}
		m.CannotUpgradeBefore = flagCannotUpgradeBeforeValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveLicenseResponsePropClientNameFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagClientNameName := fmt.Sprintf("%v.client_name", cmdPrefix)
	if cmd.Flags().Changed(flagClientNameName) {

		var flagClientNameName string
		if cmdPrefix == "" {
			flagClientNameName = "client_name"
		} else {
			flagClientNameName = fmt.Sprintf("%v.client_name", cmdPrefix)
		}

		flagClientNameValue, err := cmd.Flags().GetString(flagClientNameName)
		if err != nil {
			return err, false
		}
		m.ClientName = &flagClientNameValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveLicenseResponsePropEditionFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagEditionName := fmt.Sprintf("%v.edition", cmdPrefix)
	if cmd.Flags().Changed(flagEditionName) {

		var flagEditionName string
		if cmdPrefix == "" {
			flagEditionName = "edition"
		} else {
			flagEditionName = fmt.Sprintf("%v.edition", cmdPrefix)
		}

		flagEditionValue, err := cmd.Flags().GetString(flagEditionName)
		if err != nil {
			return err, false
		}
		m.Edition = &flagEditionValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveLicenseResponsePropEditiontypeFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagEditiontypeName := fmt.Sprintf("%v.editiontype", cmdPrefix)
	if cmd.Flags().Changed(flagEditiontypeName) {

		var flagEditiontypeName string
		if cmdPrefix == "" {
			flagEditiontypeName = "editiontype"
		} else {
			flagEditiontypeName = fmt.Sprintf("%v.editiontype", cmdPrefix)
		}

		flagEditiontypeValue, err := cmd.Flags().GetString(flagEditiontypeName)
		if err != nil {
			return err, false
		}
		m.Editiontype = flagEditiontypeValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveLicenseResponsePropExtensivePermissionsFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagExtensivePermissionsName := fmt.Sprintf("%v.extensive_permissions", cmdPrefix)
	if cmd.Flags().Changed(flagExtensivePermissionsName) {
		// warning: extensive_permissions array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveLicenseResponsePropInitialPasswordFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagInitialPasswordName := fmt.Sprintf("%v.initial_password", cmdPrefix)
	if cmd.Flags().Changed(flagInitialPasswordName) {

		var flagInitialPasswordName string
		if cmdPrefix == "" {
			flagInitialPasswordName = "initial_password"
		} else {
			flagInitialPasswordName = fmt.Sprintf("%v.initial_password", cmdPrefix)
		}

		flagInitialPasswordValue, err := cmd.Flags().GetString(flagInitialPasswordName)
		if err != nil {
			return err, false
		}
		m.InitialPassword = &flagInitialPasswordValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveLicenseResponsePropLicenseIDFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagLicenseIDName := fmt.Sprintf("%v.license_id", cmdPrefix)
	if cmd.Flags().Changed(flagLicenseIDName) {

		var flagLicenseIDName string
		if cmdPrefix == "" {
			flagLicenseIDName = "license_id"
		} else {
			flagLicenseIDName = fmt.Sprintf("%v.license_id", cmdPrefix)
		}

		flagLicenseIDValue, err := cmd.Flags().GetString(flagLicenseIDName)
		if err != nil {
			return err, false
		}
		m.LicenseID = &flagLicenseIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveLicenseResponsePropMachineIdsFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagMachineIdsName := fmt.Sprintf("%v.machine_ids", cmdPrefix)
	if cmd.Flags().Changed(flagMachineIdsName) {

		var flagMachineIdsName string
		if cmdPrefix == "" {
			flagMachineIdsName = "machine_ids"
		} else {
			flagMachineIdsName = fmt.Sprintf("%v.machine_ids", cmdPrefix)
		}

		flagMachineIdsValue, err := cmd.Flags().GetString(flagMachineIdsName)
		if err != nil {
			return err, false
		}
		m.MachineIds = flagMachineIdsValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveLicenseResponsePropMaxConcurrentScanFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagMaxConcurrentScanName := fmt.Sprintf("%v.max_concurrent_scan", cmdPrefix)
	if cmd.Flags().Changed(flagMaxConcurrentScanName) {

		var flagMaxConcurrentScanName string
		if cmdPrefix == "" {
			flagMaxConcurrentScanName = "max_concurrent_scan"
		} else {
			flagMaxConcurrentScanName = fmt.Sprintf("%v.max_concurrent_scan", cmdPrefix)
		}

		flagMaxConcurrentScanValue, err := cmd.Flags().GetInt64(flagMaxConcurrentScanName)
		if err != nil {
			return err, false
		}
		m.MaxConcurrentScan = &flagMaxConcurrentScanValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveLicenseResponsePropNotValidAfterFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNotValidAfterName := fmt.Sprintf("%v.not_valid_after", cmdPrefix)
	if cmd.Flags().Changed(flagNotValidAfterName) {

		var flagNotValidAfterName string
		if cmdPrefix == "" {
			flagNotValidAfterName = "not_valid_after"
		} else {
			flagNotValidAfterName = fmt.Sprintf("%v.not_valid_after", cmdPrefix)
		}

		flagNotValidAfterValue, err := cmd.Flags().GetString(flagNotValidAfterName)
		if err != nil {
			return err, false
		}
		m.NotValidAfter = flagNotValidAfterValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveLicenseResponsePropNotValidBeforeFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNotValidBeforeName := fmt.Sprintf("%v.not_valid_before", cmdPrefix)
	if cmd.Flags().Changed(flagNotValidBeforeName) {

		var flagNotValidBeforeName string
		if cmdPrefix == "" {
			flagNotValidBeforeName = "not_valid_before"
		} else {
			flagNotValidBeforeName = fmt.Sprintf("%v.not_valid_before", cmdPrefix)
		}

		flagNotValidBeforeValue, err := cmd.Flags().GetString(flagNotValidBeforeName)
		if err != nil {
			return err, false
		}
		m.NotValidBefore = flagNotValidBeforeValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveLicenseResponsePropPermissionsFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagPermissionsName := fmt.Sprintf("%v.permissions", cmdPrefix)
	if cmd.Flags().Changed(flagPermissionsName) {
		// warning: permissions array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveLicenseResponsePropPlatformVersionsFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagPlatformVersionsName := fmt.Sprintf("%v.platform_versions", cmdPrefix)
	if cmd.Flags().Changed(flagPlatformVersionsName) {
		// warning: platform_versions array type [][]string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveLicenseResponsePropScanEngineNumFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagScanEngineNumName := fmt.Sprintf("%v.scan_engine_num", cmdPrefix)
	if cmd.Flags().Changed(flagScanEngineNumName) {

		var flagScanEngineNumName string
		if cmdPrefix == "" {
			flagScanEngineNumName = "scan_engine_num"
		} else {
			flagScanEngineNumName = fmt.Sprintf("%v.scan_engine_num", cmdPrefix)
		}

		flagScanEngineNumValue, err := cmd.Flags().GetInt64(flagScanEngineNumName)
		if err != nil {
			return err, false
		}
		m.ScanEngineNum = &flagScanEngineNumValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveLicenseResponsePropTemplateFlags(depth int, m *models.LicenseResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagTemplateName := fmt.Sprintf("%v.template", cmdPrefix)
	if cmd.Flags().Changed(flagTemplateName) {
		// warning: template array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
