// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/xray/client/report"
	"github.com/chaitin/workspace-cli/products/xray/models"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationReportPostReportFilterCmd returns a command to handle operation postReportFilter
func makeOperationReportPostReportFilterCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PostReportFilter",
		Short: `按条件批量获取报表`,
		RunE:  runOperationReportPostReportFilter,
	}

	if err := registerOperationReportPostReportFilterParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationReportPostReportFilter uses cmd flags to call endpoint api
func runOperationReportPostReportFilter(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := report.NewPostReportFilterParams()
	if err, _ = retrieveOperationReportPostReportFilterBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationReportPostReportFilterResult(appCli.Report.PostReportFilter(params, nil))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationReportPostReportFilterParamFlags registers all flags needed to fill params
func registerOperationReportPostReportFilterParamFlags(cmd *cobra.Command) error {
	if err := registerOperationReportPostReportFilterBodyParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationReportPostReportFilterBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var flagBodyName string
	if cmdPrefix == "" {
		flagBodyName = "body"
	} else {
		flagBodyName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagBodyName, "", `Optional json string for [body]. `)

	// add flags for body
	if err := registerModelFilterReportFlags(0, "filterReport", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationReportPostReportFilterBodyFlag(m *report.PostReportFilterParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		flagBodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		flagBodyValue := models.FilterReport{}
		if err := json.Unmarshal([]byte(flagBodyValueStr), &flagBodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.FilterReport: %w", err), false
		}
		m.Body = &flagBodyValue
	}
	flagBodyModel := m.Body
	if swag.IsZero(flagBodyModel) {
		flagBodyModel = &models.FilterReport{}
	}
	err, added := retrieveModelFilterReportFlags(0, flagBodyModel, "filterReport", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = flagBodyModel
	}

	if dryRun && debug {
		flagBodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(flagBodyValueDebugBytes))
	}

	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationReportPostReportFilterResult parses request result and return the string content
func parseOperationReportPostReportFilterResult(resp0 *report.PostReportFilterOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		var iResp0 any = respErr
		eresp0, ok := iResp0.(*report.PostReportFilterOK)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp0) && !swag.IsZero(eresp0.Payload) {
				msgStr, err := json.Marshal(eresp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}
	return "", nil
}
