// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
	"github.com/go-openapi/swag"
)

// Schema cli for PostRoleOKBody

// register flags to command
func registerModelPostRoleOKBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	// register embedded APIResponse flags

	if err := registerModelAPIResponseFlags(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPostRoleOKBodyPropData(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerPostRoleOKBodyPropData(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagDataName string
	if cmdPrefix == "" {
		flagDataName = "data"
	} else {
		flagDataName = fmt.Sprintf("%v.data", cmdPrefix)
	}

	if err := registerModelRoleResponseFlags(depth+1, flagDataName, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelPostRoleOKBodyFlags(depth int, m *models.PostRoleOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	// retrieve model APIResponse
	err, AO0Added := retrieveModelAPIResponseFlags(depth, &m.APIResponse, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || AO0Added

	err, DataAdded := retrievePostRoleOKBodyPropDataFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DataAdded

	return nil, retAdded
}

func retrievePostRoleOKBodyPropDataFlags(depth int, m *models.PostRoleOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDataName := fmt.Sprintf("%v.data", cmdPrefix)
	if cmd.Flags().Changed(flagDataName) {
		// info: complex object data RoleResponse is retrieved outside this Changed() block
	}
	flagDataValue := m.Data
	if swag.IsZero(flagDataValue) {
		flagDataValue = &models.RoleResponse{}
	}

	err, DataAdded := retrieveModelRoleResponseFlags(depth+1, flagDataValue, flagDataName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DataAdded
	if DataAdded {
		m.Data = flagDataValue
	}

	return nil, retAdded
}
