// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for PostInsightAssetIPAliveCountParamsBody

// register flags to command
func registerModelPostInsightAssetIPAliveCountParamsBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerPostInsightAssetIPAliveCountParamsBodyPropAssetGroupID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPostInsightAssetIPAliveCountParamsBodyPropEndDate(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPostInsightAssetIPAliveCountParamsBodyPropProjectID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerPostInsightAssetIPAliveCountParamsBodyPropAssetGroupID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagAssetGroupIDDescription := `资产组ID`

	var flagAssetGroupIDName string
	if cmdPrefix == "" {
		flagAssetGroupIDName = "asset_group_id"
	} else {
		flagAssetGroupIDName = fmt.Sprintf("%v.asset_group_id", cmdPrefix)
	}

	var flagAssetGroupIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagAssetGroupIDName, flagAssetGroupIDDefault, flagAssetGroupIDDescription)

	return nil
}

func registerPostInsightAssetIPAliveCountParamsBodyPropEndDate(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagEndDateDescription := `Required. 结束日期`

	var flagEndDateName string
	if cmdPrefix == "" {
		flagEndDateName = "end_date"
	} else {
		flagEndDateName = fmt.Sprintf("%v.end_date", cmdPrefix)
	}

	var flagEndDateDefault string

	_ = cmd.PersistentFlags().String(flagEndDateName, flagEndDateDefault, flagEndDateDescription)

	return nil
}

func registerPostInsightAssetIPAliveCountParamsBodyPropProjectID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagProjectIDDescription := `Required. 项目ID`

	var flagProjectIDName string
	if cmdPrefix == "" {
		flagProjectIDName = "project_id"
	} else {
		flagProjectIDName = fmt.Sprintf("%v.project_id", cmdPrefix)
	}

	var flagProjectIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagProjectIDName, flagProjectIDDefault, flagProjectIDDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelPostInsightAssetIPAliveCountParamsBodyFlags(depth int, m *models.PostInsightAssetIPAliveCountParamsBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, AssetGroupIDAdded := retrievePostInsightAssetIPAliveCountParamsBodyPropAssetGroupIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || AssetGroupIDAdded

	err, EndDateAdded := retrievePostInsightAssetIPAliveCountParamsBodyPropEndDateFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || EndDateAdded

	err, ProjectIDAdded := retrievePostInsightAssetIPAliveCountParamsBodyPropProjectIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ProjectIDAdded

	return nil, retAdded
}

func retrievePostInsightAssetIPAliveCountParamsBodyPropAssetGroupIDFlags(depth int, m *models.PostInsightAssetIPAliveCountParamsBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagAssetGroupIDName := fmt.Sprintf("%v.asset_group_id", cmdPrefix)
	if cmd.Flags().Changed(flagAssetGroupIDName) {

		var flagAssetGroupIDName string
		if cmdPrefix == "" {
			flagAssetGroupIDName = "asset_group_id"
		} else {
			flagAssetGroupIDName = fmt.Sprintf("%v.asset_group_id", cmdPrefix)
		}

		flagAssetGroupIDValue, err := cmd.Flags().GetInt64(flagAssetGroupIDName)
		if err != nil {
			return err, false
		}
		m.AssetGroupID = flagAssetGroupIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrievePostInsightAssetIPAliveCountParamsBodyPropEndDateFlags(depth int, m *models.PostInsightAssetIPAliveCountParamsBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagEndDateName := fmt.Sprintf("%v.end_date", cmdPrefix)
	if cmd.Flags().Changed(flagEndDateName) {

		var flagEndDateName string
		if cmdPrefix == "" {
			flagEndDateName = "end_date"
		} else {
			flagEndDateName = fmt.Sprintf("%v.end_date", cmdPrefix)
		}

		flagEndDateValue, err := cmd.Flags().GetString(flagEndDateName)
		if err != nil {
			return err, false
		}
		m.EndDate = &flagEndDateValue

		retAdded = true
	}

	return nil, retAdded
}

func retrievePostInsightAssetIPAliveCountParamsBodyPropProjectIDFlags(depth int, m *models.PostInsightAssetIPAliveCountParamsBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagProjectIDName := fmt.Sprintf("%v.project_id", cmdPrefix)
	if cmd.Flags().Changed(flagProjectIDName) {

		var flagProjectIDName string
		if cmdPrefix == "" {
			flagProjectIDName = "project_id"
		} else {
			flagProjectIDName = fmt.Sprintf("%v.project_id", cmdPrefix)
		}

		flagProjectIDValue, err := cmd.Flags().GetInt64(flagProjectIDName)
		if err != nil {
			return err, false
		}
		m.ProjectID = &flagProjectIDValue

		retAdded = true
	}

	return nil, retAdded
}
