// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for PostUploadCustompocParamsBody

// register flags to command
func registerModelPostUploadCustompocParamsBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerPostUploadCustompocParamsBodyPropFileList(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerPostUploadCustompocParamsBodyPropFileList(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: file_list []strfmt.UUID array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelPostUploadCustompocParamsBodyFlags(depth int, m *models.PostUploadCustompocParamsBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, FileListAdded := retrievePostUploadCustompocParamsBodyPropFileListFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || FileListAdded

	return nil, retAdded
}

func retrievePostUploadCustompocParamsBodyPropFileListFlags(depth int, m *models.PostUploadCustompocParamsBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagFileListName := fmt.Sprintf("%v.file_list", cmdPrefix)
	if cmd.Flags().Changed(flagFileListName) {
		// warning: file_list array type []strfmt.UUID is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
