// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/xray/client/xprocess_lite"
	"github.com/chaitin/workspace-cli/products/xray/models"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationXprocessLitePostXprocessLiteFilterCmd returns a command to handle operation postXprocessLiteFilter
func makeOperationXprocessLitePostXprocessLiteFilterCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PostXprocessLiteFilter",
		Short: `按条件批量获取 XProcess(精简)`,
		RunE:  runOperationXprocessLitePostXprocessLiteFilter,
	}

	if err := registerOperationXprocessLitePostXprocessLiteFilterParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationXprocessLitePostXprocessLiteFilter uses cmd flags to call endpoint api
func runOperationXprocessLitePostXprocessLiteFilter(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := xprocess_lite.NewPostXprocessLiteFilterParams()
	if err, _ = retrieveOperationXprocessLitePostXprocessLiteFilterBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationXprocessLitePostXprocessLiteFilterResult(appCli.XprocessLite.PostXprocessLiteFilter(params, nil))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationXprocessLitePostXprocessLiteFilterParamFlags registers all flags needed to fill params
func registerOperationXprocessLitePostXprocessLiteFilterParamFlags(cmd *cobra.Command) error {
	if err := registerOperationXprocessLitePostXprocessLiteFilterBodyParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationXprocessLitePostXprocessLiteFilterBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var flagBodyName string
	if cmdPrefix == "" {
		flagBodyName = "body"
	} else {
		flagBodyName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagBodyName, "", `Optional json string for [body]. `)

	// add flags for body
	if err := registerModelFilterXProcessFlags(0, "filterXProcess", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationXprocessLitePostXprocessLiteFilterBodyFlag(m *xprocess_lite.PostXprocessLiteFilterParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		flagBodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		flagBodyValue := models.FilterXProcess{}
		if err := json.Unmarshal([]byte(flagBodyValueStr), &flagBodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.FilterXProcess: %w", err), false
		}
		m.Body = &flagBodyValue
	}
	flagBodyModel := m.Body
	if swag.IsZero(flagBodyModel) {
		flagBodyModel = &models.FilterXProcess{}
	}
	err, added := retrieveModelFilterXProcessFlags(0, flagBodyModel, "filterXProcess", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = flagBodyModel
	}

	if dryRun && debug {
		flagBodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(flagBodyValueDebugBytes))
	}

	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationXprocessLitePostXprocessLiteFilterResult parses request result and return the string content
func parseOperationXprocessLitePostXprocessLiteFilterResult(resp0 *xprocess_lite.PostXprocessLiteFilterOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		var iResp0 any = respErr
		eresp0, ok := iResp0.(*xprocess_lite.PostXprocessLiteFilterOK)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp0) && !swag.IsZero(eresp0.Payload) {
				msgStr, err := json.Marshal(eresp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}
	return "", nil
}
