// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for PostNetworkRegionParamsBody

// register flags to command
func registerModelPostNetworkRegionParamsBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerPostNetworkRegionParamsBodyPropName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPostNetworkRegionParamsBodyPropProjectID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerPostNetworkRegionParamsBodyPropName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagNameDescription := `Required. 网络区域名称`

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "name"
	} else {
		flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

func registerPostNetworkRegionParamsBodyPropProjectID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagProjectIDDescription := `Required. 工作区ID`

	var flagProjectIDName string
	if cmdPrefix == "" {
		flagProjectIDName = "project_id"
	} else {
		flagProjectIDName = fmt.Sprintf("%v.project_id", cmdPrefix)
	}

	var flagProjectIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagProjectIDName, flagProjectIDDefault, flagProjectIDDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelPostNetworkRegionParamsBodyFlags(depth int, m *models.PostNetworkRegionParamsBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, NameAdded := retrievePostNetworkRegionParamsBodyPropNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NameAdded

	err, ProjectIDAdded := retrievePostNetworkRegionParamsBodyPropProjectIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ProjectIDAdded

	return nil, retAdded
}

func retrievePostNetworkRegionParamsBodyPropNameFlags(depth int, m *models.PostNetworkRegionParamsBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNameName := fmt.Sprintf("%v.name", cmdPrefix)
	if cmd.Flags().Changed(flagNameName) {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "name"
		} else {
			flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = &flagNameValue

		retAdded = true
	}

	return nil, retAdded
}

func retrievePostNetworkRegionParamsBodyPropProjectIDFlags(depth int, m *models.PostNetworkRegionParamsBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagProjectIDName := fmt.Sprintf("%v.project_id", cmdPrefix)
	if cmd.Flags().Changed(flagProjectIDName) {

		var flagProjectIDName string
		if cmdPrefix == "" {
			flagProjectIDName = "project_id"
		} else {
			flagProjectIDName = fmt.Sprintf("%v.project_id", cmdPrefix)
		}

		flagProjectIDValue, err := cmd.Flags().GetInt64(flagProjectIDName)
		if err != nil {
			return err, false
		}
		m.ProjectID = &flagProjectIDValue

		retAdded = true
	}

	return nil, retAdded
}
