// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for PostInsightAssetIPScannedCountParamsBody

// register flags to command
func registerModelPostInsightAssetIPScannedCountParamsBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerPostInsightAssetIPScannedCountParamsBodyPropAssetGroupID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPostInsightAssetIPScannedCountParamsBodyPropEndDate(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPostInsightAssetIPScannedCountParamsBodyPropProjectID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPostInsightAssetIPScannedCountParamsBodyPropStartDate(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerPostInsightAssetIPScannedCountParamsBodyPropAssetGroupID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagAssetGroupIDDescription := `资产组ID`

	var flagAssetGroupIDName string
	if cmdPrefix == "" {
		flagAssetGroupIDName = "asset_group_id"
	} else {
		flagAssetGroupIDName = fmt.Sprintf("%v.asset_group_id", cmdPrefix)
	}

	var flagAssetGroupIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagAssetGroupIDName, flagAssetGroupIDDefault, flagAssetGroupIDDescription)

	return nil
}

func registerPostInsightAssetIPScannedCountParamsBodyPropEndDate(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagEndDateDescription := `Required. 结束日期`

	var flagEndDateName string
	if cmdPrefix == "" {
		flagEndDateName = "end_date"
	} else {
		flagEndDateName = fmt.Sprintf("%v.end_date", cmdPrefix)
	}

	var flagEndDateDefault string

	_ = cmd.PersistentFlags().String(flagEndDateName, flagEndDateDefault, flagEndDateDescription)

	return nil
}

func registerPostInsightAssetIPScannedCountParamsBodyPropProjectID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagProjectIDDescription := `Required. 项目ID`

	var flagProjectIDName string
	if cmdPrefix == "" {
		flagProjectIDName = "project_id"
	} else {
		flagProjectIDName = fmt.Sprintf("%v.project_id", cmdPrefix)
	}

	var flagProjectIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagProjectIDName, flagProjectIDDefault, flagProjectIDDescription)

	return nil
}

func registerPostInsightAssetIPScannedCountParamsBodyPropStartDate(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagStartDateDescription := `Required. 开始日期`

	var flagStartDateName string
	if cmdPrefix == "" {
		flagStartDateName = "start_date"
	} else {
		flagStartDateName = fmt.Sprintf("%v.start_date", cmdPrefix)
	}

	var flagStartDateDefault string

	_ = cmd.PersistentFlags().String(flagStartDateName, flagStartDateDefault, flagStartDateDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelPostInsightAssetIPScannedCountParamsBodyFlags(depth int, m *models.PostInsightAssetIPScannedCountParamsBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, AssetGroupIDAdded := retrievePostInsightAssetIPScannedCountParamsBodyPropAssetGroupIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || AssetGroupIDAdded

	err, EndDateAdded := retrievePostInsightAssetIPScannedCountParamsBodyPropEndDateFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || EndDateAdded

	err, ProjectIDAdded := retrievePostInsightAssetIPScannedCountParamsBodyPropProjectIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ProjectIDAdded

	err, StartDateAdded := retrievePostInsightAssetIPScannedCountParamsBodyPropStartDateFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || StartDateAdded

	return nil, retAdded
}

func retrievePostInsightAssetIPScannedCountParamsBodyPropAssetGroupIDFlags(depth int, m *models.PostInsightAssetIPScannedCountParamsBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagAssetGroupIDName := fmt.Sprintf("%v.asset_group_id", cmdPrefix)
	if cmd.Flags().Changed(flagAssetGroupIDName) {

		var flagAssetGroupIDName string
		if cmdPrefix == "" {
			flagAssetGroupIDName = "asset_group_id"
		} else {
			flagAssetGroupIDName = fmt.Sprintf("%v.asset_group_id", cmdPrefix)
		}

		flagAssetGroupIDValue, err := cmd.Flags().GetInt64(flagAssetGroupIDName)
		if err != nil {
			return err, false
		}
		m.AssetGroupID = flagAssetGroupIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrievePostInsightAssetIPScannedCountParamsBodyPropEndDateFlags(depth int, m *models.PostInsightAssetIPScannedCountParamsBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagEndDateName := fmt.Sprintf("%v.end_date", cmdPrefix)
	if cmd.Flags().Changed(flagEndDateName) {

		var flagEndDateName string
		if cmdPrefix == "" {
			flagEndDateName = "end_date"
		} else {
			flagEndDateName = fmt.Sprintf("%v.end_date", cmdPrefix)
		}

		flagEndDateValue, err := cmd.Flags().GetString(flagEndDateName)
		if err != nil {
			return err, false
		}
		m.EndDate = &flagEndDateValue

		retAdded = true
	}

	return nil, retAdded
}

func retrievePostInsightAssetIPScannedCountParamsBodyPropProjectIDFlags(depth int, m *models.PostInsightAssetIPScannedCountParamsBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagProjectIDName := fmt.Sprintf("%v.project_id", cmdPrefix)
	if cmd.Flags().Changed(flagProjectIDName) {

		var flagProjectIDName string
		if cmdPrefix == "" {
			flagProjectIDName = "project_id"
		} else {
			flagProjectIDName = fmt.Sprintf("%v.project_id", cmdPrefix)
		}

		flagProjectIDValue, err := cmd.Flags().GetInt64(flagProjectIDName)
		if err != nil {
			return err, false
		}
		m.ProjectID = &flagProjectIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrievePostInsightAssetIPScannedCountParamsBodyPropStartDateFlags(depth int, m *models.PostInsightAssetIPScannedCountParamsBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagStartDateName := fmt.Sprintf("%v.start_date", cmdPrefix)
	if cmd.Flags().Changed(flagStartDateName) {

		var flagStartDateName string
		if cmdPrefix == "" {
			flagStartDateName = "start_date"
		} else {
			flagStartDateName = fmt.Sprintf("%v.start_date", cmdPrefix)
		}

		flagStartDateValue, err := cmd.Flags().GetString(flagStartDateName)
		if err != nil {
			return err, false
		}
		m.StartDate = &flagStartDateValue

		retAdded = true
	}

	return nil, retAdded
}
