// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for PostInsightVulnAvgFixPeriodOKBody

// register flags to command
func registerModelPostInsightVulnAvgFixPeriodOKBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	// register embedded APIResponse flags

	if err := registerModelAPIResponseFlags(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPostInsightVulnAvgFixPeriodOKBodyPropData(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerPostInsightVulnAvgFixPeriodOKBodyPropData(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagDataDescription := `平均整改周期（天数）`

	var flagDataName string
	if cmdPrefix == "" {
		flagDataName = "data"
	} else {
		flagDataName = fmt.Sprintf("%v.data", cmdPrefix)
	}

	var flagDataDefault float64

	_ = cmd.PersistentFlags().Float64(flagDataName, flagDataDefault, flagDataDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelPostInsightVulnAvgFixPeriodOKBodyFlags(depth int, m *models.PostInsightVulnAvgFixPeriodOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	// retrieve model APIResponse
	err, AO0Added := retrieveModelAPIResponseFlags(depth, &m.APIResponse, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || AO0Added

	err, DataAdded := retrievePostInsightVulnAvgFixPeriodOKBodyPropDataFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DataAdded

	return nil, retAdded
}

func retrievePostInsightVulnAvgFixPeriodOKBodyPropDataFlags(depth int, m *models.PostInsightVulnAvgFixPeriodOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDataName := fmt.Sprintf("%v.data", cmdPrefix)
	if cmd.Flags().Changed(flagDataName) {

		var flagDataName string
		if cmdPrefix == "" {
			flagDataName = "data"
		} else {
			flagDataName = fmt.Sprintf("%v.data", cmdPrefix)
		}

		flagDataValue, err := cmd.Flags().GetFloat64(flagDataName)
		if err != nil {
			return err, false
		}
		m.Data = flagDataValue

		retAdded = true
	}

	return nil, retAdded
}
