// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/xray/client/web_asset"
	"github.com/chaitin/workspace-cli/products/xray/models"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationWebAssetPostWebsiteIDCmd returns a command to handle operation postWebsiteId
func makeOperationWebAssetPostWebsiteIDCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PostWebsiteID",
		Short: `修改 Web 站点`,
		RunE:  runOperationWebAssetPostWebsiteID,
	}

	if err := registerOperationWebAssetPostWebsiteIDParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationWebAssetPostWebsiteID uses cmd flags to call endpoint api
func runOperationWebAssetPostWebsiteID(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := web_asset.NewPostWebsiteIDParams()
	if err, _ = retrieveOperationWebAssetPostWebsiteIDBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationWebAssetPostWebsiteIDIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationWebAssetPostWebsiteIDResult(appCli.WebAsset.PostWebsiteID(params, nil))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationWebAssetPostWebsiteIDParamFlags registers all flags needed to fill params
func registerOperationWebAssetPostWebsiteIDParamFlags(cmd *cobra.Command) error {
	if err := registerOperationWebAssetPostWebsiteIDBodyParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationWebAssetPostWebsiteIDIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationWebAssetPostWebsiteIDBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var flagBodyName string
	if cmdPrefix == "" {
		flagBodyName = "body"
	} else {
		flagBodyName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagBodyName, "", `Optional json string for [body]. `)

	// add flags for body
	if err := registerModelUpdateWebsiteBodyFlags(0, "updateWebsiteBody", cmd); err != nil {
		return err
	}

	return nil
}

func registerOperationWebAssetPostWebsiteIDIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagIDDescription := `Required. 要修改的 website 的 id`

	var flagIDName string
	if cmdPrefix == "" {
		flagIDName = "id"
	} else {
		flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var flagIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagIDName, flagIDDefault, flagIDDescription)

	return nil
}

func retrieveOperationWebAssetPostWebsiteIDBodyFlag(m *web_asset.PostWebsiteIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		flagBodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		flagBodyValue := models.UpdateWebsiteBody{}
		if err := json.Unmarshal([]byte(flagBodyValueStr), &flagBodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.UpdateWebsiteBody: %w", err), false
		}
		m.Body = &flagBodyValue
	}
	flagBodyModel := m.Body
	if swag.IsZero(flagBodyModel) {
		flagBodyModel = &models.UpdateWebsiteBody{}
	}
	err, added := retrieveModelUpdateWebsiteBodyFlags(0, flagBodyModel, "updateWebsiteBody", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = flagBodyModel
	}

	if dryRun && debug {
		flagBodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(flagBodyValueDebugBytes))
	}

	retAdded = retAdded || added

	return nil, retAdded
}

func retrieveOperationWebAssetPostWebsiteIDIDFlag(m *web_asset.PostWebsiteIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var flagIDName string
		if cmdPrefix == "" {
			flagIDName = "id"
		} else {
			flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		flagIDValue, err := cmd.Flags().GetInt64(flagIDName)
		if err != nil {
			return err, false
		}
		m.ID = flagIDValue

	}

	return nil, retAdded
}

// parseOperationWebAssetPostWebsiteIDResult parses request result and return the string content
func parseOperationWebAssetPostWebsiteIDResult(resp0 *web_asset.PostWebsiteIDOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		var iResp0 any = respErr
		eresp0, ok := iResp0.(*web_asset.PostWebsiteIDOK)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp0) && !swag.IsZero(eresp0.Payload) {
				msgStr, err := json.Marshal(eresp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}
	return "", nil
}
