// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for PostReportFilterOKBodyData

// register flags to command
func registerModelPostReportFilterOKBodyDataFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerPostReportFilterOKBodyDataPropCount(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPostReportFilterOKBodyDataPropResult(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerPostReportFilterOKBodyDataPropCount(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCountDescription := `Required. `

	var flagCountName string
	if cmdPrefix == "" {
		flagCountName = "count"
	} else {
		flagCountName = fmt.Sprintf("%v.count", cmdPrefix)
	}

	var flagCountDefault int64

	_ = cmd.PersistentFlags().Int64(flagCountName, flagCountDefault, flagCountDescription)

	return nil
}

func registerPostReportFilterOKBodyDataPropResult(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: result []*ReportResponse array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelPostReportFilterOKBodyDataFlags(depth int, m *models.PostReportFilterOKBodyData, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, CountAdded := retrievePostReportFilterOKBodyDataPropCountFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CountAdded

	err, ResultAdded := retrievePostReportFilterOKBodyDataPropResultFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ResultAdded

	return nil, retAdded
}

func retrievePostReportFilterOKBodyDataPropCountFlags(depth int, m *models.PostReportFilterOKBodyData, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCountName := fmt.Sprintf("%v.count", cmdPrefix)
	if cmd.Flags().Changed(flagCountName) {

		var flagCountName string
		if cmdPrefix == "" {
			flagCountName = "count"
		} else {
			flagCountName = fmt.Sprintf("%v.count", cmdPrefix)
		}

		flagCountValue, err := cmd.Flags().GetInt64(flagCountName)
		if err != nil {
			return err, false
		}
		m.Count = &flagCountValue

		retAdded = true
	}

	return nil, retAdded
}

func retrievePostReportFilterOKBodyDataPropResultFlags(depth int, m *models.PostReportFilterOKBodyData, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagResultName := fmt.Sprintf("%v.result", cmdPrefix)
	if cmd.Flags().Changed(flagResultName) {
		// warning: result array type []*ReportResponse is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
