// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/xray/client/user"
	"github.com/chaitin/workspace-cli/products/xray/models"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationUserPostUserIDCmd returns a command to handle operation postUserId
func makeOperationUserPostUserIDCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PostUserID",
		Short: `修改用户的用户名、角色和项目，但不允许修改 remote_id 和密码。`,
		RunE:  runOperationUserPostUserID,
	}

	if err := registerOperationUserPostUserIDParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationUserPostUserID uses cmd flags to call endpoint api
func runOperationUserPostUserID(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := user.NewPostUserIDParams()
	if err, _ = retrieveOperationUserPostUserIDBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationUserPostUserIDIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationUserPostUserIDResult(appCli.User.PostUserID(params, nil))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationUserPostUserIDParamFlags registers all flags needed to fill params
func registerOperationUserPostUserIDParamFlags(cmd *cobra.Command) error {
	if err := registerOperationUserPostUserIDBodyParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationUserPostUserIDIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationUserPostUserIDBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var flagBodyName string
	if cmdPrefix == "" {
		flagBodyName = "body"
	} else {
		flagBodyName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagBodyName, "", `Optional json string for [body]. `)

	// add flags for body
	if err := registerModelUserUpdateBodyFlags(0, "userUpdateBody", cmd); err != nil {
		return err
	}

	return nil
}

func registerOperationUserPostUserIDIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagIDDescription := `Required. 要修改的用户 ID`

	var flagIDName string
	if cmdPrefix == "" {
		flagIDName = "id"
	} else {
		flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var flagIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagIDName, flagIDDefault, flagIDDescription)

	return nil
}

func retrieveOperationUserPostUserIDBodyFlag(m *user.PostUserIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		flagBodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		flagBodyValue := models.UserUpdateBody{}
		if err := json.Unmarshal([]byte(flagBodyValueStr), &flagBodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.UserUpdateBody: %w", err), false
		}
		m.Body = &flagBodyValue
	}
	flagBodyModel := m.Body
	if swag.IsZero(flagBodyModel) {
		flagBodyModel = &models.UserUpdateBody{}
	}
	err, added := retrieveModelUserUpdateBodyFlags(0, flagBodyModel, "userUpdateBody", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = flagBodyModel
	}

	if dryRun && debug {
		flagBodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(flagBodyValueDebugBytes))
	}

	retAdded = retAdded || added

	return nil, retAdded
}

func retrieveOperationUserPostUserIDIDFlag(m *user.PostUserIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var flagIDName string
		if cmdPrefix == "" {
			flagIDName = "id"
		} else {
			flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		flagIDValue, err := cmd.Flags().GetInt64(flagIDName)
		if err != nil {
			return err, false
		}
		m.ID = flagIDValue

	}

	return nil, retAdded
}

// parseOperationUserPostUserIDResult parses request result and return the string content
func parseOperationUserPostUserIDResult(resp0 *user.PostUserIDOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		var iResp0 any = respErr
		eresp0, ok := iResp0.(*user.PostUserIDOK)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp0) && !swag.IsZero(eresp0.Payload) {
				msgStr, err := json.Marshal(eresp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}
	return "", nil
}
