// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for PostVulnBatchUpdateOKBodyDataUpdatedItems

// register flags to command
func registerModelPostVulnBatchUpdateOKBodyDataUpdatedItemsFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerPostVulnBatchUpdateOKBodyDataUpdatedItemsPropStatus(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPostVulnBatchUpdateOKBodyDataUpdatedItemsPropVulnID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerPostVulnBatchUpdateOKBodyDataUpdatedItemsPropStatus(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagStatusDescription := `修改后的漏洞状态`

	var flagStatusName string
	if cmdPrefix == "" {
		flagStatusName = "status"
	} else {
		flagStatusName = fmt.Sprintf("%v.status", cmdPrefix)
	}

	var flagStatusDefault string

	_ = cmd.PersistentFlags().String(flagStatusName, flagStatusDefault, flagStatusDescription)

	return nil
}

func registerPostVulnBatchUpdateOKBodyDataUpdatedItemsPropVulnID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagVulnIDDescription := ``

	var flagVulnIDName string
	if cmdPrefix == "" {
		flagVulnIDName = "vuln_id"
	} else {
		flagVulnIDName = fmt.Sprintf("%v.vuln_id", cmdPrefix)
	}

	var flagVulnIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagVulnIDName, flagVulnIDDefault, flagVulnIDDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelPostVulnBatchUpdateOKBodyDataUpdatedItemsFlags(depth int, m *models.PostVulnBatchUpdateOKBodyDataUpdatedItems, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, StatusAdded := retrievePostVulnBatchUpdateOKBodyDataUpdatedItemsPropStatusFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || StatusAdded

	err, VulnIDAdded := retrievePostVulnBatchUpdateOKBodyDataUpdatedItemsPropVulnIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || VulnIDAdded

	return nil, retAdded
}

func retrievePostVulnBatchUpdateOKBodyDataUpdatedItemsPropStatusFlags(depth int, m *models.PostVulnBatchUpdateOKBodyDataUpdatedItems, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagStatusName := fmt.Sprintf("%v.status", cmdPrefix)
	if cmd.Flags().Changed(flagStatusName) {

		var flagStatusName string
		if cmdPrefix == "" {
			flagStatusName = "status"
		} else {
			flagStatusName = fmt.Sprintf("%v.status", cmdPrefix)
		}

		flagStatusValue, err := cmd.Flags().GetString(flagStatusName)
		if err != nil {
			return err, false
		}
		m.Status = flagStatusValue

		retAdded = true
	}

	return nil, retAdded
}

func retrievePostVulnBatchUpdateOKBodyDataUpdatedItemsPropVulnIDFlags(depth int, m *models.PostVulnBatchUpdateOKBodyDataUpdatedItems, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagVulnIDName := fmt.Sprintf("%v.vuln_id", cmdPrefix)
	if cmd.Flags().Changed(flagVulnIDName) {

		var flagVulnIDName string
		if cmdPrefix == "" {
			flagVulnIDName = "vuln_id"
		} else {
			flagVulnIDName = fmt.Sprintf("%v.vuln_id", cmdPrefix)
		}

		flagVulnIDValue, err := cmd.Flags().GetInt64(flagVulnIDName)
		if err != nil {
			return err, false
		}
		m.VulnID = flagVulnIDValue

		retAdded = true
	}

	return nil, retAdded
}
