// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for ProjectWithParentIDResponse

// register flags to command
func registerModelProjectWithParentIDResponseFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerProjectWithParentIDResponsePropFullName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerProjectWithParentIDResponsePropID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerProjectWithParentIDResponsePropName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerProjectWithParentIDResponsePropParentID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerProjectWithParentIDResponsePropFullName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagFullNameDescription := `Required. `

	var flagFullNameName string
	if cmdPrefix == "" {
		flagFullNameName = "full_name"
	} else {
		flagFullNameName = fmt.Sprintf("%v.full_name", cmdPrefix)
	}

	var flagFullNameDefault string

	_ = cmd.PersistentFlags().String(flagFullNameName, flagFullNameDefault, flagFullNameDescription)

	return nil
}

func registerProjectWithParentIDResponsePropID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagIDDescription := `Required. `

	var flagIDName string
	if cmdPrefix == "" {
		flagIDName = "id"
	} else {
		flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var flagIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagIDName, flagIDDefault, flagIDDescription)

	return nil
}

func registerProjectWithParentIDResponsePropName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagNameDescription := `Required. `

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "name"
	} else {
		flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

func registerProjectWithParentIDResponsePropParentID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagParentIDDescription := `Required. `

	var flagParentIDName string
	if cmdPrefix == "" {
		flagParentIDName = "parent_id"
	} else {
		flagParentIDName = fmt.Sprintf("%v.parent_id", cmdPrefix)
	}

	var flagParentIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagParentIDName, flagParentIDDefault, flagParentIDDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelProjectWithParentIDResponseFlags(depth int, m *models.ProjectWithParentIDResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, FullNameAdded := retrieveProjectWithParentIDResponsePropFullNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || FullNameAdded

	err, IDAdded := retrieveProjectWithParentIDResponsePropIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IDAdded

	err, NameAdded := retrieveProjectWithParentIDResponsePropNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NameAdded

	err, ParentIDAdded := retrieveProjectWithParentIDResponsePropParentIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ParentIDAdded

	return nil, retAdded
}

func retrieveProjectWithParentIDResponsePropFullNameFlags(depth int, m *models.ProjectWithParentIDResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagFullNameName := fmt.Sprintf("%v.full_name", cmdPrefix)
	if cmd.Flags().Changed(flagFullNameName) {

		var flagFullNameName string
		if cmdPrefix == "" {
			flagFullNameName = "full_name"
		} else {
			flagFullNameName = fmt.Sprintf("%v.full_name", cmdPrefix)
		}

		flagFullNameValue, err := cmd.Flags().GetString(flagFullNameName)
		if err != nil {
			return err, false
		}
		m.FullName = &flagFullNameValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveProjectWithParentIDResponsePropIDFlags(depth int, m *models.ProjectWithParentIDResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagIDName := fmt.Sprintf("%v.id", cmdPrefix)
	if cmd.Flags().Changed(flagIDName) {

		var flagIDName string
		if cmdPrefix == "" {
			flagIDName = "id"
		} else {
			flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		flagIDValue, err := cmd.Flags().GetInt64(flagIDName)
		if err != nil {
			return err, false
		}
		m.ID = &flagIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveProjectWithParentIDResponsePropNameFlags(depth int, m *models.ProjectWithParentIDResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNameName := fmt.Sprintf("%v.name", cmdPrefix)
	if cmd.Flags().Changed(flagNameName) {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "name"
		} else {
			flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = &flagNameValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveProjectWithParentIDResponsePropParentIDFlags(depth int, m *models.ProjectWithParentIDResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagParentIDName := fmt.Sprintf("%v.parent_id", cmdPrefix)
	if cmd.Flags().Changed(flagParentIDName) {

		var flagParentIDName string
		if cmdPrefix == "" {
			flagParentIDName = "parent_id"
		} else {
			flagParentIDName = fmt.Sprintf("%v.parent_id", cmdPrefix)
		}

		flagParentIDValue, err := cmd.Flags().GetInt64(flagParentIDName)
		if err != nil {
			return err, false
		}
		m.ParentID = &flagParentIDValue

		retAdded = true
	}

	return nil, retAdded
}
