// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for ReportTemplateResponseProject

// register flags to command
func registerModelReportTemplateResponseProjectFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerReportTemplateResponseProjectPropProjectID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerReportTemplateResponseProjectPropProjectName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerReportTemplateResponseProjectPropProjectID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagProjectIDDescription := `Required. `

	var flagProjectIDName string
	if cmdPrefix == "" {
		flagProjectIDName = "project_id"
	} else {
		flagProjectIDName = fmt.Sprintf("%v.project_id", cmdPrefix)
	}

	var flagProjectIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagProjectIDName, flagProjectIDDefault, flagProjectIDDescription)

	return nil
}

func registerReportTemplateResponseProjectPropProjectName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagProjectNameDescription := `Required. `

	var flagProjectNameName string
	if cmdPrefix == "" {
		flagProjectNameName = "project_name"
	} else {
		flagProjectNameName = fmt.Sprintf("%v.project_name", cmdPrefix)
	}

	var flagProjectNameDefault string

	_ = cmd.PersistentFlags().String(flagProjectNameName, flagProjectNameDefault, flagProjectNameDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelReportTemplateResponseProjectFlags(depth int, m *models.ReportTemplateResponseProject, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, ProjectIDAdded := retrieveReportTemplateResponseProjectPropProjectIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ProjectIDAdded

	err, ProjectNameAdded := retrieveReportTemplateResponseProjectPropProjectNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ProjectNameAdded

	return nil, retAdded
}

func retrieveReportTemplateResponseProjectPropProjectIDFlags(depth int, m *models.ReportTemplateResponseProject, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagProjectIDName := fmt.Sprintf("%v.project_id", cmdPrefix)
	if cmd.Flags().Changed(flagProjectIDName) {

		var flagProjectIDName string
		if cmdPrefix == "" {
			flagProjectIDName = "project_id"
		} else {
			flagProjectIDName = fmt.Sprintf("%v.project_id", cmdPrefix)
		}

		flagProjectIDValue, err := cmd.Flags().GetInt64(flagProjectIDName)
		if err != nil {
			return err, false
		}
		m.ProjectID = &flagProjectIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveReportTemplateResponseProjectPropProjectNameFlags(depth int, m *models.ReportTemplateResponseProject, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagProjectNameName := fmt.Sprintf("%v.project_name", cmdPrefix)
	if cmd.Flags().Changed(flagProjectNameName) {

		var flagProjectNameName string
		if cmdPrefix == "" {
			flagProjectNameName = "project_name"
		} else {
			flagProjectNameName = fmt.Sprintf("%v.project_name", cmdPrefix)
		}

		flagProjectNameValue, err := cmd.Flags().GetString(flagProjectNameName)
		if err != nil {
			return err, false
		}
		m.ProjectName = &flagProjectNameValue

		retAdded = true
	}

	return nil, retAdded
}
