// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for ScannerDictDictType

// register flags to command
func registerModelScannerDictDictTypeFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	// register embedded ScannerDictTypeEnum flags

	if err := registerModelScannerDictTypeEnumFlags(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelScannerDictDictTypeFlags(depth int, m *models.ScannerDictDictType, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	// retrieve model ScannerDictTypeEnum
	err, AO0Added := retrieveModelScannerDictTypeEnumFlags(depth, &m.ScannerDictTypeEnum, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || AO0Added

	return nil, retAdded
}
