// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// Schema cli for TargetTypeEnum

// register flags to command
func registerModelTargetTypeEnumFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelTargetTypeEnumFlags(depth int, m *models.TargetTypeEnum, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	return nil, retAdded
}
