// Code generated by go-swagger; DO NOT EDIT.

package report

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteReportIDParams creates a new DeleteReportIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteReportIDParams() *DeleteReportIDParams {
	return &DeleteReportIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteReportIDParamsWithTimeout creates a new DeleteReportIDParams object
// with the ability to set a timeout on a request.
func NewDeleteReportIDParamsWithTimeout(timeout time.Duration) *DeleteReportIDParams {
	return &DeleteReportIDParams{
		timeout: timeout,
	}
}

// NewDeleteReportIDParamsWithContext creates a new DeleteReportIDParams object
// with the ability to set a context for a request.
func NewDeleteReportIDParamsWithContext(ctx context.Context) *DeleteReportIDParams {
	return &DeleteReportIDParams{
		Context: ctx,
	}
}

// NewDeleteReportIDParamsWithHTTPClient creates a new DeleteReportIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteReportIDParamsWithHTTPClient(client *http.Client) *DeleteReportIDParams {
	return &DeleteReportIDParams{
		HTTPClient: client,
	}
}

/*
DeleteReportIDParams contains all the parameters to send to the API endpoint

	for the delete report ID operation.

	Typically these are written to a http.Request.
*/
type DeleteReportIDParams struct {

	/* ID.

	   要删除的报表的 id
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete report ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteReportIDParams) WithDefaults() *DeleteReportIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete report ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteReportIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete report ID params
func (o *DeleteReportIDParams) WithTimeout(timeout time.Duration) *DeleteReportIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete report ID params
func (o *DeleteReportIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete report ID params
func (o *DeleteReportIDParams) WithContext(ctx context.Context) *DeleteReportIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete report ID params
func (o *DeleteReportIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete report ID params
func (o *DeleteReportIDParams) WithHTTPClient(client *http.Client) *DeleteReportIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete report ID params
func (o *DeleteReportIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete report ID params
func (o *DeleteReportIDParams) WithID(id int64) *DeleteReportIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete report ID params
func (o *DeleteReportIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteReportIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
