// Code generated by go-swagger; DO NOT EDIT.

package report

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// NewPostReportTemplateFilterParams creates a new PostReportTemplateFilterParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostReportTemplateFilterParams() *PostReportTemplateFilterParams {
	return &PostReportTemplateFilterParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostReportTemplateFilterParamsWithTimeout creates a new PostReportTemplateFilterParams object
// with the ability to set a timeout on a request.
func NewPostReportTemplateFilterParamsWithTimeout(timeout time.Duration) *PostReportTemplateFilterParams {
	return &PostReportTemplateFilterParams{
		timeout: timeout,
	}
}

// NewPostReportTemplateFilterParamsWithContext creates a new PostReportTemplateFilterParams object
// with the ability to set a context for a request.
func NewPostReportTemplateFilterParamsWithContext(ctx context.Context) *PostReportTemplateFilterParams {
	return &PostReportTemplateFilterParams{
		Context: ctx,
	}
}

// NewPostReportTemplateFilterParamsWithHTTPClient creates a new PostReportTemplateFilterParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostReportTemplateFilterParamsWithHTTPClient(client *http.Client) *PostReportTemplateFilterParams {
	return &PostReportTemplateFilterParams{
		HTTPClient: client,
	}
}

/*
PostReportTemplateFilterParams contains all the parameters to send to the API endpoint

	for the post report template filter operation.

	Typically these are written to a http.Request.
*/
type PostReportTemplateFilterParams struct {

	// Body.
	Body *models.FilterReportTemplate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post report template filter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostReportTemplateFilterParams) WithDefaults() *PostReportTemplateFilterParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post report template filter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostReportTemplateFilterParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post report template filter params
func (o *PostReportTemplateFilterParams) WithTimeout(timeout time.Duration) *PostReportTemplateFilterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post report template filter params
func (o *PostReportTemplateFilterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post report template filter params
func (o *PostReportTemplateFilterParams) WithContext(ctx context.Context) *PostReportTemplateFilterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post report template filter params
func (o *PostReportTemplateFilterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post report template filter params
func (o *PostReportTemplateFilterParams) WithHTTPClient(client *http.Client) *PostReportTemplateFilterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post report template filter params
func (o *PostReportTemplateFilterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post report template filter params
func (o *PostReportTemplateFilterParams) WithBody(body *models.FilterReportTemplate) *PostReportTemplateFilterParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post report template filter params
func (o *PostReportTemplateFilterParams) SetBody(body *models.FilterReportTemplate) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostReportTemplateFilterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
