// Code generated by go-swagger; DO NOT EDIT.

package report

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// NewPostReportDownloadParams creates a new PostReportDownloadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostReportDownloadParams() *PostReportDownloadParams {
	return &PostReportDownloadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostReportDownloadParamsWithTimeout creates a new PostReportDownloadParams object
// with the ability to set a timeout on a request.
func NewPostReportDownloadParamsWithTimeout(timeout time.Duration) *PostReportDownloadParams {
	return &PostReportDownloadParams{
		timeout: timeout,
	}
}

// NewPostReportDownloadParamsWithContext creates a new PostReportDownloadParams object
// with the ability to set a context for a request.
func NewPostReportDownloadParamsWithContext(ctx context.Context) *PostReportDownloadParams {
	return &PostReportDownloadParams{
		Context: ctx,
	}
}

// NewPostReportDownloadParamsWithHTTPClient creates a new PostReportDownloadParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostReportDownloadParamsWithHTTPClient(client *http.Client) *PostReportDownloadParams {
	return &PostReportDownloadParams{
		HTTPClient: client,
	}
}

/*
PostReportDownloadParams contains all the parameters to send to the API endpoint

	for the post report download operation.

	Typically these are written to a http.Request.
*/
type PostReportDownloadParams struct {

	// Body.
	Body *models.PostReportDownloadParamsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post report download params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostReportDownloadParams) WithDefaults() *PostReportDownloadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post report download params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostReportDownloadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post report download params
func (o *PostReportDownloadParams) WithTimeout(timeout time.Duration) *PostReportDownloadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post report download params
func (o *PostReportDownloadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post report download params
func (o *PostReportDownloadParams) WithContext(ctx context.Context) *PostReportDownloadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post report download params
func (o *PostReportDownloadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post report download params
func (o *PostReportDownloadParams) WithHTTPClient(client *http.Client) *PostReportDownloadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post report download params
func (o *PostReportDownloadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post report download params
func (o *PostReportDownloadParams) WithBody(body *models.PostReportDownloadParamsBody) *PostReportDownloadParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post report download params
func (o *PostReportDownloadParams) SetBody(body *models.PostReportDownloadParamsBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostReportDownloadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
