// Code generated by go-swagger; DO NOT EDIT.

package system_info

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSystemInfoServicesParams creates a new GetSystemInfoServicesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSystemInfoServicesParams() *GetSystemInfoServicesParams {
	return &GetSystemInfoServicesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSystemInfoServicesParamsWithTimeout creates a new GetSystemInfoServicesParams object
// with the ability to set a timeout on a request.
func NewGetSystemInfoServicesParamsWithTimeout(timeout time.Duration) *GetSystemInfoServicesParams {
	return &GetSystemInfoServicesParams{
		timeout: timeout,
	}
}

// NewGetSystemInfoServicesParamsWithContext creates a new GetSystemInfoServicesParams object
// with the ability to set a context for a request.
func NewGetSystemInfoServicesParamsWithContext(ctx context.Context) *GetSystemInfoServicesParams {
	return &GetSystemInfoServicesParams{
		Context: ctx,
	}
}

// NewGetSystemInfoServicesParamsWithHTTPClient creates a new GetSystemInfoServicesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSystemInfoServicesParamsWithHTTPClient(client *http.Client) *GetSystemInfoServicesParams {
	return &GetSystemInfoServicesParams{
		HTTPClient: client,
	}
}

/*
GetSystemInfoServicesParams contains all the parameters to send to the API endpoint

	for the get system info services operation.

	Typically these are written to a http.Request.
*/
type GetSystemInfoServicesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get system info services params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSystemInfoServicesParams) WithDefaults() *GetSystemInfoServicesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get system info services params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSystemInfoServicesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get system info services params
func (o *GetSystemInfoServicesParams) WithTimeout(timeout time.Duration) *GetSystemInfoServicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get system info services params
func (o *GetSystemInfoServicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get system info services params
func (o *GetSystemInfoServicesParams) WithContext(ctx context.Context) *GetSystemInfoServicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get system info services params
func (o *GetSystemInfoServicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get system info services params
func (o *GetSystemInfoServicesParams) WithHTTPClient(client *http.Client) *GetSystemInfoServicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get system info services params
func (o *GetSystemInfoServicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSystemInfoServicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
