// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CookieType cookie type
//
// swagger:model CookieType
type CookieType struct {

	// 是否允许覆写
	// Required: true
	AllowOverride *bool `json:"allow_override"`

	// 名称
	// Required: true
	Key *string `json:"key"`

	// 值
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this cookie type
func (m *CookieType) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAllowOverride(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CookieType) validateAllowOverride(formats strfmt.Registry) error {

	if err := validate.Required("allow_override", "body", m.AllowOverride); err != nil {
		return err
	}

	return nil
}

func (m *CookieType) validateKey(formats strfmt.Registry) error {

	if err := validate.Required("key", "body", m.Key); err != nil {
		return err
	}

	return nil
}

func (m *CookieType) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this cookie type based on context it is used
func (m *CookieType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CookieType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CookieType) UnmarshalBinary(b []byte) error {
	var res CookieType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
