// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeleteCustompocParamsBody 删除自定义poc
//
// swagger:model deleteCustompocParamsBody
type DeleteCustompocParamsBody struct {

	// custom poc id list
	// Required: true
	CustomPocIDList []strfmt.UUID `json:"custom_poc_id_list"`
}

// Validate validates this delete custompoc params body
func (m *DeleteCustompocParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCustomPocIDList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeleteCustompocParamsBody) validateCustomPocIDList(formats strfmt.Registry) error {

	if err := validate.Required("custom_poc_id_list", "body", m.CustomPocIDList); err != nil {
		return err
	}

	for i := 0; i < len(m.CustomPocIDList); i++ {

		if err := validate.FormatOf("custom_poc_id_list"+"."+strconv.Itoa(i), "body", "uuid", m.CustomPocIDList[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this delete custompoc params body based on context it is used
func (m *DeleteCustompocParamsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteCustompocParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteCustompocParamsBody) UnmarshalBinary(b []byte) error {
	var res DeleteCustompocParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
