// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EngineSystemInfo engine system info
//
// swagger:model EngineSystemInfo
type EngineSystemInfo struct {
	Engine

	// 引擎基础镜像版本
	BaseImageVersion string `json:"base_image_version,omitempty"`

	// cpu 占用率
	// Required: true
	CPUUsageRate *FloatWithDate `json:"cpu_usage_rate"`

	// disk io
	// Required: true
	DiskIo *EngineSystemInfoDiskIo `json:"disk_io"`

	// 硬盘总大小,MB
	DiskTatal float64 `json:"disk_tatal,omitempty"`

	// 硬盘总大小,MB
	// Required: true
	DiskTotal *float64 `json:"disk_total"`

	// 硬盘已使用,MB
	// Required: true
	DiskUsage *float64 `json:"disk_usage"`

	// 内存总量: MB
	// Required: true
	MemTotal *float64 `json:"mem_total"`

	// 内存占用, MB
	// Required: true
	MemUsage *FloatWithDate `json:"mem_usage"`

	// net io
	// Required: true
	NetIo *EngineSystemInfoNetIo `json:"net_io"`

	// 在线状态
	// Required: true
	// Enum: ["ONLINE","OFFLINE"]
	OnlineStatus *string `json:"online_status"`

	// 状态
	// Required: true
	// Enum: ["WORKING","FREE","UPDATING","ERROR"]
	Status *string `json:"status"`

	// 运行时长，秒
	// Required: true
	Uptime *float64 `json:"uptime"`

	// 引擎版本
	Version string `json:"version,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *EngineSystemInfo) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Engine
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Engine = aO0

	// now for regular properties
	var propsEngineSystemInfo struct {
		BaseImageVersion string `json:"base_image_version,omitempty"`

		CPUUsageRate *FloatWithDate `json:"cpu_usage_rate"`

		DiskIo *EngineSystemInfoDiskIo `json:"disk_io"`

		DiskTatal float64 `json:"disk_tatal,omitempty"`

		DiskTotal *float64 `json:"disk_total"`

		DiskUsage *float64 `json:"disk_usage"`

		MemTotal *float64 `json:"mem_total"`

		MemUsage *FloatWithDate `json:"mem_usage"`

		NetIo *EngineSystemInfoNetIo `json:"net_io"`

		OnlineStatus *string `json:"online_status"`

		Status *string `json:"status"`

		Uptime *float64 `json:"uptime"`

		Version string `json:"version,omitempty"`
	}
	if err := swag.ReadJSON(raw, &propsEngineSystemInfo); err != nil {
		return err
	}
	m.BaseImageVersion = propsEngineSystemInfo.BaseImageVersion

	m.CPUUsageRate = propsEngineSystemInfo.CPUUsageRate

	m.DiskIo = propsEngineSystemInfo.DiskIo

	m.DiskTatal = propsEngineSystemInfo.DiskTatal

	m.DiskTotal = propsEngineSystemInfo.DiskTotal

	m.DiskUsage = propsEngineSystemInfo.DiskUsage

	m.MemTotal = propsEngineSystemInfo.MemTotal

	m.MemUsage = propsEngineSystemInfo.MemUsage

	m.NetIo = propsEngineSystemInfo.NetIo

	m.OnlineStatus = propsEngineSystemInfo.OnlineStatus

	m.Status = propsEngineSystemInfo.Status

	m.Uptime = propsEngineSystemInfo.Uptime

	m.Version = propsEngineSystemInfo.Version

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m EngineSystemInfo) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.Engine)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	// now for regular properties
	var propsEngineSystemInfo struct {
		BaseImageVersion string `json:"base_image_version,omitempty"`

		CPUUsageRate *FloatWithDate `json:"cpu_usage_rate"`

		DiskIo *EngineSystemInfoDiskIo `json:"disk_io"`

		DiskTatal float64 `json:"disk_tatal,omitempty"`

		DiskTotal *float64 `json:"disk_total"`

		DiskUsage *float64 `json:"disk_usage"`

		MemTotal *float64 `json:"mem_total"`

		MemUsage *FloatWithDate `json:"mem_usage"`

		NetIo *EngineSystemInfoNetIo `json:"net_io"`

		OnlineStatus *string `json:"online_status"`

		Status *string `json:"status"`

		Uptime *float64 `json:"uptime"`

		Version string `json:"version,omitempty"`
	}
	propsEngineSystemInfo.BaseImageVersion = m.BaseImageVersion

	propsEngineSystemInfo.CPUUsageRate = m.CPUUsageRate

	propsEngineSystemInfo.DiskIo = m.DiskIo

	propsEngineSystemInfo.DiskTatal = m.DiskTatal

	propsEngineSystemInfo.DiskTotal = m.DiskTotal

	propsEngineSystemInfo.DiskUsage = m.DiskUsage

	propsEngineSystemInfo.MemTotal = m.MemTotal

	propsEngineSystemInfo.MemUsage = m.MemUsage

	propsEngineSystemInfo.NetIo = m.NetIo

	propsEngineSystemInfo.OnlineStatus = m.OnlineStatus

	propsEngineSystemInfo.Status = m.Status

	propsEngineSystemInfo.Uptime = m.Uptime

	propsEngineSystemInfo.Version = m.Version

	jsonDataPropsEngineSystemInfo, errEngineSystemInfo := swag.WriteJSON(propsEngineSystemInfo)
	if errEngineSystemInfo != nil {
		return nil, errEngineSystemInfo
	}
	_parts = append(_parts, jsonDataPropsEngineSystemInfo)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this engine system info
func (m *EngineSystemInfo) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Engine
	if err := m.Engine.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCPUUsageRate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDiskIo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDiskTotal(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDiskUsage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMemTotal(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMemUsage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetIo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOnlineStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUptime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EngineSystemInfo) validateCPUUsageRate(formats strfmt.Registry) error {

	if err := validate.Required("cpu_usage_rate", "body", m.CPUUsageRate); err != nil {
		return err
	}

	if m.CPUUsageRate != nil {
		if err := m.CPUUsageRate.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cpu_usage_rate")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cpu_usage_rate")
			}

			return err
		}
	}

	return nil
}

func (m *EngineSystemInfo) validateDiskIo(formats strfmt.Registry) error {

	if err := validate.Required("disk_io", "body", m.DiskIo); err != nil {
		return err
	}

	if m.DiskIo != nil {
		if err := m.DiskIo.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("disk_io")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("disk_io")
			}

			return err
		}
	}

	return nil
}

func (m *EngineSystemInfo) validateDiskTotal(formats strfmt.Registry) error {

	if err := validate.Required("disk_total", "body", m.DiskTotal); err != nil {
		return err
	}

	return nil
}

func (m *EngineSystemInfo) validateDiskUsage(formats strfmt.Registry) error {

	if err := validate.Required("disk_usage", "body", m.DiskUsage); err != nil {
		return err
	}

	return nil
}

func (m *EngineSystemInfo) validateMemTotal(formats strfmt.Registry) error {

	if err := validate.Required("mem_total", "body", m.MemTotal); err != nil {
		return err
	}

	return nil
}

func (m *EngineSystemInfo) validateMemUsage(formats strfmt.Registry) error {

	if err := validate.Required("mem_usage", "body", m.MemUsage); err != nil {
		return err
	}

	if m.MemUsage != nil {
		if err := m.MemUsage.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("mem_usage")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("mem_usage")
			}

			return err
		}
	}

	return nil
}

func (m *EngineSystemInfo) validateNetIo(formats strfmt.Registry) error {

	if err := validate.Required("net_io", "body", m.NetIo); err != nil {
		return err
	}

	if m.NetIo != nil {
		if err := m.NetIo.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("net_io")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("net_io")
			}

			return err
		}
	}

	return nil
}

var engineSystemInfoTypeOnlineStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ONLINE","OFFLINE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		engineSystemInfoTypeOnlineStatusPropEnum = append(engineSystemInfoTypeOnlineStatusPropEnum, v)
	}
}

const (

	// EngineSystemInfoOnlineStatusONLINE captures enum value "ONLINE"
	EngineSystemInfoOnlineStatusONLINE string = "ONLINE"

	// EngineSystemInfoOnlineStatusOFFLINE captures enum value "OFFLINE"
	EngineSystemInfoOnlineStatusOFFLINE string = "OFFLINE"
)

// prop value enum
func (m *EngineSystemInfo) validateOnlineStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, engineSystemInfoTypeOnlineStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *EngineSystemInfo) validateOnlineStatus(formats strfmt.Registry) error {

	if err := validate.Required("online_status", "body", m.OnlineStatus); err != nil {
		return err
	}

	// value enum
	if err := m.validateOnlineStatusEnum("online_status", "body", *m.OnlineStatus); err != nil {
		return err
	}

	return nil
}

var engineSystemInfoTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["WORKING","FREE","UPDATING","ERROR"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		engineSystemInfoTypeStatusPropEnum = append(engineSystemInfoTypeStatusPropEnum, v)
	}
}

const (

	// EngineSystemInfoStatusWORKING captures enum value "WORKING"
	EngineSystemInfoStatusWORKING string = "WORKING"

	// EngineSystemInfoStatusFREE captures enum value "FREE"
	EngineSystemInfoStatusFREE string = "FREE"

	// EngineSystemInfoStatusUPDATING captures enum value "UPDATING"
	EngineSystemInfoStatusUPDATING string = "UPDATING"

	// EngineSystemInfoStatusERROR captures enum value "ERROR"
	EngineSystemInfoStatusERROR string = "ERROR"
)

// prop value enum
func (m *EngineSystemInfo) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, engineSystemInfoTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *EngineSystemInfo) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

func (m *EngineSystemInfo) validateUptime(formats strfmt.Registry) error {

	if err := validate.Required("uptime", "body", m.Uptime); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this engine system info based on the context it is used
func (m *EngineSystemInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Engine
	if err := m.Engine.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCPUUsageRate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDiskIo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMemUsage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNetIo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EngineSystemInfo) contextValidateCPUUsageRate(ctx context.Context, formats strfmt.Registry) error {

	if m.CPUUsageRate != nil {

		if err := m.CPUUsageRate.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cpu_usage_rate")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cpu_usage_rate")
			}

			return err
		}
	}

	return nil
}

func (m *EngineSystemInfo) contextValidateDiskIo(ctx context.Context, formats strfmt.Registry) error {

	if m.DiskIo != nil {

		if err := m.DiskIo.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("disk_io")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("disk_io")
			}

			return err
		}
	}

	return nil
}

func (m *EngineSystemInfo) contextValidateMemUsage(ctx context.Context, formats strfmt.Registry) error {

	if m.MemUsage != nil {

		if err := m.MemUsage.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("mem_usage")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("mem_usage")
			}

			return err
		}
	}

	return nil
}

func (m *EngineSystemInfo) contextValidateNetIo(ctx context.Context, formats strfmt.Registry) error {

	if m.NetIo != nil {

		if err := m.NetIo.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("net_io")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("net_io")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EngineSystemInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EngineSystemInfo) UnmarshalBinary(b []byte) error {
	var res EngineSystemInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
