// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FilterXProcess filter x process
//
// swagger:model FilterXProcess
type FilterXProcess struct {
	LimitAndOffsetFilter

	// created time
	CreatedTime *TimeFilterType `json:"created_time,omitempty"`

	// plan id
	PlanID int64 `json:"plan_id,omitempty"`

	// 对应的工作区的 ID
	ProjectID int64 `json:"project_id,omitempty"`

	// remark
	Remark []*PartialInputType `json:"remark"`

	// status
	Status XProcessStatusEnum `json:"status,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *FilterXProcess) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 LimitAndOffsetFilter
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.LimitAndOffsetFilter = aO0

	// now for regular properties
	var propsFilterXProcess struct {
		CreatedTime *TimeFilterType `json:"created_time,omitempty"`

		PlanID int64 `json:"plan_id,omitempty"`

		ProjectID int64 `json:"project_id,omitempty"`

		Remark []*PartialInputType `json:"remark"`

		Status XProcessStatusEnum `json:"status,omitempty"`
	}
	if err := swag.ReadJSON(raw, &propsFilterXProcess); err != nil {
		return err
	}
	m.CreatedTime = propsFilterXProcess.CreatedTime

	m.PlanID = propsFilterXProcess.PlanID

	m.ProjectID = propsFilterXProcess.ProjectID

	m.Remark = propsFilterXProcess.Remark

	m.Status = propsFilterXProcess.Status

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m FilterXProcess) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.LimitAndOffsetFilter)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	// now for regular properties
	var propsFilterXProcess struct {
		CreatedTime *TimeFilterType `json:"created_time,omitempty"`

		PlanID int64 `json:"plan_id,omitempty"`

		ProjectID int64 `json:"project_id,omitempty"`

		Remark []*PartialInputType `json:"remark"`

		Status XProcessStatusEnum `json:"status,omitempty"`
	}
	propsFilterXProcess.CreatedTime = m.CreatedTime

	propsFilterXProcess.PlanID = m.PlanID

	propsFilterXProcess.ProjectID = m.ProjectID

	propsFilterXProcess.Remark = m.Remark

	propsFilterXProcess.Status = m.Status

	jsonDataPropsFilterXProcess, errFilterXProcess := swag.WriteJSON(propsFilterXProcess)
	if errFilterXProcess != nil {
		return nil, errFilterXProcess
	}
	_parts = append(_parts, jsonDataPropsFilterXProcess)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this filter x process
func (m *FilterXProcess) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with LimitAndOffsetFilter
	if err := m.LimitAndOffsetFilter.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRemark(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FilterXProcess) validateCreatedTime(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedTime) { // not required
		return nil
	}

	if m.CreatedTime != nil {
		if err := m.CreatedTime.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("created_time")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("created_time")
			}

			return err
		}
	}

	return nil
}

func (m *FilterXProcess) validateRemark(formats strfmt.Registry) error {
	if swag.IsZero(m.Remark) { // not required
		return nil
	}

	for i := 0; i < len(m.Remark); i++ {
		if swag.IsZero(m.Remark[i]) { // not required
			continue
		}

		if m.Remark[i] != nil {
			if err := m.Remark[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("remark" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("remark" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *FilterXProcess) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if err := m.Status.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("status")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("status")
		}

		return err
	}

	return nil
}

// ContextValidate validate this filter x process based on the context it is used
func (m *FilterXProcess) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with LimitAndOffsetFilter
	if err := m.LimitAndOffsetFilter.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreatedTime(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRemark(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FilterXProcess) contextValidateCreatedTime(ctx context.Context, formats strfmt.Registry) error {

	if m.CreatedTime != nil {

		if swag.IsZero(m.CreatedTime) { // not required
			return nil
		}

		if err := m.CreatedTime.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("created_time")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("created_time")
			}

			return err
		}
	}

	return nil
}

func (m *FilterXProcess) contextValidateRemark(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Remark); i++ {

		if m.Remark[i] != nil {

			if swag.IsZero(m.Remark[i]) { // not required
				return nil
			}

			if err := m.Remark[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("remark" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("remark" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *FilterXProcess) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if err := m.Status.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("status")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("status")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FilterXProcess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FilterXProcess) UnmarshalBinary(b []byte) error {
	var res FilterXProcess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
