// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostScannerdictOKBody post scannerdict o k body
//
// swagger:model postScannerdictOKBody
type PostScannerdictOKBody struct {
	APIResponse

	// data
	Data *ScannerDict `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PostScannerdictOKBody) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 APIResponse
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.APIResponse = aO0

	// now for regular properties
	var propsPostScannerdictOKBody struct {
		Data *ScannerDict `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &propsPostScannerdictOKBody); err != nil {
		return err
	}
	m.Data = propsPostScannerdictOKBody.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PostScannerdictOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.APIResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	// now for regular properties
	var propsPostScannerdictOKBody struct {
		Data *ScannerDict `json:"data,omitempty"`
	}
	propsPostScannerdictOKBody.Data = m.Data

	jsonDataPropsPostScannerdictOKBody, errPostScannerdictOKBody := swag.WriteJSON(propsPostScannerdictOKBody)
	if errPostScannerdictOKBody != nil {
		return nil, errPostScannerdictOKBody
	}
	_parts = append(_parts, jsonDataPropsPostScannerdictOKBody)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post scannerdict o k body
func (m *PostScannerdictOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with APIResponse
	if err := m.APIResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostScannerdictOKBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(m.Data) { // not required
		return nil
	}

	if m.Data != nil {
		if err := m.Data.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("data")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("data")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this post scannerdict o k body based on the context it is used
func (m *PostScannerdictOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with APIResponse
	if err := m.APIResponse.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostScannerdictOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if m.Data != nil {

		if swag.IsZero(m.Data) { // not required
			return nil
		}

		if err := m.Data.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("data")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("data")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostScannerdictOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostScannerdictOKBody) UnmarshalBinary(b []byte) error {
	var res PostScannerdictOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
