// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostVulnBatchUpdateOKBodyDataErrorsItems post vuln batch update o k body data errors items
//
// swagger:model postVulnBatchUpdateOKBodyDataErrorsItems
type PostVulnBatchUpdateOKBodyDataErrorsItems struct {

	// 错误原因，例如 VULN_STATUS_ERROR
	Error string `json:"error,omitempty"`

	// vuln id
	VulnID int64 `json:"vuln_id,omitempty"`
}

// Validate validates this post vuln batch update o k body data errors items
func (m *PostVulnBatchUpdateOKBodyDataErrorsItems) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post vuln batch update o k body data errors items based on context it is used
func (m *PostVulnBatchUpdateOKBodyDataErrorsItems) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostVulnBatchUpdateOKBodyDataErrorsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostVulnBatchUpdateOKBodyDataErrorsItems) UnmarshalBinary(b []byte) error {
	var res PostVulnBatchUpdateOKBodyDataErrorsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
