// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostReportParamsBody 创建报表的目标数据
//
// swagger:model postReportParamsBody
type PostReportParamsBody struct {

	// report type
	// Enum: ["IP_ADDRESS","WEBSITE","VULN","XPROCESS","BASELINE_PROCESS"]
	ReportType string `json:"report_type,omitempty"`
}

// Validate validates this post report params body
func (m *PostReportParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReportType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var postReportParamsBodyTypeReportTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["IP_ADDRESS","WEBSITE","VULN","XPROCESS","BASELINE_PROCESS"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postReportParamsBodyTypeReportTypePropEnum = append(postReportParamsBodyTypeReportTypePropEnum, v)
	}
}

const (

	// PostReportParamsBodyReportTypeIPADDRESS captures enum value "IP_ADDRESS"
	PostReportParamsBodyReportTypeIPADDRESS string = "IP_ADDRESS"

	// PostReportParamsBodyReportTypeWEBSITE captures enum value "WEBSITE"
	PostReportParamsBodyReportTypeWEBSITE string = "WEBSITE"

	// PostReportParamsBodyReportTypeVULN captures enum value "VULN"
	PostReportParamsBodyReportTypeVULN string = "VULN"

	// PostReportParamsBodyReportTypeXPROCESS captures enum value "XPROCESS"
	PostReportParamsBodyReportTypeXPROCESS string = "XPROCESS"

	// PostReportParamsBodyReportTypeBASELINEPROCESS captures enum value "BASELINE_PROCESS"
	PostReportParamsBodyReportTypeBASELINEPROCESS string = "BASELINE_PROCESS"
)

// prop value enum
func (m *PostReportParamsBody) validateReportTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postReportParamsBodyTypeReportTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostReportParamsBody) validateReportType(formats strfmt.Registry) error {
	if swag.IsZero(m.ReportType) { // not required
		return nil
	}

	// value enum
	if err := m.validateReportTypeEnum("report_type", "body", m.ReportType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post report params body based on context it is used
func (m *PostReportParamsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostReportParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostReportParamsBody) UnmarshalBinary(b []byte) error {
	var res PostReportParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
