// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostHostCredentialVerifyOKBody post host credential verify o k body
//
// swagger:model postHostCredentialVerifyOKBody
type PostHostCredentialVerifyOKBody struct {
	APIResponse

	// 校验未通过信息（包含未通过目标及未通过原因）
	// Required: true
	Errors []string `json:"errors"`

	// 校验的总目标数
	// Required: true
	TotalCount *int64 `json:"total_count"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PostHostCredentialVerifyOKBody) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 APIResponse
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.APIResponse = aO0

	// now for regular properties
	var propsPostHostCredentialVerifyOKBody struct {
		Errors []string `json:"errors"`

		TotalCount *int64 `json:"total_count"`
	}
	if err := swag.ReadJSON(raw, &propsPostHostCredentialVerifyOKBody); err != nil {
		return err
	}
	m.Errors = propsPostHostCredentialVerifyOKBody.Errors

	m.TotalCount = propsPostHostCredentialVerifyOKBody.TotalCount

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PostHostCredentialVerifyOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.APIResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	// now for regular properties
	var propsPostHostCredentialVerifyOKBody struct {
		Errors []string `json:"errors"`

		TotalCount *int64 `json:"total_count"`
	}
	propsPostHostCredentialVerifyOKBody.Errors = m.Errors

	propsPostHostCredentialVerifyOKBody.TotalCount = m.TotalCount

	jsonDataPropsPostHostCredentialVerifyOKBody, errPostHostCredentialVerifyOKBody := swag.WriteJSON(propsPostHostCredentialVerifyOKBody)
	if errPostHostCredentialVerifyOKBody != nil {
		return nil, errPostHostCredentialVerifyOKBody
	}
	_parts = append(_parts, jsonDataPropsPostHostCredentialVerifyOKBody)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post host credential verify o k body
func (m *PostHostCredentialVerifyOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with APIResponse
	if err := m.APIResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostHostCredentialVerifyOKBody) validateErrors(formats strfmt.Registry) error {

	if err := validate.Required("errors", "body", m.Errors); err != nil {
		return err
	}

	return nil
}

func (m *PostHostCredentialVerifyOKBody) validateTotalCount(formats strfmt.Registry) error {

	if err := validate.Required("total_count", "body", m.TotalCount); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this post host credential verify o k body based on the context it is used
func (m *PostHostCredentialVerifyOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with APIResponse
	if err := m.APIResponse.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PostHostCredentialVerifyOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostHostCredentialVerifyOKBody) UnmarshalBinary(b []byte) error {
	var res PostHostCredentialVerifyOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
