// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProjectType project type
//
// swagger:model ProjectType
type ProjectType struct {

	// 工作区的 ID
	ID int64 `json:"id,omitempty"`
}

// Validate validates this project type
func (m *ProjectType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this project type based on context it is used
func (m *ProjectType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectType) UnmarshalBinary(b []byte) error {
	var res ProjectType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
