// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ScannerDict scanner dict
//
// swagger:model ScannerDict
type ScannerDict struct {

	// 字典的创建时间
	// Required: true
	// Format: date-time
	CreatedTime *strfmt.DateTime `json:"created_time"`

	// dict type
	// Required: true
	DictType *ScannerDictDictType `json:"dict_type"`

	// 字典的 ID
	// Required: true
	ID *int64 `json:"id"`

	// 字典的名字
	// Required: true
	Name *string `json:"name"`

	// 字典的预览
	// Required: true
	Preview []string `json:"preview"`

	// 字典的行数
	// Required: true
	RowNum *int64 `json:"row_num"`
}

// Validate validates this scanner dict
func (m *ScannerDict) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDictType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePreview(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRowNum(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ScannerDict) validateCreatedTime(formats strfmt.Registry) error {

	if err := validate.Required("created_time", "body", m.CreatedTime); err != nil {
		return err
	}

	if err := validate.FormatOf("created_time", "body", "date-time", m.CreatedTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ScannerDict) validateDictType(formats strfmt.Registry) error {

	if err := validate.Required("dict_type", "body", m.DictType); err != nil {
		return err
	}

	if m.DictType != nil {
		if err := m.DictType.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("dict_type")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("dict_type")
			}

			return err
		}
	}

	return nil
}

func (m *ScannerDict) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *ScannerDict) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *ScannerDict) validatePreview(formats strfmt.Registry) error {

	if err := validate.Required("preview", "body", m.Preview); err != nil {
		return err
	}

	return nil
}

func (m *ScannerDict) validateRowNum(formats strfmt.Registry) error {

	if err := validate.Required("row_num", "body", m.RowNum); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this scanner dict based on the context it is used
func (m *ScannerDict) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDictType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ScannerDict) contextValidateDictType(ctx context.Context, formats strfmt.Registry) error {

	if m.DictType != nil {

		if err := m.DictType.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("dict_type")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("dict_type")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ScannerDict) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScannerDict) UnmarshalBinary(b []byte) error {
	var res ScannerDict
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
