// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SSHKeyResponse SSH key response
//
// swagger:model SSHKeyResponse
type SSHKeyResponse struct {

	// id
	ID int64 `json:"id,omitempty"`

	// project
	Project int64 `json:"project,omitempty"`

	// remark
	Remark string `json:"remark,omitempty"`
}

// Validate validates this SSH key response
func (m *SSHKeyResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this SSH key response based on context it is used
func (m *SSHKeyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SSHKeyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SSHKeyResponse) UnmarshalBinary(b []byte) error {
	var res SSHKeyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
