// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateVulnBodyStatus 要修改的漏洞资产状态
//
// swagger:model updateVulnBodyStatus
type UpdateVulnBodyStatus struct {
	VulnStatusEnum
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *UpdateVulnBodyStatus) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 VulnStatusEnum
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.VulnStatusEnum = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m UpdateVulnBodyStatus) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.VulnStatusEnum)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this update vuln body status
func (m *UpdateVulnBodyStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with VulnStatusEnum
	if err := m.VulnStatusEnum.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this update vuln body status based on the context it is used
func (m *UpdateVulnBodyStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with VulnStatusEnum
	if err := m.VulnStatusEnum.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateVulnBodyStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateVulnBodyStatus) UnmarshalBinary(b []byte) error {
	var res UpdateVulnBodyStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
