// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateDomainBody update domain body
//
// swagger:model UpdateDomainBody
type UpdateDomainBody struct {

	// 要修改的 Domain 的备注
	Remark string `json:"remark,omitempty"`
}

// Validate validates this update domain body
func (m *UpdateDomainBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update domain body based on context it is used
func (m *UpdateDomainBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateDomainBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateDomainBody) UnmarshalBinary(b []byte) error {
	var res UpdateDomainBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
