// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VulnResponseRelatedAsset 漏洞资产相关联的资产
//
// swagger:model vulnResponseRelatedAsset
type VulnResponseRelatedAsset struct {

	// 关联资产的 ID
	ID int64 `json:"id,omitempty"`

	// 关联资产的类型
	// Enum: ["SERVICE","WEBSITE"]
	Type string `json:"type,omitempty"`
}

// Validate validates this vuln response related asset
func (m *VulnResponseRelatedAsset) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var vulnResponseRelatedAssetTypeTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["SERVICE","WEBSITE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		vulnResponseRelatedAssetTypeTypePropEnum = append(vulnResponseRelatedAssetTypeTypePropEnum, v)
	}
}

const (

	// VulnResponseRelatedAssetTypeSERVICE captures enum value "SERVICE"
	VulnResponseRelatedAssetTypeSERVICE string = "SERVICE"

	// VulnResponseRelatedAssetTypeWEBSITE captures enum value "WEBSITE"
	VulnResponseRelatedAssetTypeWEBSITE string = "WEBSITE"
)

// prop value enum
func (m *VulnResponseRelatedAsset) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, vulnResponseRelatedAssetTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *VulnResponseRelatedAsset) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this vuln response related asset based on context it is used
func (m *VulnResponseRelatedAsset) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VulnResponseRelatedAsset) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VulnResponseRelatedAsset) UnmarshalBinary(b []byte) error {
	var res VulnResponseRelatedAsset
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
