// Code generated by go-swagger; DO NOT EDIT.

package insight

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// NewPostInsightAssetIPContinuingCountParams creates a new PostInsightAssetIPContinuingCountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostInsightAssetIPContinuingCountParams() *PostInsightAssetIPContinuingCountParams {
	return &PostInsightAssetIPContinuingCountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostInsightAssetIPContinuingCountParamsWithTimeout creates a new PostInsightAssetIPContinuingCountParams object
// with the ability to set a timeout on a request.
func NewPostInsightAssetIPContinuingCountParamsWithTimeout(timeout time.Duration) *PostInsightAssetIPContinuingCountParams {
	return &PostInsightAssetIPContinuingCountParams{
		timeout: timeout,
	}
}

// NewPostInsightAssetIPContinuingCountParamsWithContext creates a new PostInsightAssetIPContinuingCountParams object
// with the ability to set a context for a request.
func NewPostInsightAssetIPContinuingCountParamsWithContext(ctx context.Context) *PostInsightAssetIPContinuingCountParams {
	return &PostInsightAssetIPContinuingCountParams{
		Context: ctx,
	}
}

// NewPostInsightAssetIPContinuingCountParamsWithHTTPClient creates a new PostInsightAssetIPContinuingCountParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostInsightAssetIPContinuingCountParamsWithHTTPClient(client *http.Client) *PostInsightAssetIPContinuingCountParams {
	return &PostInsightAssetIPContinuingCountParams{
		HTTPClient: client,
	}
}

/*
PostInsightAssetIPContinuingCountParams contains all the parameters to send to the API endpoint

	for the post insight asset IP continuing count operation.

	Typically these are written to a http.Request.
*/
type PostInsightAssetIPContinuingCountParams struct {

	// Body.
	Body *models.PostInsightAssetIPContinuingCountParamsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post insight asset IP continuing count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostInsightAssetIPContinuingCountParams) WithDefaults() *PostInsightAssetIPContinuingCountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post insight asset IP continuing count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostInsightAssetIPContinuingCountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post insight asset IP continuing count params
func (o *PostInsightAssetIPContinuingCountParams) WithTimeout(timeout time.Duration) *PostInsightAssetIPContinuingCountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post insight asset IP continuing count params
func (o *PostInsightAssetIPContinuingCountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post insight asset IP continuing count params
func (o *PostInsightAssetIPContinuingCountParams) WithContext(ctx context.Context) *PostInsightAssetIPContinuingCountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post insight asset IP continuing count params
func (o *PostInsightAssetIPContinuingCountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post insight asset IP continuing count params
func (o *PostInsightAssetIPContinuingCountParams) WithHTTPClient(client *http.Client) *PostInsightAssetIPContinuingCountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post insight asset IP continuing count params
func (o *PostInsightAssetIPContinuingCountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post insight asset IP continuing count params
func (o *PostInsightAssetIPContinuingCountParams) WithBody(body *models.PostInsightAssetIPContinuingCountParamsBody) *PostInsightAssetIPContinuingCountParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post insight asset IP continuing count params
func (o *PostInsightAssetIPContinuingCountParams) SetBody(body *models.PostInsightAssetIPContinuingCountParamsBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostInsightAssetIPContinuingCountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
