// Code generated by go-swagger; DO NOT EDIT.

package ip_asset

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// NewDeleteIPParams creates a new DeleteIPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteIPParams() *DeleteIPParams {
	return &DeleteIPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteIPParamsWithTimeout creates a new DeleteIPParams object
// with the ability to set a timeout on a request.
func NewDeleteIPParamsWithTimeout(timeout time.Duration) *DeleteIPParams {
	return &DeleteIPParams{
		timeout: timeout,
	}
}

// NewDeleteIPParamsWithContext creates a new DeleteIPParams object
// with the ability to set a context for a request.
func NewDeleteIPParamsWithContext(ctx context.Context) *DeleteIPParams {
	return &DeleteIPParams{
		Context: ctx,
	}
}

// NewDeleteIPParamsWithHTTPClient creates a new DeleteIPParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteIPParamsWithHTTPClient(client *http.Client) *DeleteIPParams {
	return &DeleteIPParams{
		HTTPClient: client,
	}
}

/*
DeleteIPParams contains all the parameters to send to the API endpoint

	for the delete IP operation.

	Typically these are written to a http.Request.
*/
type DeleteIPParams struct {

	// Body.
	Body []*models.DeleteIPAddressItem

	/* ProjectID.

	   对应工作区的 ID
	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete IP params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteIPParams) WithDefaults() *DeleteIPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete IP params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteIPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete IP params
func (o *DeleteIPParams) WithTimeout(timeout time.Duration) *DeleteIPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete IP params
func (o *DeleteIPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete IP params
func (o *DeleteIPParams) WithContext(ctx context.Context) *DeleteIPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete IP params
func (o *DeleteIPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete IP params
func (o *DeleteIPParams) WithHTTPClient(client *http.Client) *DeleteIPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete IP params
func (o *DeleteIPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete IP params
func (o *DeleteIPParams) WithBody(body []*models.DeleteIPAddressItem) *DeleteIPParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete IP params
func (o *DeleteIPParams) SetBody(body []*models.DeleteIPAddressItem) {
	o.Body = body
}

// WithProjectID adds the projectID to the delete IP params
func (o *DeleteIPParams) WithProjectID(projectID int64) *DeleteIPParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the delete IP params
func (o *DeleteIPParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteIPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// query param project_id
	qrProjectID := o.ProjectID
	qProjectID := swag.FormatInt64(qrProjectID)
	if qProjectID != "" {

		if err := r.SetQueryParam("project_id", qProjectID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
