// Code generated by go-swagger; DO NOT EDIT.

package ip_asset

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// NewPostIPFilterParams creates a new PostIPFilterParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostIPFilterParams() *PostIPFilterParams {
	return &PostIPFilterParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostIPFilterParamsWithTimeout creates a new PostIPFilterParams object
// with the ability to set a timeout on a request.
func NewPostIPFilterParamsWithTimeout(timeout time.Duration) *PostIPFilterParams {
	return &PostIPFilterParams{
		timeout: timeout,
	}
}

// NewPostIPFilterParamsWithContext creates a new PostIPFilterParams object
// with the ability to set a context for a request.
func NewPostIPFilterParamsWithContext(ctx context.Context) *PostIPFilterParams {
	return &PostIPFilterParams{
		Context: ctx,
	}
}

// NewPostIPFilterParamsWithHTTPClient creates a new PostIPFilterParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostIPFilterParamsWithHTTPClient(client *http.Client) *PostIPFilterParams {
	return &PostIPFilterParams{
		HTTPClient: client,
	}
}

/*
PostIPFilterParams contains all the parameters to send to the API endpoint

	for the post IP filter operation.

	Typically these are written to a http.Request.
*/
type PostIPFilterParams struct {

	// Body.
	Body *models.FilterIPAddress

	/* ProjectID.

	   对应工作区的 ID
	*/
	ProjectID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post IP filter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostIPFilterParams) WithDefaults() *PostIPFilterParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post IP filter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostIPFilterParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post IP filter params
func (o *PostIPFilterParams) WithTimeout(timeout time.Duration) *PostIPFilterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post IP filter params
func (o *PostIPFilterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post IP filter params
func (o *PostIPFilterParams) WithContext(ctx context.Context) *PostIPFilterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post IP filter params
func (o *PostIPFilterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post IP filter params
func (o *PostIPFilterParams) WithHTTPClient(client *http.Client) *PostIPFilterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post IP filter params
func (o *PostIPFilterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post IP filter params
func (o *PostIPFilterParams) WithBody(body *models.FilterIPAddress) *PostIPFilterParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post IP filter params
func (o *PostIPFilterParams) SetBody(body *models.FilterIPAddress) {
	o.Body = body
}

// WithProjectID adds the projectID to the post IP filter params
func (o *PostIPFilterParams) WithProjectID(projectID int64) *PostIPFilterParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the post IP filter params
func (o *PostIPFilterParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *PostIPFilterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// query param project_id
	qrProjectID := o.ProjectID
	qProjectID := swag.FormatInt64(qrProjectID)
	if qProjectID != "" {

		if err := r.SetQueryParam("project_id", qProjectID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
