// Code generated by go-swagger; DO NOT EDIT.

package asset_property

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// NewPostLocationFilterParams creates a new PostLocationFilterParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostLocationFilterParams() *PostLocationFilterParams {
	return &PostLocationFilterParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostLocationFilterParamsWithTimeout creates a new PostLocationFilterParams object
// with the ability to set a timeout on a request.
func NewPostLocationFilterParamsWithTimeout(timeout time.Duration) *PostLocationFilterParams {
	return &PostLocationFilterParams{
		timeout: timeout,
	}
}

// NewPostLocationFilterParamsWithContext creates a new PostLocationFilterParams object
// with the ability to set a context for a request.
func NewPostLocationFilterParamsWithContext(ctx context.Context) *PostLocationFilterParams {
	return &PostLocationFilterParams{
		Context: ctx,
	}
}

// NewPostLocationFilterParamsWithHTTPClient creates a new PostLocationFilterParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostLocationFilterParamsWithHTTPClient(client *http.Client) *PostLocationFilterParams {
	return &PostLocationFilterParams{
		HTTPClient: client,
	}
}

/*
PostLocationFilterParams contains all the parameters to send to the API endpoint

	for the post location filter operation.

	Typically these are written to a http.Request.
*/
type PostLocationFilterParams struct {

	// Body.
	Body *models.AssetPropertyLocationFilter

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post location filter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostLocationFilterParams) WithDefaults() *PostLocationFilterParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post location filter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostLocationFilterParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post location filter params
func (o *PostLocationFilterParams) WithTimeout(timeout time.Duration) *PostLocationFilterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post location filter params
func (o *PostLocationFilterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post location filter params
func (o *PostLocationFilterParams) WithContext(ctx context.Context) *PostLocationFilterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post location filter params
func (o *PostLocationFilterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post location filter params
func (o *PostLocationFilterParams) WithHTTPClient(client *http.Client) *PostLocationFilterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post location filter params
func (o *PostLocationFilterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post location filter params
func (o *PostLocationFilterParams) WithBody(body *models.AssetPropertyLocationFilter) *PostLocationFilterParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post location filter params
func (o *PostLocationFilterParams) SetBody(body *models.AssetPropertyLocationFilter) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostLocationFilterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
