// Code generated by workspace-cli-generator. DO NOT EDIT.

package security_tool

import (
	"github.com/spf13/cobra"
)

var SecurityToolCmd = &cobra.Command{
	Use:   "security_tool",
	Short: "安全工具",
	Long:  `安全工具相关操作`,
}

func init() {
	SecurityToolCmd.AddCommand(GetTaskResultListCmd)
	SecurityToolCmd.AddCommand(GetToolDetailCmd)
	SecurityToolCmd.AddCommand(GetToolListCmd)
}
