// Code generated by go-swagger; DO NOT EDIT.

package baseline

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// PostBaselineTaskStopReader is a Reader for the PostBaselineTaskStop structure.
type PostBaselineTaskStopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostBaselineTaskStopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostBaselineTaskStopOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /baseline/task/stop] PostBaselineTaskStop", response, response.Code())
	}
}

// NewPostBaselineTaskStopOK creates a PostBaselineTaskStopOK with default headers values
func NewPostBaselineTaskStopOK() *PostBaselineTaskStopOK {
	return &PostBaselineTaskStopOK{}
}

/*
PostBaselineTaskStopOK describes a response with status code 200, with default header values.

Response
*/
type PostBaselineTaskStopOK struct {
	Payload *models.PostBaselineTaskStopOKBody
}

// IsSuccess returns true when this post baseline task stop o k response has a 2xx status code
func (o *PostBaselineTaskStopOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post baseline task stop o k response has a 3xx status code
func (o *PostBaselineTaskStopOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post baseline task stop o k response has a 4xx status code
func (o *PostBaselineTaskStopOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post baseline task stop o k response has a 5xx status code
func (o *PostBaselineTaskStopOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post baseline task stop o k response a status code equal to that given
func (o *PostBaselineTaskStopOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post baseline task stop o k response
func (o *PostBaselineTaskStopOK) Code() int {
	return 200
}

func (o *PostBaselineTaskStopOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /baseline/task/stop][%d] postBaselineTaskStopOK %s", 200, payload)
}

func (o *PostBaselineTaskStopOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /baseline/task/stop][%d] postBaselineTaskStopOK %s", 200, payload)
}

func (o *PostBaselineTaskStopOK) GetPayload() *models.PostBaselineTaskStopOKBody {
	return o.Payload
}

func (o *PostBaselineTaskStopOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostBaselineTaskStopOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
