// Code generated by workspace-cli-generator. DO NOT EDIT.

package host_asset

import (
	"context"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var setAntiUninstallConfigParams SetAntiUninstallConfigParams

var SetAntiUninstallConfigCmd = &cobra.Command{
	Use:   "set_anti_uninstall_config",
	Short: "设置探针防卸载开关",
	Long:  `设置探针防卸载开关`,
	Run: func(cmd *cobra.Command, args []string) {

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "HostAssetService.SetAntiUninstallConfig", setAntiUninstallConfigParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	SetAntiUninstallConfigCmd.Flags().StringVar(&setAntiUninstallConfigParams.AntiUninstallStatus, "anti-uninstall-status", "", "防卸载状态，enable:防卸载开启，disable:防卸载关闭")
	SetAntiUninstallConfigCmd.Flags().StringVar(&setAntiUninstallConfigParams.Totp, "totp", "", "双因子认证口令")
}

// SetAntiUninstallConfigParams 请求参数
type SetAntiUninstallConfigParams struct {
	AntiUninstallStatus string `json:"anti_uninstall_status"` // 防卸载状态，enable:防卸载开启，disable:防卸载关闭
	Totp                string `json:"totp"`                  // 双因子认证口令
}
