// Code generated by workspace-cli-generator. DO NOT EDIT.

package memory_webshell_event

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getEventByHostListParams GetEventByHostListParams
var GetEventByHostListCustomAttrJSON string
var GetEventByHostListOrderByJSON string
var GetEventByHostListSelectJSON string

var GetEventByHostListCmd = &cobra.Command{
	Use:   "get_event_by_host_list",
	Short: "根据主机获取事件列表",
	Long:  `根据主机获取事件列表`,
	Run: func(cmd *cobra.Command, args []string) {
		if GetEventByHostListCustomAttrJSON != "" {
			if err := json.Unmarshal([]byte(GetEventByHostListCustomAttrJSON), &getEventByHostListParams.CustomAttr); err != nil {
				cmd.PrintErrln("Error parsing custom-attr:", err)
				return
			}
		}
		if GetEventByHostListOrderByJSON != "" {
			if err := json.Unmarshal([]byte(GetEventByHostListOrderByJSON), &getEventByHostListParams.OrderBy); err != nil {
				cmd.PrintErrln("Error parsing order-by:", err)
				return
			}
		}
		if GetEventByHostListSelectJSON != "" {
			if err := json.Unmarshal([]byte(GetEventByHostListSelectJSON), &getEventByHostListParams.Select); err != nil {
				cmd.PrintErrln("Error parsing select:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "MemoryWebshellEventService.GetEventByHostList", getEventByHostListParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	GetEventByHostListCmd.Flags().StringSliceVar(&getEventByHostListParams.ClassName, "class-name", nil, "类名")
	GetEventByHostListCmd.Flags().StringSliceVar(&getEventByHostListParams.Comment, "comment", nil, "用户自定义备注")
	GetEventByHostListCmd.Flags().IntVar(&getEventByHostListParams.Count, "count", 20, "每页记录数量, 默认为 20")
	GetEventByHostListCmd.Flags().StringSliceVar(&getEventByHostListParams.CreatedAt, "created-at", nil, "事件发现时间")
	// custom_attr is complex type []map[string]interface{}, use JSON string
	GetEventByHostListCmd.Flags().StringVar(&GetEventByHostListCustomAttrJSON, "custom-attr", "", "主机业务属性 (JSON, e.g. [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}])")
	GetEventByHostListCmd.Flags().Float64SliceVar(&getEventByHostListParams.Gids, "gids", nil, "业务组 ID")
	GetEventByHostListCmd.Flags().StringSliceVar(&getEventByHostListParams.HostComment, "host-comment", nil, "主机备注")
	GetEventByHostListCmd.Flags().Float64SliceVar(&getEventByHostListParams.HostId, "host-id", nil, "主机 ID")
	GetEventByHostListCmd.Flags().StringSliceVar(&getEventByHostListParams.HostIp, "host-ip", nil, "主机 IP")
	GetEventByHostListCmd.Flags().StringSliceVar(&getEventByHostListParams.HostName, "host-name", nil, "主机名称")
	GetEventByHostListCmd.Flags().StringSliceVar(&getEventByHostListParams.HostState, "host-state", nil, "主机状态")
	GetEventByHostListCmd.Flags().StringSliceVar(&getEventByHostListParams.HostTags, "host-tags", nil, "主机标签")
	GetEventByHostListCmd.Flags().Float64SliceVar(&getEventByHostListParams.Id, "id", nil, "事件ID")
	GetEventByHostListCmd.Flags().IntSliceVar(&getEventByHostListParams.Level, "level", nil, "事件等级(1-低危，2-中危，3-高危，4-严重)")
	GetEventByHostListCmd.Flags().IntVar(&getEventByHostListParams.Offset, "offset", 0, "页偏移, 默认为 0")
	GetEventByHostListCmd.Flags().Float64SliceVar(&getEventByHostListParams.Oid, "oid", nil, "机构 ID")
	// order_by is object type, use JSON string
	GetEventByHostListCmd.Flags().StringVar(&GetEventByHostListOrderByJSON, "order-by", "", "排序规则 (JSON, e.g. {\"column\": \"level\", \"order\": \"ASC\"})")
	GetEventByHostListCmd.Flags().Float64SliceVar(&getEventByHostListParams.Pid, "pid", nil, "进程 ID")
	GetEventByHostListCmd.Flags().Float64SliceVar(&getEventByHostListParams.PlanId, "plan-id", nil, "任务 id")
	GetEventByHostListCmd.Flags().StringSliceVar(&getEventByHostListParams.ProcessName, "process-name", nil, "进程名称")
	// select is complex type []map[string]interface{}, use JSON string
	GetEventByHostListCmd.Flags().StringVar(&GetEventByHostListSelectJSON, "select", "", "select (JSON, e.g. [{\"class_name\": \".class\", \"host_id\": 162, \"id\": 154, \"server_name\": \"tomcat\"}])")
	GetEventByHostListCmd.Flags().BoolVar(&getEventByHostListParams.SelectAll, "select-all", false, "是否全选")
	GetEventByHostListCmd.Flags().StringSliceVar(&getEventByHostListParams.ServerName, "server-name", nil, "服务名称")
	GetEventByHostListCmd.Flags().Float64SliceVar(&getEventByHostListParams.StatEventId, "stat-event-id", nil, "事件统计 ID")
	GetEventByHostListCmd.Flags().IntSliceVar(&getEventByHostListParams.State, "state", nil, "事件状态(1-有风险，2-已忽略，3-已处理)")
	GetEventByHostListCmd.Flags().Float64SliceVar(&getEventByHostListParams.Type, "type", nil, "事件类型 1:内存马 2:内存恶意代码")
	GetEventByHostListCmd.Flags().StringSliceVar(&getEventByHostListParams.UpdatedAt, "updated-at", nil, "最后发现时间")
	GetEventByHostListCmd.Flags().StringSliceVar(&getEventByHostListParams.WhiteRuleId, "white-rule-id", nil, "白名单规则 ID")
}

// GetEventByHostListParams 请求参数
type GetEventByHostListParams struct {
	ClassName   []string                 `json:"class_name"`    // 类名
	Comment     []string                 `json:"comment"`       // 用户自定义备注
	Count       int                      `json:"count"`         // 每页记录数量, 默认为 20
	CreatedAt   []string                 `json:"created_at"`    // 事件发现时间
	CustomAttr  []map[string]interface{} `json:"custom_attr"`   // 主机业务属性
	Gids        []float64                `json:"gids"`          // 业务组 ID
	HostComment []string                 `json:"host_comment"`  // 主机备注
	HostId      []float64                `json:"host_id"`       // 主机 ID
	HostIp      []string                 `json:"host_ip"`       // 主机 IP
	HostName    []string                 `json:"host_name"`     // 主机名称
	HostState   []string                 `json:"host_state"`    // 主机状态
	HostTags    []string                 `json:"host_tags"`     // 主机标签
	Id          []float64                `json:"id"`            // 事件ID
	Level       []int                    `json:"level"`         // 事件等级(1-低危，2-中危，3-高危，4-严重)
	Offset      int                      `json:"offset"`        // 页偏移, 默认为 0
	Oid         []float64                `json:"oid"`           // 机构 ID
	OrderBy     map[string]interface{}   `json:"order_by"`      // 排序规则
	Pid         []float64                `json:"pid"`           // 进程 ID
	PlanId      []float64                `json:"plan_id"`       // 任务 id
	ProcessName []string                 `json:"process_name"`  // 进程名称
	Select      []map[string]interface{} `json:"select"`        // select
	SelectAll   bool                     `json:"select_all"`    // 是否全选
	ServerName  []string                 `json:"server_name"`   // 服务名称
	StatEventId []float64                `json:"stat_event_id"` // 事件统计 ID
	State       []int                    `json:"state"`         // 事件状态(1-有风险，2-已忽略，3-已处理)
	Type        []float64                `json:"type"`          // 事件类型 1:内存马 2:内存恶意代码
	UpdatedAt   []string                 `json:"updated_at"`    // 最后发现时间
	WhiteRuleId []string                 `json:"white_rule_id"` // 白名单规则 ID
}
