// Code generated by go-swagger; DO NOT EDIT.

package service_asset

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// PostServiceIDReader is a Reader for the PostServiceID structure.
type PostServiceIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostServiceIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostServiceIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /service/{id}] PostServiceID", response, response.Code())
	}
}

// NewPostServiceIDOK creates a PostServiceIDOK with default headers values
func NewPostServiceIDOK() *PostServiceIDOK {
	return &PostServiceIDOK{}
}

/*
PostServiceIDOK describes a response with status code 200, with default header values.

Response
*/
type PostServiceIDOK struct {
	Payload *models.APIResponse
}

// IsSuccess returns true when this post service Id o k response has a 2xx status code
func (o *PostServiceIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post service Id o k response has a 3xx status code
func (o *PostServiceIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post service Id o k response has a 4xx status code
func (o *PostServiceIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post service Id o k response has a 5xx status code
func (o *PostServiceIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post service Id o k response a status code equal to that given
func (o *PostServiceIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post service Id o k response
func (o *PostServiceIDOK) Code() int {
	return 200
}

func (o *PostServiceIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /service/{id}][%d] postServiceIdOK %s", 200, payload)
}

func (o *PostServiceIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /service/{id}][%d] postServiceIdOK %s", 200, payload)
}

func (o *PostServiceIDOK) GetPayload() *models.APIResponse {
	return o.Payload
}

func (o *PostServiceIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
