// Code generated by workspace-cli-generator. DO NOT EDIT.

package report

import (
	"context"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var deleteReportParams DeleteReportParams

var DeleteReportCmd = &cobra.Command{
	Use:   "delete_report",
	Short: "删除报告",
	Long:  `删除报告`,
	Run: func(cmd *cobra.Command, args []string) {

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "ReportService.DeleteReport", deleteReportParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	DeleteReportCmd.Flags().Float64SliceVar(&deleteReportParams.Ids, "ids", nil, "ID")
	DeleteReportCmd.Flags().StringSliceVar(&deleteReportParams.Name, "name", nil, "报告名称")
	DeleteReportCmd.Flags().BoolVar(&deleteReportParams.SelectAll, "select-all", false, "是否选中所有")
}

// DeleteReportParams 请求参数
type DeleteReportParams struct {
	Ids       []float64 `json:"ids"`        // ID
	Name      []string  `json:"name"`       // 报告名称
	SelectAll bool      `json:"select_all"` // 是否选中所有
}
