// Code generated by workspace-cli-generator. DO NOT EDIT.

package admin_monitor

import (
	"github.com/spf13/cobra"
)

var AdminMonitorCmd = &cobra.Command{
	Use:   "admin_monitor",
	Short: "监控管理",
	Long:  `监控管理相关操作`,
}

func init() {
	AdminMonitorCmd.AddCommand(GetContainerListCmd)
	AdminMonitorCmd.AddCommand(GetNsqStatisticsCmd)
	AdminMonitorCmd.AddCommand(GetRedisStatisticsCmd)
}
