// Code generated by go-swagger; DO NOT EDIT.

package system_service

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// PostPackageCheckReader is a Reader for the PostPackageCheck structure.
type PostPackageCheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostPackageCheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostPackageCheckOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /package/check] PostPackageCheck", response, response.Code())
	}
}

// NewPostPackageCheckOK creates a PostPackageCheckOK with default headers values
func NewPostPackageCheckOK() *PostPackageCheckOK {
	return &PostPackageCheckOK{}
}

/*
PostPackageCheckOK describes a response with status code 200, with default header values.

Response
*/
type PostPackageCheckOK struct {
	Payload *models.PostPackageCheckOKBody
}

// IsSuccess returns true when this post package check o k response has a 2xx status code
func (o *PostPackageCheckOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post package check o k response has a 3xx status code
func (o *PostPackageCheckOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post package check o k response has a 4xx status code
func (o *PostPackageCheckOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post package check o k response has a 5xx status code
func (o *PostPackageCheckOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post package check o k response a status code equal to that given
func (o *PostPackageCheckOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post package check o k response
func (o *PostPackageCheckOK) Code() int {
	return 200
}

func (o *PostPackageCheckOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /package/check][%d] postPackageCheckOK %s", 200, payload)
}

func (o *PostPackageCheckOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /package/check][%d] postPackageCheckOK %s", 200, payload)
}

func (o *PostPackageCheckOK) GetPayload() *models.PostPackageCheckOKBody {
	return o.Payload
}

func (o *PostPackageCheckOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostPackageCheckOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
