// Code generated by workspace-cli-generator. DO NOT EDIT.

package emergency_vuln_v1

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var editEventCommentParams EditEventCommentParams
var EditEventCommentSelectJSON string

var EditEventCommentCmd = &cobra.Command{
	Use:   "edit_event_comment",
	Short: "改变所选应急漏洞事件备注",
	Long:  `改变所选应急漏洞事件备注`,
	Run: func(cmd *cobra.Command, args []string) {
		if EditEventCommentSelectJSON != "" {
			if err := json.Unmarshal([]byte(EditEventCommentSelectJSON), &editEventCommentParams.Select); err != nil {
				cmd.PrintErrln("Error parsing select:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "EmergencyVulnV1Service.EditEventComment", editEventCommentParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	EditEventCommentCmd.Flags().StringVar(&editEventCommentParams.NewComment, "new-comment", "", "新的事件备注")
	// select is complex type []map[string]interface{}, use JSON string
	EditEventCommentCmd.Flags().StringVar(&EditEventCommentSelectJSON, "select", "", "select (JSON, e.g. [{\"event_id\": 120, \"host_id\": 111, \"vuln_id\": 111}])")
	EditEventCommentCmd.Flags().BoolVar(&editEventCommentParams.SelectAll, "select-all", false, "select_all")
}

// EditEventCommentParams 请求参数
type EditEventCommentParams struct {
	NewComment string                   `json:"new_comment"` // 新的事件备注
	Select     []map[string]interface{} `json:"select"`      // select
	SelectAll  bool                     `json:"select_all"`  // select_all
}
