// Code generated by workspace-cli-generator. DO NOT EDIT.

package package_service

import (
	"context"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var cancelDownloadParams CancelDownloadParams

var CancelDownloadCmd = &cobra.Command{
	Use:   "cancel_download",
	Short: "取消下载",
	Long:  `取消下载`,
	Run: func(cmd *cobra.Command, args []string) {

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "PackageService.CancelDownload", cancelDownloadParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	CancelDownloadCmd.Flags().StringVar(&cancelDownloadParams.Name, "name", "", "升级包名称")
}

// CancelDownloadParams 请求参数
type CancelDownloadParams struct {
	Name string `json:"name"` // 升级包名称
}
