// Code generated by workspace-cli-generator. DO NOT EDIT.

package webshell_event

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var retestEventParams RetestEventParams
var RetestEventCustomAttrJSON string
var RetestEventSelectJSON string

var RetestEventCmd = &cobra.Command{
	Use:   "retest_event",
	Short: "触发一个探针端任务用来检测 Webshell 是否仍然存在",
	Long:  `触发一个探针端任务用来检测 Webshell 是否仍然存在`,
	Run: func(cmd *cobra.Command, args []string) {
		if RetestEventCustomAttrJSON != "" {
			if err := json.Unmarshal([]byte(RetestEventCustomAttrJSON), &retestEventParams.CustomAttr); err != nil {
				cmd.PrintErrln("Error parsing custom-attr:", err)
				return
			}
		}
		if RetestEventSelectJSON != "" {
			if err := json.Unmarshal([]byte(RetestEventSelectJSON), &retestEventParams.Select); err != nil {
				cmd.PrintErrln("Error parsing select:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "WebshellEventService.RetestEvent", retestEventParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	RetestEventCmd.Flags().StringSliceVar(&retestEventParams.Comment, "comment", nil, "用户自定义备注")
	RetestEventCmd.Flags().StringSliceVar(&retestEventParams.CreatedAt, "created-at", nil, "事件发现时间")
	// custom_attr is complex type []map[string]interface{}, use JSON string
	RetestEventCmd.Flags().StringVar(&RetestEventCustomAttrJSON, "custom-attr", "", "主机业务属性 (JSON, e.g. [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}])")
	RetestEventCmd.Flags().StringSliceVar(&retestEventParams.Domain, "domain", nil, "域名")
	RetestEventCmd.Flags().StringSliceVar(&retestEventParams.FileName, "file-name", nil, "文件名")
	RetestEventCmd.Flags().StringSliceVar(&retestEventParams.FilePath, "file-path", nil, "文件路径")
	RetestEventCmd.Flags().Float64SliceVar(&retestEventParams.Gids, "gids", nil, "业务组 ID")
	RetestEventCmd.Flags().StringSliceVar(&retestEventParams.HostComment, "host-comment", nil, "主机备注")
	RetestEventCmd.Flags().Float64SliceVar(&retestEventParams.HostId, "host-id", nil, "主机 ID")
	RetestEventCmd.Flags().StringSliceVar(&retestEventParams.HostIp, "host-ip", nil, "主机 IP")
	RetestEventCmd.Flags().StringSliceVar(&retestEventParams.HostName, "host-name", nil, "主机名称")
	RetestEventCmd.Flags().StringSliceVar(&retestEventParams.HostState, "host-state", nil, "主机状态")
	RetestEventCmd.Flags().StringSliceVar(&retestEventParams.HostTags, "host-tags", nil, "主机标签")
	RetestEventCmd.Flags().Float64SliceVar(&retestEventParams.Id, "id", nil, "事件ID")
	RetestEventCmd.Flags().Float64SliceVar(&retestEventParams.IsolateState, "isolate-state", nil, "隔离状态")
	RetestEventCmd.Flags().IntSliceVar(&retestEventParams.Level, "level", nil, "事件等级(1-低危，2-中危，3-高危，4-严重)")
	RetestEventCmd.Flags().StringSliceVar(&retestEventParams.Md5, "md5", nil, "文件 MD5")
	RetestEventCmd.Flags().Float64SliceVar(&retestEventParams.Oid, "oid", nil, "机构 ID")
	RetestEventCmd.Flags().Float64SliceVar(&retestEventParams.PlanId, "plan-id", nil, "任务 id")
	// select is complex type []map[string]interface{}, use JSON string
	RetestEventCmd.Flags().StringVar(&RetestEventSelectJSON, "select", "", "select (JSON, e.g. [{\"file_name\": \"WebShell\", \"file_path\": \"mem://[java.exe:9540]/org.apache.coyote.type.TypeBase\", \"host_id\": 162, \"id\": 154, \"webshell_type\": \"java_memory_webshell\"}])")
	RetestEventCmd.Flags().BoolVar(&retestEventParams.SelectAll, "select-all", false, "是否全选")
	RetestEventCmd.Flags().Float64SliceVar(&retestEventParams.StatEventId, "stat-event-id", nil, "统计事件 ID")
	RetestEventCmd.Flags().IntSliceVar(&retestEventParams.State, "state", nil, "事件状态(1-有风险，2-已忽略，3-已处理)")
	RetestEventCmd.Flags().StringSliceVar(&retestEventParams.UpdatedAt, "updated-at", nil, "最后发现时间")
	RetestEventCmd.Flags().StringSliceVar(&retestEventParams.WebshellType, "webshell-type", nil, "Webshell 类型")
	RetestEventCmd.Flags().StringSliceVar(&retestEventParams.WhiteRuleId, "white-rule-id", nil, "白名单规则 ID")
}

// RetestEventParams 请求参数
type RetestEventParams struct {
	Comment      []string                 `json:"comment"`       // 用户自定义备注
	CreatedAt    []string                 `json:"created_at"`    // 事件发现时间
	CustomAttr   []map[string]interface{} `json:"custom_attr"`   // 主机业务属性
	Domain       []string                 `json:"domain"`        // 域名
	FileName     []string                 `json:"file_name"`     // 文件名
	FilePath     []string                 `json:"file_path"`     // 文件路径
	Gids         []float64                `json:"gids"`          // 业务组 ID
	HostComment  []string                 `json:"host_comment"`  // 主机备注
	HostId       []float64                `json:"host_id"`       // 主机 ID
	HostIp       []string                 `json:"host_ip"`       // 主机 IP
	HostName     []string                 `json:"host_name"`     // 主机名称
	HostState    []string                 `json:"host_state"`    // 主机状态
	HostTags     []string                 `json:"host_tags"`     // 主机标签
	Id           []float64                `json:"id"`            // 事件ID
	IsolateState []float64                `json:"isolate_state"` // 隔离状态
	Level        []int                    `json:"level"`         // 事件等级(1-低危，2-中危，3-高危，4-严重)
	Md5          []string                 `json:"md5"`           // 文件 MD5
	Oid          []float64                `json:"oid"`           // 机构 ID
	PlanId       []float64                `json:"plan_id"`       // 任务 id
	Select       []map[string]interface{} `json:"select"`        // select
	SelectAll    bool                     `json:"select_all"`    // 是否全选
	StatEventId  []float64                `json:"stat_event_id"` // 统计事件 ID
	State        []int                    `json:"state"`         // 事件状态(1-有风险，2-已忽略，3-已处理)
	UpdatedAt    []string                 `json:"updated_at"`    // 最后发现时间
	WebshellType []string                 `json:"webshell_type"` // Webshell 类型
	WhiteRuleId  []string                 `json:"white_rule_id"` // 白名单规则 ID
}
