// Code generated by workspace-cli-generator. DO NOT EDIT.

package webshell_event

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var statEventByFileNameParams StatEventByFileNameParams
var StatEventByFileNameCustomAttrJSON string

var StatEventByFileNameCmd = &cobra.Command{
	Use:   "stat_event_by_file_name",
	Short: "获取按文件名聚合的统计结果",
	Long:  `获取按文件名聚合的统计结果`,
	Run: func(cmd *cobra.Command, args []string) {
		if StatEventByFileNameCustomAttrJSON != "" {
			if err := json.Unmarshal([]byte(StatEventByFileNameCustomAttrJSON), &statEventByFileNameParams.CustomAttr); err != nil {
				cmd.PrintErrln("Error parsing custom-attr:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "WebshellEventService.StatEventByFileName", statEventByFileNameParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	StatEventByFileNameCmd.Flags().StringSliceVar(&statEventByFileNameParams.Comment, "comment", nil, "用户自定义备注")
	StatEventByFileNameCmd.Flags().IntVar(&statEventByFileNameParams.Count, "count", 20, "返回数据数量")
	StatEventByFileNameCmd.Flags().StringSliceVar(&statEventByFileNameParams.CreatedAt, "created-at", nil, "事件发现时间")
	// custom_attr is complex type []map[string]interface{}, use JSON string
	StatEventByFileNameCmd.Flags().StringVar(&StatEventByFileNameCustomAttrJSON, "custom-attr", "", "主机业务属性 (JSON, e.g. [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}])")
	StatEventByFileNameCmd.Flags().StringSliceVar(&statEventByFileNameParams.Domain, "domain", nil, "域名")
	StatEventByFileNameCmd.Flags().StringSliceVar(&statEventByFileNameParams.FileName, "file-name", nil, "文件名")
	StatEventByFileNameCmd.Flags().StringSliceVar(&statEventByFileNameParams.FilePath, "file-path", nil, "文件路径")
	StatEventByFileNameCmd.Flags().Float64SliceVar(&statEventByFileNameParams.Gids, "gids", nil, "业务组 ID")
	StatEventByFileNameCmd.Flags().StringSliceVar(&statEventByFileNameParams.HostComment, "host-comment", nil, "主机备注")
	StatEventByFileNameCmd.Flags().Float64SliceVar(&statEventByFileNameParams.HostId, "host-id", nil, "主机 ID")
	StatEventByFileNameCmd.Flags().StringSliceVar(&statEventByFileNameParams.HostIp, "host-ip", nil, "主机 IP")
	StatEventByFileNameCmd.Flags().StringSliceVar(&statEventByFileNameParams.HostName, "host-name", nil, "主机名称")
	StatEventByFileNameCmd.Flags().StringSliceVar(&statEventByFileNameParams.HostState, "host-state", nil, "主机状态")
	StatEventByFileNameCmd.Flags().StringSliceVar(&statEventByFileNameParams.HostTags, "host-tags", nil, "主机标签")
	StatEventByFileNameCmd.Flags().Float64SliceVar(&statEventByFileNameParams.Id, "id", nil, "事件ID")
	StatEventByFileNameCmd.Flags().Float64SliceVar(&statEventByFileNameParams.IsolateState, "isolate-state", nil, "隔离状态")
	StatEventByFileNameCmd.Flags().IntSliceVar(&statEventByFileNameParams.Level, "level", nil, "事件等级(1-低危，2-中危，3-高危，4-严重)")
	StatEventByFileNameCmd.Flags().StringSliceVar(&statEventByFileNameParams.Md5, "md5", nil, "文件 MD5")
	StatEventByFileNameCmd.Flags().Float64SliceVar(&statEventByFileNameParams.Oid, "oid", nil, "机构 ID")
	StatEventByFileNameCmd.Flags().Float64SliceVar(&statEventByFileNameParams.PlanId, "plan-id", nil, "任务 id")
	StatEventByFileNameCmd.Flags().Float64SliceVar(&statEventByFileNameParams.StatEventId, "stat-event-id", nil, "统计事件 ID")
	StatEventByFileNameCmd.Flags().IntSliceVar(&statEventByFileNameParams.State, "state", nil, "事件状态(1-有风险，2-已忽略，3-已处理)")
	StatEventByFileNameCmd.Flags().StringSliceVar(&statEventByFileNameParams.UpdatedAt, "updated-at", nil, "最后发现时间")
	StatEventByFileNameCmd.Flags().StringSliceVar(&statEventByFileNameParams.WebshellType, "webshell-type", nil, "Webshell 类型")
	StatEventByFileNameCmd.Flags().StringSliceVar(&statEventByFileNameParams.WhiteRuleId, "white-rule-id", nil, "白名单规则 ID")
}

// StatEventByFileNameParams 请求参数
type StatEventByFileNameParams struct {
	Comment      []string                 `json:"comment"`       // 用户自定义备注
	Count        int                      `json:"count"`         // 返回数据数量
	CreatedAt    []string                 `json:"created_at"`    // 事件发现时间
	CustomAttr   []map[string]interface{} `json:"custom_attr"`   // 主机业务属性
	Domain       []string                 `json:"domain"`        // 域名
	FileName     []string                 `json:"file_name"`     // 文件名
	FilePath     []string                 `json:"file_path"`     // 文件路径
	Gids         []float64                `json:"gids"`          // 业务组 ID
	HostComment  []string                 `json:"host_comment"`  // 主机备注
	HostId       []float64                `json:"host_id"`       // 主机 ID
	HostIp       []string                 `json:"host_ip"`       // 主机 IP
	HostName     []string                 `json:"host_name"`     // 主机名称
	HostState    []string                 `json:"host_state"`    // 主机状态
	HostTags     []string                 `json:"host_tags"`     // 主机标签
	Id           []float64                `json:"id"`            // 事件ID
	IsolateState []float64                `json:"isolate_state"` // 隔离状态
	Level        []int                    `json:"level"`         // 事件等级(1-低危，2-中危，3-高危，4-严重)
	Md5          []string                 `json:"md5"`           // 文件 MD5
	Oid          []float64                `json:"oid"`           // 机构 ID
	PlanId       []float64                `json:"plan_id"`       // 任务 id
	StatEventId  []float64                `json:"stat_event_id"` // 统计事件 ID
	State        []int                    `json:"state"`         // 事件状态(1-有风险，2-已忽略，3-已处理)
	UpdatedAt    []string                 `json:"updated_at"`    // 最后发现时间
	WebshellType []string                 `json:"webshell_type"` // Webshell 类型
	WhiteRuleId  []string                 `json:"white_rule_id"` // 白名单规则 ID
}
