// Code generated by workspace-cli-generator. DO NOT EDIT.

package asset_config

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var deleteWebScanRuleParams DeleteWebScanRuleParams
var DeleteWebScanRuleCustomAttrJSON string

var DeleteWebScanRuleCmd = &cobra.Command{
	Use:   "delete_web_scan_rule",
	Short: "删除 Web 自定义路径",
	Long:  `删除 Web 自定义路径`,
	Run: func(cmd *cobra.Command, args []string) {
		if DeleteWebScanRuleCustomAttrJSON != "" {
			if err := json.Unmarshal([]byte(DeleteWebScanRuleCustomAttrJSON), &deleteWebScanRuleParams.CustomAttr); err != nil {
				cmd.PrintErrln("Error parsing custom-attr:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "AssetConfigService.DeleteWebScanRule", deleteWebScanRuleParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	// custom_attr is complex type []map[string]interface{}, use JSON string
	DeleteWebScanRuleCmd.Flags().StringVar(&DeleteWebScanRuleCustomAttrJSON, "custom-attr", "", "主机业务属性 (JSON, e.g. [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}])")
	DeleteWebScanRuleCmd.Flags().BoolVar(&deleteWebScanRuleParams.Enable, "enable", false, "是否启用")
	DeleteWebScanRuleCmd.Flags().StringSliceVar(&deleteWebScanRuleParams.HostComment, "host-comment", nil, "主机备注")
	DeleteWebScanRuleCmd.Flags().Float64SliceVar(&deleteWebScanRuleParams.HostId, "host-id", nil, "主机ID")
	DeleteWebScanRuleCmd.Flags().StringSliceVar(&deleteWebScanRuleParams.HostIp, "host-ip", nil, "主机IP")
	DeleteWebScanRuleCmd.Flags().StringSliceVar(&deleteWebScanRuleParams.HostName, "host-name", nil, "主机名称")
	DeleteWebScanRuleCmd.Flags().StringSliceVar(&deleteWebScanRuleParams.HostState, "host-state", nil, "主机状态")
	DeleteWebScanRuleCmd.Flags().StringSliceVar(&deleteWebScanRuleParams.HostTag, "host-tag", nil, "主机标签")
	DeleteWebScanRuleCmd.Flags().StringSliceVar(&deleteWebScanRuleParams.Id, "id", nil, "规则 ID")
	DeleteWebScanRuleCmd.Flags().StringSliceVar(&deleteWebScanRuleParams.Path, "path", nil, "Web 路径")
	DeleteWebScanRuleCmd.Flags().StringSliceVar(&deleteWebScanRuleParams.RuleName, "rule-name", nil, "规则名称")
}

// DeleteWebScanRuleParams 请求参数
type DeleteWebScanRuleParams struct {
	CustomAttr  []map[string]interface{} `json:"custom_attr"`  // 主机业务属性
	Enable      bool                     `json:"enable"`       // 是否启用
	HostComment []string                 `json:"host_comment"` // 主机备注
	HostId      []float64                `json:"host_id"`      // 主机ID
	HostIp      []string                 `json:"host_ip"`      // 主机IP
	HostName    []string                 `json:"host_name"`    // 主机名称
	HostState   []string                 `json:"host_state"`   // 主机状态
	HostTag     []string                 `json:"host_tag"`     // 主机标签
	Id          []string                 `json:"id"`           // 规则 ID
	Path        []string                 `json:"path"`         // Web 路径
	RuleName    []string                 `json:"rule_name"`    // 规则名称
}
