// Code generated by workspace-cli-generator. DO NOT EDIT.

package revshell_event

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getWhitelistParams GetWhitelistParams
var GetWhitelistCustomAttrJSON string

var GetWhitelistCmd = &cobra.Command{
	Use:   "get_whitelist",
	Short: "获取白名单规则",
	Long:  `获取白名单规则`,
	Run: func(cmd *cobra.Command, args []string) {
		if GetWhitelistCustomAttrJSON != "" {
			if err := json.Unmarshal([]byte(GetWhitelistCustomAttrJSON), &getWhitelistParams.CustomAttr); err != nil {
				cmd.PrintErrln("Error parsing custom-attr:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "RevshellEventService.GetWhitelist", getWhitelistParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	GetWhitelistCmd.Flags().Float64SliceVar(&getWhitelistParams.AggHostId, "agg-host-id", nil, "主机id")
	GetWhitelistCmd.Flags().Float64SliceVar(&getWhitelistParams.AggId, "agg-id", nil, "事件id")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.AggRemoteAddress, "agg-remote-address", nil, "远程地址")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.Comment, "comment", nil, "用户自定义备注")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.CreatedAt, "created-at", nil, "事件发现时间")
	// custom_attr is complex type []map[string]interface{}, use JSON string
	GetWhitelistCmd.Flags().StringVar(&GetWhitelistCustomAttrJSON, "custom-attr", "", "主机业务属性 (JSON, e.g. [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}])")
	GetWhitelistCmd.Flags().Float64SliceVar(&getWhitelistParams.Gids, "gids", nil, "gids")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.HostComment, "host-comment", nil, "主机备注")
	GetWhitelistCmd.Flags().Float64SliceVar(&getWhitelistParams.HostId, "host-id", nil, "主机 ID")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.HostIp, "host-ip", nil, "主机 IP")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.HostName, "host-name", nil, "主机名称")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.HostState, "host-state", nil, "主机状态")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.HostTags, "host-tags", nil, "主机标签")
	GetWhitelistCmd.Flags().Float64SliceVar(&getWhitelistParams.Ids, "ids", nil, "事件 ID")
	GetWhitelistCmd.Flags().IntSliceVar(&getWhitelistParams.Level, "level", nil, "事件等级(1-低危，2-中危，3-高危，4-严重)")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.LocalAddr, "local-addr", nil, "本地 IP")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.LocationCode, "location-code", nil, "location_code")
	GetWhitelistCmd.Flags().Float64SliceVar(&getWhitelistParams.Oid, "oid", nil, "机构 ID")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.ParentCmdline, "parent-cmdline", nil, "父 Shell 命令行")
	GetWhitelistCmd.Flags().Float64SliceVar(&getWhitelistParams.ParentPid, "parent-pid", nil, "父进程 ID")
	GetWhitelistCmd.Flags().Float64SliceVar(&getWhitelistParams.Pid, "pid", nil, "进程 ID")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.RemoteAddr, "remote-addr", nil, "远程 IP")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.RemoteAddrType, "remote-addr-type", nil, "远程IP类型，intranet(内网)、internet(外网)")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.ShellCmdline, "shell-cmdline", nil, "Shell 命令行")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.StartTime, "start-time", nil, "Shell 开始时间")
	GetWhitelistCmd.Flags().Float64SliceVar(&getWhitelistParams.StatEventId, "stat-event-id", nil, "事件统计 ID")
	GetWhitelistCmd.Flags().IntSliceVar(&getWhitelistParams.State, "state", nil, "事件状态(1-有风险，2-已忽略，3-已处理)")
	GetWhitelistCmd.Flags().StringSliceVar(&getWhitelistParams.WhiteRuleId, "white-rule-id", nil, "白名单规则 ID")
}

// GetWhitelistParams 请求参数
type GetWhitelistParams struct {
	AggHostId        []float64                `json:"agg_host_id"`        // 主机id
	AggId            []float64                `json:"agg_id"`             // 事件id
	AggRemoteAddress []string                 `json:"agg_remote_address"` // 远程地址
	Comment          []string                 `json:"comment"`            // 用户自定义备注
	CreatedAt        []string                 `json:"created_at"`         // 事件发现时间
	CustomAttr       []map[string]interface{} `json:"custom_attr"`        // 主机业务属性
	Gids             []float64                `json:"gids"`               // gids
	HostComment      []string                 `json:"host_comment"`       // 主机备注
	HostId           []float64                `json:"host_id"`            // 主机 ID
	HostIp           []string                 `json:"host_ip"`            // 主机 IP
	HostName         []string                 `json:"host_name"`          // 主机名称
	HostState        []string                 `json:"host_state"`         // 主机状态
	HostTags         []string                 `json:"host_tags"`          // 主机标签
	Ids              []float64                `json:"ids"`                // 事件 ID
	Level            []int                    `json:"level"`              // 事件等级(1-低危，2-中危，3-高危，4-严重)
	LocalAddr        []string                 `json:"local_addr"`         // 本地 IP
	LocationCode     []string                 `json:"location_code"`      // location_code
	Oid              []float64                `json:"oid"`                // 机构 ID
	ParentCmdline    []string                 `json:"parent_cmdline"`     // 父 Shell 命令行
	ParentPid        []float64                `json:"parent_pid"`         // 父进程 ID
	Pid              []float64                `json:"pid"`                // 进程 ID
	RemoteAddr       []string                 `json:"remote_addr"`        // 远程 IP
	RemoteAddrType   []string                 `json:"remote_addr_type"`   // 远程IP类型，intranet(内网)、internet(外网)
	ShellCmdline     []string                 `json:"shell_cmdline"`      // Shell 命令行
	StartTime        []string                 `json:"start_time"`         // Shell 开始时间
	StatEventId      []float64                `json:"stat_event_id"`      // 事件统计 ID
	State            []int                    `json:"state"`              // 事件状态(1-有风险，2-已忽略，3-已处理)
	WhiteRuleId      []string                 `json:"white_rule_id"`      // 白名单规则 ID
}
