// Code generated by workspace-cli-generator. DO NOT EDIT.

package revshell_event

import (
	"github.com/spf13/cobra"
)

var RevshellEventCmd = &cobra.Command{
	Use:   "revshell_event",
	Short: "反弹 Shell 事件",
	Long:  `反弹 Shell 事件相关操作`,
}

func init() {
	RevshellEventCmd.AddCommand(CreateWhitelistCmd)
	RevshellEventCmd.AddCommand(DeleteEventCmd)
	RevshellEventCmd.AddCommand(EditEventCommentCmd)
	RevshellEventCmd.AddCommand(EditEventStateCmd)
	RevshellEventCmd.AddCommand(GenerateEventFirewallRuleCmd)
	RevshellEventCmd.AddCommand(GetEventCmd)
	RevshellEventCmd.AddCommand(GetEventByHostListCmd)
	RevshellEventCmd.AddCommand(GetEventByRemoteAddrListCmd)
	RevshellEventCmd.AddCommand(GetEventListCmd)
	RevshellEventCmd.AddCommand(GetWhitelistCmd)
	RevshellEventCmd.AddCommand(MarkAsReadCmd)
	RevshellEventCmd.AddCommand(ProcessKillCmd)
	RevshellEventCmd.AddCommand(StatEventByAssetCmd)
	RevshellEventCmd.AddCommand(StatEventByCmdlineCmd)
	RevshellEventCmd.AddCommand(StatEventByRemoteAddrCmd)
	RevshellEventCmd.AddCommand(StatEventByStateCmd)
	RevshellEventCmd.AddCommand(StatEventByTimeCmd)
	RevshellEventCmd.AddCommand(StatEventByUnameCmd)
}
