// Code generated by workspace-cli-generator. DO NOT EDIT.

package network_audit_event

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getEventListByProcessNameParams GetEventListByProcessNameParams
var GetEventListByProcessNameCustomAttrJSON string
var GetEventListByProcessNameOrderByJSON string
var GetEventListByProcessNameSelectJSON string

var GetEventListByProcessNameCmd = &cobra.Command{
	Use:   "get_event_list_by_process_name",
	Short: "获取按进程名聚合的事件列表",
	Long:  `获取按进程名聚合的事件列表`,
	Run: func(cmd *cobra.Command, args []string) {
		if GetEventListByProcessNameCustomAttrJSON != "" {
			if err := json.Unmarshal([]byte(GetEventListByProcessNameCustomAttrJSON), &getEventListByProcessNameParams.CustomAttr); err != nil {
				cmd.PrintErrln("Error parsing custom-attr:", err)
				return
			}
		}
		if GetEventListByProcessNameOrderByJSON != "" {
			if err := json.Unmarshal([]byte(GetEventListByProcessNameOrderByJSON), &getEventListByProcessNameParams.OrderBy); err != nil {
				cmd.PrintErrln("Error parsing order-by:", err)
				return
			}
		}
		if GetEventListByProcessNameSelectJSON != "" {
			if err := json.Unmarshal([]byte(GetEventListByProcessNameSelectJSON), &getEventListByProcessNameParams.Select); err != nil {
				cmd.PrintErrln("Error parsing select:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "NetworkAuditEventService.GetEventListByProcessName", getEventListByProcessNameParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.Cmdline, "cmdline", nil, "命令行")
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.Comment, "comment", nil, "用户自定义备注")
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.ContainerId, "container-id", nil, "容器id")
	GetEventListByProcessNameCmd.Flags().IntVar(&getEventListByProcessNameParams.Count, "count", 20, "每页记录数量, 默认为 20")
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.CreatedAt, "created-at", nil, "发现时间")
	// custom_attr is complex type []map[string]interface{}, use JSON string
	GetEventListByProcessNameCmd.Flags().StringVar(&GetEventListByProcessNameCustomAttrJSON, "custom-attr", "", "主机业务属性 (JSON, e.g. [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}])")
	GetEventListByProcessNameCmd.Flags().Float64SliceVar(&getEventListByProcessNameParams.Gids, "gids", nil, "业务组 ID")
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.GroupName, "group-name", nil, "业务组名")
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.HostComment, "host-comment", nil, "主机备注")
	GetEventListByProcessNameCmd.Flags().Float64SliceVar(&getEventListByProcessNameParams.HostId, "host-id", nil, "主机 ID")
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.HostIp, "host-ip", nil, "主机 IP")
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.HostName, "host-name", nil, "主机名称")
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.HostState, "host-state", nil, "主机状态")
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.HostTags, "host-tags", nil, "主机标签")
	GetEventListByProcessNameCmd.Flags().IntSliceVar(&getEventListByProcessNameParams.Level, "level", nil, "事件等级(1-低危，2-中危，3-高危，4-严重)")
	GetEventListByProcessNameCmd.Flags().IntVar(&getEventListByProcessNameParams.Offset, "offset", 0, "页偏移, 默认为 0")
	GetEventListByProcessNameCmd.Flags().Float64SliceVar(&getEventListByProcessNameParams.Oid, "oid", nil, "机构 ID")
	// order_by is object type, use JSON string
	GetEventListByProcessNameCmd.Flags().StringVar(&GetEventListByProcessNameOrderByJSON, "order-by", "", "排序规则 (JSON, e.g. {\"column\": \"level\", \"order\": \"ASC\"})")
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.ProcessName, "process-name", nil, "进程名")
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.RemoteAddrType, "remote-addr-type", nil, "远程IP类型，intranet(内网)、internet(外网)")
	// select is complex type []map[string]interface{}, use JSON string
	GetEventListByProcessNameCmd.Flags().StringVar(&GetEventListByProcessNameSelectJSON, "select", "", "select (JSON, e.g. [{\"host_id\": 151, \"id\": 151, \"process_name\": \"AliSecureCheckAdvanced.exe\", \"target\": \"119.96.137.252\"}])")
	GetEventListByProcessNameCmd.Flags().BoolVar(&getEventListByProcessNameParams.SelectAll, "select-all", false, "选择所有事件")
	GetEventListByProcessNameCmd.Flags().Float64SliceVar(&getEventListByProcessNameParams.StatEventId, "stat-event-id", nil, "事件统计 ID")
	GetEventListByProcessNameCmd.Flags().IntSliceVar(&getEventListByProcessNameParams.State, "state", nil, "事件状态(1-有风险，2-已忽略，3-已处理)")
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.Target, "target", nil, "目标地址")
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.Type, "type", nil, "网络异常类型")
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.UpdatedAt, "updated-at", nil, "更新时间")
	GetEventListByProcessNameCmd.Flags().StringSliceVar(&getEventListByProcessNameParams.WhiteRuleId, "white-rule-id", nil, "白名单规则 ID")
}

// GetEventListByProcessNameParams 请求参数
type GetEventListByProcessNameParams struct {
	Cmdline        []string                 `json:"cmdline"`          // 命令行
	Comment        []string                 `json:"comment"`          // 用户自定义备注
	ContainerId    []string                 `json:"container_id"`     // 容器id
	Count          int                      `json:"count"`            // 每页记录数量, 默认为 20
	CreatedAt      []string                 `json:"created_at"`       // 发现时间
	CustomAttr     []map[string]interface{} `json:"custom_attr"`      // 主机业务属性
	Gids           []float64                `json:"gids"`             // 业务组 ID
	GroupName      []string                 `json:"group_name"`       // 业务组名
	HostComment    []string                 `json:"host_comment"`     // 主机备注
	HostId         []float64                `json:"host_id"`          // 主机 ID
	HostIp         []string                 `json:"host_ip"`          // 主机 IP
	HostName       []string                 `json:"host_name"`        // 主机名称
	HostState      []string                 `json:"host_state"`       // 主机状态
	HostTags       []string                 `json:"host_tags"`        // 主机标签
	Level          []int                    `json:"level"`            // 事件等级(1-低危，2-中危，3-高危，4-严重)
	Offset         int                      `json:"offset"`           // 页偏移, 默认为 0
	Oid            []float64                `json:"oid"`              // 机构 ID
	OrderBy        map[string]interface{}   `json:"order_by"`         // 排序规则
	ProcessName    []string                 `json:"process_name"`     // 进程名
	RemoteAddrType []string                 `json:"remote_addr_type"` // 远程IP类型，intranet(内网)、internet(外网)
	Select         []map[string]interface{} `json:"select"`           // select
	SelectAll      bool                     `json:"select_all"`       // 选择所有事件
	StatEventId    []float64                `json:"stat_event_id"`    // 事件统计 ID
	State          []int                    `json:"state"`            // 事件状态(1-有风险，2-已忽略，3-已处理)
	Target         []string                 `json:"target"`           // 目标地址
	Type           []string                 `json:"type"`             // 网络异常类型
	UpdatedAt      []string                 `json:"updated_at"`       // 更新时间
	WhiteRuleId    []string                 `json:"white_rule_id"`    // 白名单规则 ID
}
