// Code generated by workspace-cli-generator. DO NOT EDIT.

package network_audit_event

import (
	"github.com/spf13/cobra"
)

var NetworkAuditEventCmd = &cobra.Command{
	Use:   "network_audit_event",
	Short: "网络异常事件",
	Long:  `网络异常事件相关操作`,
}

func init() {
	NetworkAuditEventCmd.AddCommand(CreateWhitelistCmd)
	NetworkAuditEventCmd.AddCommand(DeleteEventCmd)
	NetworkAuditEventCmd.AddCommand(EditEventCommentCmd)
	NetworkAuditEventCmd.AddCommand(EditEventStateCmd)
	NetworkAuditEventCmd.AddCommand(GetEventCmd)
	NetworkAuditEventCmd.AddCommand(GetEventListCmd)
	NetworkAuditEventCmd.AddCommand(GetEventListByHostCmd)
	NetworkAuditEventCmd.AddCommand(GetEventListByProcessNameCmd)
	NetworkAuditEventCmd.AddCommand(GetEventListByTargetCmd)
	NetworkAuditEventCmd.AddCommand(GetWhitelistCmd)
	NetworkAuditEventCmd.AddCommand(MarkAsReadCmd)
	NetworkAuditEventCmd.AddCommand(ProcessKillCmd)
	NetworkAuditEventCmd.AddCommand(StatEventByHostCmd)
	NetworkAuditEventCmd.AddCommand(StatEventByLevelStateCmd)
	NetworkAuditEventCmd.AddCommand(StatEventByProcessNameCmd)
	NetworkAuditEventCmd.AddCommand(StatEventByTargetCmd)
	NetworkAuditEventCmd.AddCommand(StatEventByTimeStateCmd)
	NetworkAuditEventCmd.AddCommand(StatEventByTypeCmd)
}
