// Code generated by workspace-cli-generator. DO NOT EDIT.

package weak_passwd

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var deleteParams DeleteParams
var DeleteCustomAttrJSON string
var DeleteFilterJSON string

var DeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "删除弱口令事件",
	Long:  `删除弱口令事件`,
	Run: func(cmd *cobra.Command, args []string) {
		if DeleteCustomAttrJSON != "" {
			if err := json.Unmarshal([]byte(DeleteCustomAttrJSON), &deleteParams.CustomAttr); err != nil {
				cmd.PrintErrln("Error parsing custom-attr:", err)
				return
			}
		}
		if DeleteFilterJSON != "" {
			if err := json.Unmarshal([]byte(DeleteFilterJSON), &deleteParams.Filter); err != nil {
				cmd.PrintErrln("Error parsing filter:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "WeakPasswdService.Delete", deleteParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	DeleteCmd.Flags().Float64Var(&deleteParams.Accessible, "accessible", 0, "是否可外部访问,1代表不可外部访问 2代表可以外部风闻")
	DeleteCmd.Flags().BoolSliceVar(&deleteParams.CanLogin, "can-login", nil, "是否可登录，true代表可登录，false代表不可登录")
	DeleteCmd.Flags().StringSliceVar(&deleteParams.Comment, "comment", nil, "用户自定义备注")
	DeleteCmd.Flags().StringSliceVar(&deleteParams.CreatedAt, "created-at", nil, "创建事件")
	// custom_attr is complex type []map[string]interface{}, use JSON string
	DeleteCmd.Flags().StringVar(&DeleteCustomAttrJSON, "custom-attr", "", "主机业务属性 (JSON, e.g. [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}])")
	// filter is complex type []map[string]interface{}, use JSON string
	DeleteCmd.Flags().StringVar(&DeleteFilterJSON, "filter", "", "聚合筛选 (JSON, e.g. [{\"host_id\": 3643, \"id\": 3643, \"password\": \"123456\", \"service\": \"ssh\", \"username\": \"test\"}])")
	DeleteCmd.Flags().Float64SliceVar(&deleteParams.Gids, "gids", nil, "业务组 ID 列表")
	DeleteCmd.Flags().StringSliceVar(&deleteParams.HostComment, "host-comment", nil, "主机备注")
	DeleteCmd.Flags().Float64SliceVar(&deleteParams.HostId, "host-id", nil, "主机 ID")
	DeleteCmd.Flags().StringSliceVar(&deleteParams.HostIp, "host-ip", nil, "主机 IP")
	DeleteCmd.Flags().StringSliceVar(&deleteParams.HostName, "host-name", nil, "主机名称")
	DeleteCmd.Flags().StringSliceVar(&deleteParams.HostState, "host-state", nil, "主机状态")
	DeleteCmd.Flags().StringSliceVar(&deleteParams.HostTags, "host-tags", nil, "主机标签")
	DeleteCmd.Flags().Float64SliceVar(&deleteParams.Id, "id", nil, "ID 用来在任务完成后按id筛选")
	DeleteCmd.Flags().IntSliceVar(&deleteParams.Level, "level", nil, "事件等级(1-低危，2-中危，3-高危，4-严重)")
	DeleteCmd.Flags().Float64SliceVar(&deleteParams.Oid, "oid", nil, "机构 ID")
	DeleteCmd.Flags().StringSliceVar(&deleteParams.Password, "password", nil, "密码")
	DeleteCmd.Flags().BoolVar(&deleteParams.SelectAll, "select-all", false, "是否全选")
	DeleteCmd.Flags().StringSliceVar(&deleteParams.Service, "service", nil, "服务")
	DeleteCmd.Flags().StringSliceVar(&deleteParams.ServicePath, "service-path", nil, "服务路径地址")
	DeleteCmd.Flags().StringSliceVar(&deleteParams.ServiceVersion, "service-version", nil, "服务版本")
	DeleteCmd.Flags().IntSliceVar(&deleteParams.State, "state", nil, "事件状态(1-有风险，2-已忽略，3-已处理)")
	DeleteCmd.Flags().StringSliceVar(&deleteParams.Type, "type", nil, "弱口令类型,too_short代表密码长度小于7位,empty代表空口令,is_username代表密码与用户名相同,like_username代表密码中包含用户名,number_only代表纯数字密码,空代表其他")
	DeleteCmd.Flags().StringSliceVar(&deleteParams.UpdatedAt, "updated-at", nil, "最后发现时间")
	DeleteCmd.Flags().StringSliceVar(&deleteParams.Username, "username", nil, "用户名")
	DeleteCmd.Flags().StringSliceVar(&deleteParams.WhiteRuleId, "white-rule-id", nil, "白名单规则 ID")
}

// DeleteParams 请求参数
type DeleteParams struct {
	Accessible     float64                  `json:"accessible"`      // 是否可外部访问,1代表不可外部访问 2代表可以外部风闻
	CanLogin       []bool                   `json:"can_login"`       // 是否可登录，true代表可登录，false代表不可登录
	Comment        []string                 `json:"comment"`         // 用户自定义备注
	CreatedAt      []string                 `json:"created_at"`      // 创建事件
	CustomAttr     []map[string]interface{} `json:"custom_attr"`     // 主机业务属性
	Filter         []map[string]interface{} `json:"filter"`          // 聚合筛选
	Gids           []float64                `json:"gids"`            // 业务组 ID 列表
	HostComment    []string                 `json:"host_comment"`    // 主机备注
	HostId         []float64                `json:"host_id"`         // 主机 ID
	HostIp         []string                 `json:"host_ip"`         // 主机 IP
	HostName       []string                 `json:"host_name"`       // 主机名称
	HostState      []string                 `json:"host_state"`      // 主机状态
	HostTags       []string                 `json:"host_tags"`       // 主机标签
	Id             []float64                `json:"id"`              // ID 用来在任务完成后按id筛选
	Level          []int                    `json:"level"`           // 事件等级(1-低危，2-中危，3-高危，4-严重)
	Oid            []float64                `json:"oid"`             // 机构 ID
	Password       []string                 `json:"password"`        // 密码
	SelectAll      bool                     `json:"select_all"`      // 是否全选
	Service        []string                 `json:"service"`         // 服务
	ServicePath    []string                 `json:"service_path"`    // 服务路径地址
	ServiceVersion []string                 `json:"service_version"` // 服务版本
	State          []int                    `json:"state"`           // 事件状态(1-有风险，2-已忽略，3-已处理)
	Type           []string                 `json:"type"`            // 弱口令类型,too_short代表密码长度小于7位,empty代表空口令,is_username代表密码与用户名相同,like_username代表密码中包含用户名,number_only代表纯数字密码,空代表其他
	UpdatedAt      []string                 `json:"updated_at"`      // 最后发现时间
	Username       []string                 `json:"username"`        // 用户名
	WhiteRuleId    []string                 `json:"white_rule_id"`   // 白名单规则 ID
}
