// Code generated by workspace-cli-generator. DO NOT EDIT.

package detection_rule

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var setNetworkAuditAdvCfgParams SetNetworkAuditAdvCfgParams
var SetNetworkAuditAdvCfgEngineJSON string

var SetNetworkAuditAdvCfgCmd = &cobra.Command{
	Use:   "set_network_audit_adv_cfg",
	Short: "设置网络异常高级配置",
	Long:  `设置网络异常高级配置`,
	Run: func(cmd *cobra.Command, args []string) {
		if SetNetworkAuditAdvCfgEngineJSON != "" {
			if err := json.Unmarshal([]byte(SetNetworkAuditAdvCfgEngineJSON), &setNetworkAuditAdvCfgParams.Engine); err != nil {
				cmd.PrintErrln("Error parsing engine:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "DetectionRuleService.SetNetworkAuditAdvCfg", setNetworkAuditAdvCfgParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	// engine is object type, use JSON string
	SetNetworkAuditAdvCfgCmd.Flags().StringVar(&SetNetworkAuditAdvCfgEngineJSON, "engine", "", "智能检测引擎 (JSON, e.g. {\"dns_detection\": false, \"ip_detection\": false, \"process_detection\": false})")
}

// SetNetworkAuditAdvCfgParams 请求参数
type SetNetworkAuditAdvCfgParams struct {
	Engine map[string]interface{} `json:"engine"` // 智能检测引擎
}
