// Code generated by workspace-cli-generator. DO NOT EDIT.

package endpoint

import (
	"context"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var ListServerCertCmd = &cobra.Command{
	Use:   "list_server_cert",
	Short: "获取证书列表参数",
	Long:  `获取证书列表参数`,
	Run: func(cmd *cobra.Command, args []string) {

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "EndpointService.ListServerCert", nil, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {

}
