// Code generated by workspace-cli-generator. DO NOT EDIT.

package sensitive_port

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var statEventByStateParams StatEventByStateParams
var StatEventByStateCustomAttrJSON string
var StatEventByStateSelectJSON string

var StatEventByStateCmd = &cobra.Command{
	Use:   "stat_event_by_state",
	Short: "事件状态分布",
	Long:  `事件状态分布`,
	Run: func(cmd *cobra.Command, args []string) {
		if StatEventByStateCustomAttrJSON != "" {
			if err := json.Unmarshal([]byte(StatEventByStateCustomAttrJSON), &statEventByStateParams.CustomAttr); err != nil {
				cmd.PrintErrln("Error parsing custom-attr:", err)
				return
			}
		}
		if StatEventByStateSelectJSON != "" {
			if err := json.Unmarshal([]byte(StatEventByStateSelectJSON), &statEventByStateParams.Select); err != nil {
				cmd.PrintErrln("Error parsing select:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "SensitivePortService.StatEventByState", statEventByStateParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	StatEventByStateCmd.Flags().StringSliceVar(&statEventByStateParams.Cmdline, "cmdline", nil, "命令行")
	StatEventByStateCmd.Flags().StringSliceVar(&statEventByStateParams.Comment, "comment", nil, "用户自定义备注")
	StatEventByStateCmd.Flags().StringSliceVar(&statEventByStateParams.CreatedAt, "created-at", nil, "创建时间")
	// custom_attr is complex type []map[string]interface{}, use JSON string
	StatEventByStateCmd.Flags().StringVar(&StatEventByStateCustomAttrJSON, "custom-attr", "", "主机业务属性 (JSON, e.g. [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}])")
	StatEventByStateCmd.Flags().StringSliceVar(&statEventByStateParams.Exepath, "exepath", nil, "可执行文件路径")
	StatEventByStateCmd.Flags().Float64SliceVar(&statEventByStateParams.Gids, "gids", nil, "业务组 ID 列表")
	StatEventByStateCmd.Flags().StringSliceVar(&statEventByStateParams.HostComment, "host-comment", nil, "主机备注")
	StatEventByStateCmd.Flags().Float64SliceVar(&statEventByStateParams.HostId, "host-id", nil, "主机 ID")
	StatEventByStateCmd.Flags().StringSliceVar(&statEventByStateParams.HostIp, "host-ip", nil, "主机 IP")
	StatEventByStateCmd.Flags().StringSliceVar(&statEventByStateParams.HostName, "host-name", nil, "主机名称")
	StatEventByStateCmd.Flags().StringSliceVar(&statEventByStateParams.HostState, "host-state", nil, "主机状态")
	StatEventByStateCmd.Flags().StringSliceVar(&statEventByStateParams.HostTags, "host-tags", nil, "主机标签")
	StatEventByStateCmd.Flags().StringSliceVar(&statEventByStateParams.Ip, "ip", nil, "IP")
	StatEventByStateCmd.Flags().IntSliceVar(&statEventByStateParams.Level, "level", nil, "事件等级(1-低危，2-中危，3-高危，4-严重)")
	StatEventByStateCmd.Flags().Float64SliceVar(&statEventByStateParams.Oid, "oid", nil, "机构 ID")
	StatEventByStateCmd.Flags().Float64SliceVar(&statEventByStateParams.Pid, "pid", nil, "PID")
	StatEventByStateCmd.Flags().StringSliceVar(&statEventByStateParams.Pname, "pname", nil, "进程名")
	StatEventByStateCmd.Flags().StringSliceVar(&statEventByStateParams.Port, "port", nil, "端口")
	StatEventByStateCmd.Flags().Float64SliceVar(&statEventByStateParams.PortState, "port-state", nil, "端口状态")
	StatEventByStateCmd.Flags().StringSliceVar(&statEventByStateParams.Protocol, "protocol", nil, "协议")
	// select is complex type []map[string]interface{}, use JSON string
	StatEventByStateCmd.Flags().StringVar(&StatEventByStateSelectJSON, "select", "", "select (JSON, e.g. [{\"host_id\": 165, \"id\": 192, \"pname\": \"unknown\", \"port\": 22, \"protocol\": \"tcp\"}])")
	StatEventByStateCmd.Flags().BoolVar(&statEventByStateParams.SelectAll, "select-all", false, "是否全选")
	StatEventByStateCmd.Flags().IntSliceVar(&statEventByStateParams.State, "state", nil, "事件状态(1-有风险，2-已忽略，3-已处理)")
	StatEventByStateCmd.Flags().StringSliceVar(&statEventByStateParams.UpdatedAt, "updated-at", nil, "事件更新时间")
	StatEventByStateCmd.Flags().StringSliceVar(&statEventByStateParams.WhiteRuleId, "white-rule-id", nil, "白名单规则 ID")
}

// StatEventByStateParams 请求参数
type StatEventByStateParams struct {
	Cmdline     []string                 `json:"cmdline"`       // 命令行
	Comment     []string                 `json:"comment"`       // 用户自定义备注
	CreatedAt   []string                 `json:"created_at"`    // 创建时间
	CustomAttr  []map[string]interface{} `json:"custom_attr"`   // 主机业务属性
	Exepath     []string                 `json:"exepath"`       // 可执行文件路径
	Gids        []float64                `json:"gids"`          // 业务组 ID 列表
	HostComment []string                 `json:"host_comment"`  // 主机备注
	HostId      []float64                `json:"host_id"`       // 主机 ID
	HostIp      []string                 `json:"host_ip"`       // 主机 IP
	HostName    []string                 `json:"host_name"`     // 主机名称
	HostState   []string                 `json:"host_state"`    // 主机状态
	HostTags    []string                 `json:"host_tags"`     // 主机标签
	Ip          []string                 `json:"ip"`            // IP
	Level       []int                    `json:"level"`         // 事件等级(1-低危，2-中危，3-高危，4-严重)
	Oid         []float64                `json:"oid"`           // 机构 ID
	Pid         []float64                `json:"pid"`           // PID
	Pname       []string                 `json:"pname"`         // 进程名
	Port        []string                 `json:"port"`          // 端口
	PortState   []float64                `json:"port_state"`    // 端口状态
	Protocol    []string                 `json:"protocol"`      // 协议
	Select      []map[string]interface{} `json:"select"`        // select
	SelectAll   bool                     `json:"select_all"`    // 是否全选
	State       []int                    `json:"state"`         // 事件状态(1-有风险，2-已忽略，3-已处理)
	UpdatedAt   []string                 `json:"updated_at"`    // 事件更新时间
	WhiteRuleId []string                 `json:"white_rule_id"` // 白名单规则 ID
}
