// Code generated by workspace-cli-generator. DO NOT EDIT.

package port_asset

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getPortAssetListParams GetPortAssetListParams
var GetPortAssetListCustomAttrJSON string
var GetPortAssetListFilterJSON string
var GetPortAssetListOrderByJSON string

var GetPortAssetListCmd = &cobra.Command{
	Use:   "get_port_asset_list",
	Short: "获取端口资产列表",
	Long:  `获取端口资产列表`,
	Run: func(cmd *cobra.Command, args []string) {
		if GetPortAssetListCustomAttrJSON != "" {
			if err := json.Unmarshal([]byte(GetPortAssetListCustomAttrJSON), &getPortAssetListParams.CustomAttr); err != nil {
				cmd.PrintErrln("Error parsing custom-attr:", err)
				return
			}
		}
		if GetPortAssetListFilterJSON != "" {
			if err := json.Unmarshal([]byte(GetPortAssetListFilterJSON), &getPortAssetListParams.Filter); err != nil {
				cmd.PrintErrln("Error parsing filter:", err)
				return
			}
		}
		if GetPortAssetListOrderByJSON != "" {
			if err := json.Unmarshal([]byte(GetPortAssetListOrderByJSON), &getPortAssetListParams.OrderBy); err != nil {
				cmd.PrintErrln("Error parsing order-by:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "PortAssetService.GetPortAssetList", getPortAssetListParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	GetPortAssetListCmd.Flags().StringSliceVar(&getPortAssetListParams.Cmd, "cmd", nil, "IP")
	GetPortAssetListCmd.Flags().IntVar(&getPortAssetListParams.Count, "count", 20, "数量")
	// custom_attr is complex type []map[string]interface{}, use JSON string
	GetPortAssetListCmd.Flags().StringVar(&GetPortAssetListCustomAttrJSON, "custom-attr", "", "主机业务属性 (JSON, e.g. [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}])")
	// filter is complex type []map[string]interface{}, use JSON string
	GetPortAssetListCmd.Flags().StringVar(&GetPortAssetListFilterJSON, "filter", "", "filter (JSON, e.g. [{\"cmd\": \"java\", \"id\": 151, \"ip\": \"::\", \"port\": 50002, \"protocol\": \"tcp\"}])")
	GetPortAssetListCmd.Flags().Float64SliceVar(&getPortAssetListParams.Gids, "gids", nil, "gids")
	GetPortAssetListCmd.Flags().StringSliceVar(&getPortAssetListParams.HostComment, "host-comment", nil, "主机备注")
	GetPortAssetListCmd.Flags().Float64SliceVar(&getPortAssetListParams.HostId, "host-id", nil, "主机 ID")
	GetPortAssetListCmd.Flags().StringSliceVar(&getPortAssetListParams.HostIp, "host-ip", nil, "主机 IP")
	GetPortAssetListCmd.Flags().StringSliceVar(&getPortAssetListParams.HostName, "host-name", nil, "主机名称")
	GetPortAssetListCmd.Flags().StringSliceVar(&getPortAssetListParams.HostState, "host-state", nil, "主机状态")
	GetPortAssetListCmd.Flags().StringSliceVar(&getPortAssetListParams.HostTags, "host-tags", nil, "主机标签")
	GetPortAssetListCmd.Flags().StringSliceVar(&getPortAssetListParams.Ip, "ip", nil, "IP")
	GetPortAssetListCmd.Flags().IntVar(&getPortAssetListParams.Offset, "offset", 0, "偏移量")
	GetPortAssetListCmd.Flags().Float64SliceVar(&getPortAssetListParams.Oid, "oid", nil, "机构 ID")
	// order_by is object type, use JSON string
	GetPortAssetListCmd.Flags().StringVar(&GetPortAssetListOrderByJSON, "order-by", "", "排序规则 (JSON, e.g. {\"column\": \"level\", \"order\": \"ASC\"})")
	GetPortAssetListCmd.Flags().Float64SliceVar(&getPortAssetListParams.Pid, "pid", nil, "IP")
	GetPortAssetListCmd.Flags().StringSliceVar(&getPortAssetListParams.Port, "port", nil, "IP")
	GetPortAssetListCmd.Flags().StringSliceVar(&getPortAssetListParams.Protocol, "protocol", nil, "IP")
	GetPortAssetListCmd.Flags().BoolVar(&getPortAssetListParams.SelectAll, "select-all", false, "select_all")
	GetPortAssetListCmd.Flags().BoolVar(&getPortAssetListParams.SingletonPortProcess, "singleton-port-process", false, "单例网络应用")
	GetPortAssetListCmd.Flags().StringSliceVar(&getPortAssetListParams.UpdatedAt, "updated-at", nil, "IP")
	GetPortAssetListCmd.Flags().BoolSliceVar(&getPortAssetListParams.Visibility, "visibility", nil, "true")
}

// GetPortAssetListParams 请求参数
type GetPortAssetListParams struct {
	Cmd                  []string                 `json:"cmd"`                    // IP
	Count                int                      `json:"count"`                  // 数量
	CustomAttr           []map[string]interface{} `json:"custom_attr"`            // 主机业务属性
	Filter               []map[string]interface{} `json:"filter"`                 // filter
	Gids                 []float64                `json:"gids"`                   // gids
	HostComment          []string                 `json:"host_comment"`           // 主机备注
	HostId               []float64                `json:"host_id"`                // 主机 ID
	HostIp               []string                 `json:"host_ip"`                // 主机 IP
	HostName             []string                 `json:"host_name"`              // 主机名称
	HostState            []string                 `json:"host_state"`             // 主机状态
	HostTags             []string                 `json:"host_tags"`              // 主机标签
	Ip                   []string                 `json:"ip"`                     // IP
	Offset               int                      `json:"offset"`                 // 偏移量
	Oid                  []float64                `json:"oid"`                    // 机构 ID
	OrderBy              map[string]interface{}   `json:"order_by"`               // 排序规则
	Pid                  []float64                `json:"pid"`                    // IP
	Port                 []string                 `json:"port"`                   // IP
	Protocol             []string                 `json:"protocol"`               // IP
	SelectAll            bool                     `json:"select_all"`             // select_all
	SingletonPortProcess bool                     `json:"singleton_port_process"` // 单例网络应用
	UpdatedAt            []string                 `json:"updated_at"`             // IP
	Visibility           []bool                   `json:"visibility"`             // true
}
