// Code generated by go-swagger; DO NOT EDIT.

package task_config

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// NewDeleteWhitelistParams creates a new DeleteWhitelistParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteWhitelistParams() *DeleteWhitelistParams {
	return &DeleteWhitelistParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteWhitelistParamsWithTimeout creates a new DeleteWhitelistParams object
// with the ability to set a timeout on a request.
func NewDeleteWhitelistParamsWithTimeout(timeout time.Duration) *DeleteWhitelistParams {
	return &DeleteWhitelistParams{
		timeout: timeout,
	}
}

// NewDeleteWhitelistParamsWithContext creates a new DeleteWhitelistParams object
// with the ability to set a context for a request.
func NewDeleteWhitelistParamsWithContext(ctx context.Context) *DeleteWhitelistParams {
	return &DeleteWhitelistParams{
		Context: ctx,
	}
}

// NewDeleteWhitelistParamsWithHTTPClient creates a new DeleteWhitelistParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteWhitelistParamsWithHTTPClient(client *http.Client) *DeleteWhitelistParams {
	return &DeleteWhitelistParams{
		HTTPClient: client,
	}
}

/*
DeleteWhitelistParams contains all the parameters to send to the API endpoint

	for the delete whitelist operation.

	Typically these are written to a http.Request.
*/
type DeleteWhitelistParams struct {

	// Body.
	Body *models.DeleteItem

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete whitelist params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteWhitelistParams) WithDefaults() *DeleteWhitelistParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete whitelist params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteWhitelistParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete whitelist params
func (o *DeleteWhitelistParams) WithTimeout(timeout time.Duration) *DeleteWhitelistParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete whitelist params
func (o *DeleteWhitelistParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete whitelist params
func (o *DeleteWhitelistParams) WithContext(ctx context.Context) *DeleteWhitelistParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete whitelist params
func (o *DeleteWhitelistParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete whitelist params
func (o *DeleteWhitelistParams) WithHTTPClient(client *http.Client) *DeleteWhitelistParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete whitelist params
func (o *DeleteWhitelistParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete whitelist params
func (o *DeleteWhitelistParams) WithBody(body *models.DeleteItem) *DeleteWhitelistParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete whitelist params
func (o *DeleteWhitelistParams) SetBody(body *models.DeleteItem) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteWhitelistParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
