// Code generated by go-swagger; DO NOT EDIT.

package task_config

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCustomPluginIDParams creates a new GetCustomPluginIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCustomPluginIDParams() *GetCustomPluginIDParams {
	return &GetCustomPluginIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCustomPluginIDParamsWithTimeout creates a new GetCustomPluginIDParams object
// with the ability to set a timeout on a request.
func NewGetCustomPluginIDParamsWithTimeout(timeout time.Duration) *GetCustomPluginIDParams {
	return &GetCustomPluginIDParams{
		timeout: timeout,
	}
}

// NewGetCustomPluginIDParamsWithContext creates a new GetCustomPluginIDParams object
// with the ability to set a context for a request.
func NewGetCustomPluginIDParamsWithContext(ctx context.Context) *GetCustomPluginIDParams {
	return &GetCustomPluginIDParams{
		Context: ctx,
	}
}

// NewGetCustomPluginIDParamsWithHTTPClient creates a new GetCustomPluginIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCustomPluginIDParamsWithHTTPClient(client *http.Client) *GetCustomPluginIDParams {
	return &GetCustomPluginIDParams{
		HTTPClient: client,
	}
}

/*
GetCustomPluginIDParams contains all the parameters to send to the API endpoint

	for the get custom plugin ID operation.

	Typically these are written to a http.Request.
*/
type GetCustomPluginIDParams struct {

	/* ID.

	   要获取的自定义插件的 uuid
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get custom plugin ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomPluginIDParams) WithDefaults() *GetCustomPluginIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get custom plugin ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomPluginIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get custom plugin ID params
func (o *GetCustomPluginIDParams) WithTimeout(timeout time.Duration) *GetCustomPluginIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get custom plugin ID params
func (o *GetCustomPluginIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get custom plugin ID params
func (o *GetCustomPluginIDParams) WithContext(ctx context.Context) *GetCustomPluginIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get custom plugin ID params
func (o *GetCustomPluginIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get custom plugin ID params
func (o *GetCustomPluginIDParams) WithHTTPClient(client *http.Client) *GetCustomPluginIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get custom plugin ID params
func (o *GetCustomPluginIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get custom plugin ID params
func (o *GetCustomPluginIDParams) WithID(id string) *GetCustomPluginIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get custom plugin ID params
func (o *GetCustomPluginIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomPluginIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
