// Code generated by workspace-cli-generator. DO NOT EDIT.

package firewall

import (
	"context"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var generateWhiteRuleParams GenerateWhiteRuleParams

var GenerateWhiteRuleCmd = &cobra.Command{
	Use:   "generate_white_rule",
	Short: "获取白名单配置",
	Long:  `获取白名单配置`,
	Run: func(cmd *cobra.Command, args []string) {

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "FirewallService.GenerateWhiteRule", generateWhiteRuleParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	GenerateWhiteRuleCmd.Flags().IntVar(&generateWhiteRuleParams.Id, "id", 0, "事件 ID")
	GenerateWhiteRuleCmd.MarkFlagRequired("id")
}

// GenerateWhiteRuleParams 请求参数
type GenerateWhiteRuleParams struct {
	Id int `json:"id"` // 事件 ID
}
