// Code generated by go-swagger; DO NOT EDIT.

package plan

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// PostPlanFilterReader is a Reader for the PostPlanFilter structure.
type PostPlanFilterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostPlanFilterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostPlanFilterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /plan/filter] PostPlanFilter", response, response.Code())
	}
}

// NewPostPlanFilterOK creates a PostPlanFilterOK with default headers values
func NewPostPlanFilterOK() *PostPlanFilterOK {
	return &PostPlanFilterOK{}
}

/*
PostPlanFilterOK describes a response with status code 200, with default header values.

Response
*/
type PostPlanFilterOK struct {
	Payload *models.PostPlanFilterOKBody
}

// IsSuccess returns true when this post plan filter o k response has a 2xx status code
func (o *PostPlanFilterOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post plan filter o k response has a 3xx status code
func (o *PostPlanFilterOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post plan filter o k response has a 4xx status code
func (o *PostPlanFilterOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post plan filter o k response has a 5xx status code
func (o *PostPlanFilterOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post plan filter o k response a status code equal to that given
func (o *PostPlanFilterOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post plan filter o k response
func (o *PostPlanFilterOK) Code() int {
	return 200
}

func (o *PostPlanFilterOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /plan/filter][%d] postPlanFilterOK %s", 200, payload)
}

func (o *PostPlanFilterOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /plan/filter][%d] postPlanFilterOK %s", 200, payload)
}

func (o *PostPlanFilterOK) GetPayload() *models.PostPlanFilterOKBody {
	return o.Payload
}

func (o *PostPlanFilterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostPlanFilterOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
