// Code generated by workspace-cli-generator. DO NOT EDIT.

package user_asset

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getWindowsUserListParams GetWindowsUserListParams
var GetWindowsUserListCustomAttrJSON string
var GetWindowsUserListFilterJSON string
var GetWindowsUserListOrderByJSON string

var GetWindowsUserListCmd = &cobra.Command{
	Use:   "get_windows_user_list",
	Short: "获取 windows 用户列表",
	Long:  `获取 windows 用户列表`,
	Run: func(cmd *cobra.Command, args []string) {
		if GetWindowsUserListCustomAttrJSON != "" {
			if err := json.Unmarshal([]byte(GetWindowsUserListCustomAttrJSON), &getWindowsUserListParams.CustomAttr); err != nil {
				cmd.PrintErrln("Error parsing custom-attr:", err)
				return
			}
		}
		if GetWindowsUserListFilterJSON != "" {
			if err := json.Unmarshal([]byte(GetWindowsUserListFilterJSON), &getWindowsUserListParams.Filter); err != nil {
				cmd.PrintErrln("Error parsing filter:", err)
				return
			}
		}
		if GetWindowsUserListOrderByJSON != "" {
			if err := json.Unmarshal([]byte(GetWindowsUserListOrderByJSON), &getWindowsUserListParams.OrderBy); err != nil {
				cmd.PrintErrln("Error parsing order-by:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "UserAssetService.GetWindowsUserList", getWindowsUserListParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	GetWindowsUserListCmd.Flags().IntVar(&getWindowsUserListParams.Count, "count", 20, "数量")
	// custom_attr is complex type []map[string]interface{}, use JSON string
	GetWindowsUserListCmd.Flags().StringVar(&GetWindowsUserListCustomAttrJSON, "custom-attr", "", "主机业务属性 (JSON, e.g. [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}])")
	GetWindowsUserListCmd.Flags().BoolSliceVar(&getWindowsUserListParams.Enabled, "enabled", nil, "是否启用，true代表启用，false代表禁用")
	// filter is complex type []map[string]interface{}, use JSON string
	GetWindowsUserListCmd.Flags().StringVar(&GetWindowsUserListFilterJSON, "filter", "", "已选中的项目 (JSON, e.g. [{\"host_id\": 1, \"id\": 123, \"username\": \"test222\"}])")
	GetWindowsUserListCmd.Flags().Float64SliceVar(&getWindowsUserListParams.Gids, "gids", nil, "业务组")
	GetWindowsUserListCmd.Flags().StringSliceVar(&getWindowsUserListParams.HostComment, "host-comment", nil, "主机备注")
	GetWindowsUserListCmd.Flags().Float64SliceVar(&getWindowsUserListParams.HostId, "host-id", nil, "主机ID, 用于主机详情页面")
	GetWindowsUserListCmd.Flags().StringSliceVar(&getWindowsUserListParams.HostIp, "host-ip", nil, "主机IP")
	GetWindowsUserListCmd.Flags().StringSliceVar(&getWindowsUserListParams.HostName, "host-name", nil, "主机名称")
	GetWindowsUserListCmd.Flags().StringSliceVar(&getWindowsUserListParams.HostState, "host-state", nil, "主机状态")
	GetWindowsUserListCmd.Flags().StringSliceVar(&getWindowsUserListParams.HostTags, "host-tags", nil, "主机标签")
	GetWindowsUserListCmd.Flags().StringSliceVar(&getWindowsUserListParams.LastLogin, "last-login", nil, "上次登录时间")
	GetWindowsUserListCmd.Flags().StringSliceVar(&getWindowsUserListParams.LastLogout, "last-logout", nil, "上次登出时间")
	GetWindowsUserListCmd.Flags().IntVar(&getWindowsUserListParams.Offset, "offset", 0, "偏移量")
	GetWindowsUserListCmd.Flags().Float64SliceVar(&getWindowsUserListParams.Oid, "oid", nil, "机构 ID")
	// order_by is object type, use JSON string
	GetWindowsUserListCmd.Flags().StringVar(&GetWindowsUserListOrderByJSON, "order-by", "", "排序规则 (JSON, e.g. {\"column\": \"level\", \"order\": \"ASC\"})")
	GetWindowsUserListCmd.Flags().StringSliceVar(&getWindowsUserListParams.PasswordModify, "password-modify", nil, "上次修改密码时间")
	GetWindowsUserListCmd.Flags().BoolVar(&getWindowsUserListParams.SelectAll, "select-all", false, "是否选中所有")
	GetWindowsUserListCmd.Flags().Float64SliceVar(&getWindowsUserListParams.Sid, "sid", nil, "SID")
	GetWindowsUserListCmd.Flags().StringSliceVar(&getWindowsUserListParams.UserExpire, "user-expire", nil, "用户失效时间")
	GetWindowsUserListCmd.Flags().StringSliceVar(&getWindowsUserListParams.UserGroup, "user-group", nil, "用户组名")
	GetWindowsUserListCmd.Flags().StringSliceVar(&getWindowsUserListParams.UserType, "user-type", nil, "用户类型")
	GetWindowsUserListCmd.Flags().StringSliceVar(&getWindowsUserListParams.Username, "username", nil, "用户名")
}

// GetWindowsUserListParams 请求参数
type GetWindowsUserListParams struct {
	Count          int                      `json:"count"`           // 数量
	CustomAttr     []map[string]interface{} `json:"custom_attr"`     // 主机业务属性
	Enabled        []bool                   `json:"enabled"`         // 是否启用，true代表启用，false代表禁用
	Filter         []map[string]interface{} `json:"filter"`          // 已选中的项目
	Gids           []float64                `json:"gids"`            // 业务组
	HostComment    []string                 `json:"host_comment"`    // 主机备注
	HostId         []float64                `json:"host_id"`         // 主机ID, 用于主机详情页面
	HostIp         []string                 `json:"host_ip"`         // 主机IP
	HostName       []string                 `json:"host_name"`       // 主机名称
	HostState      []string                 `json:"host_state"`      // 主机状态
	HostTags       []string                 `json:"host_tags"`       // 主机标签
	LastLogin      []string                 `json:"last_login"`      // 上次登录时间
	LastLogout     []string                 `json:"last_logout"`     // 上次登出时间
	Offset         int                      `json:"offset"`          // 偏移量
	Oid            []float64                `json:"oid"`             // 机构 ID
	OrderBy        map[string]interface{}   `json:"order_by"`        // 排序规则
	PasswordModify []string                 `json:"password_modify"` // 上次修改密码时间
	SelectAll      bool                     `json:"select_all"`      // 是否选中所有
	Sid            []float64                `json:"sid"`             // SID
	UserExpire     []string                 `json:"user_expire"`     // 用户失效时间
	UserGroup      []string                 `json:"user_group"`      // 用户组名
	UserType       []string                 `json:"user_type"`       // 用户类型
	Username       []string                 `json:"username"`        // 用户名
}
