// Code generated by workspace-cli-generator. DO NOT EDIT.

package whitelist

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var createWhitelistParams CreateWhitelistParams
var CreateWhitelistRuleJSON string

var CreateWhitelistCmd = &cobra.Command{
	Use:   "create_whitelist",
	Short: "创建事件加白规则",
	Long:  `创建事件加白规则`,
	Run: func(cmd *cobra.Command, args []string) {
		if CreateWhitelistRuleJSON != "" {
			if err := json.Unmarshal([]byte(CreateWhitelistRuleJSON), &createWhitelistParams.Rule); err != nil {
				cmd.PrintErrln("Error parsing rule:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "WhitelistService.CreateWhitelist", createWhitelistParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	CreateWhitelistCmd.Flags().Float64SliceVar(&createWhitelistParams.AgentRange, "agent-range", nil, "主机范围")
	CreateWhitelistCmd.Flags().Float64SliceVar(&createWhitelistParams.BusinessGroupRange, "business-group-range", nil, "业务组范围")
	CreateWhitelistCmd.Flags().BoolVar(&createWhitelistParams.Enable, "enable", false, "是否启用")
	CreateWhitelistCmd.Flags().Float64Var(&createWhitelistParams.EventId, "event-id", 0, "风险事件ID")
	CreateWhitelistCmd.Flags().StringVar(&createWhitelistParams.FilterMethod, "filter-method", "", "过滤方式")
	CreateWhitelistCmd.Flags().BoolVar(&createWhitelistParams.Global, "global", false, "是否绑定全局探针")
	CreateWhitelistCmd.Flags().BoolVar(&createWhitelistParams.NeedDealHistory, "need-deal-history", false, "是否处理历史事件")
	CreateWhitelistCmd.Flags().StringVar(&createWhitelistParams.Remark, "remark", "", "备注")
	// rule is object type, use JSON string
	CreateWhitelistCmd.Flags().StringVar(&CreateWhitelistRuleJSON, "rule", "", "加白规则 (JSON, e.g. {\"abnormal_login\": {\"auth_type\": [\"password\"], \"ip\": [\"10.10.10.10\"], \"location\": [{\"city\": \"...\", \"country\": \"...\", \"province\": \"...\"}], \"time\": [{\"start_time\": \"...\", \"stop_time\": \"...\", \"weekdays\": \"...\"}], \"username\": [\"root\"], \"username_regex\": [\"root\"]}, \"baseline_v2\": {\"baseline_logic_name\": [\"some baseline logic\"], \"baseline_logic_tags\": [\"1\"], \"baseline_set_id\": [\"1\"]}, \"bruteforce\": {\"service\": [\"ssh\"], \"source_ip\": [\"10.10.10.10\"], \"time\": [{\"start_time\": \"...\", \"stop_time\": \"...\", \"weekdays\": \"...\"}], \"username\": [\"root\"], \"username_regex\": [\"root\"]}, \"...\": \"...\"})")
	CreateWhitelistCmd.Flags().StringVar(&createWhitelistParams.RuleName, "rule-name", "", "规则名称")
	CreateWhitelistCmd.Flags().StringVar(&createWhitelistParams.Type, "type", "", "事件类型")
}

// CreateWhitelistParams 请求参数
type CreateWhitelistParams struct {
	AgentRange         []float64              `json:"agent_range"`          // 主机范围
	BusinessGroupRange []float64              `json:"business_group_range"` // 业务组范围
	Enable             bool                   `json:"enable"`               // 是否启用
	EventId            float64                `json:"event_id"`             // 风险事件ID
	FilterMethod       string                 `json:"filter_method"`        // 过滤方式
	Global             bool                   `json:"global"`               // 是否绑定全局探针
	NeedDealHistory    bool                   `json:"need_deal_history"`    // 是否处理历史事件
	Remark             string                 `json:"remark"`               // 备注
	Rule               map[string]interface{} `json:"rule"`                 // 加白规则
	RuleName           string                 `json:"rule_name"`            // 规则名称
	Type               string                 `json:"type"`                 // 事件类型
}
