// Code generated by go-swagger; DO NOT EDIT.

package domain_asset

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// GetDomainIDReader is a Reader for the GetDomainID structure.
type GetDomainIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDomainIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetDomainIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /domain/{id}] GetDomainID", response, response.Code())
	}
}

// NewGetDomainIDOK creates a GetDomainIDOK with default headers values
func NewGetDomainIDOK() *GetDomainIDOK {
	return &GetDomainIDOK{}
}

/*
GetDomainIDOK describes a response with status code 200, with default header values.

Response
*/
type GetDomainIDOK struct {
	Payload *models.GetDomainIDOKBody
}

// IsSuccess returns true when this get domain Id o k response has a 2xx status code
func (o *GetDomainIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get domain Id o k response has a 3xx status code
func (o *GetDomainIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get domain Id o k response has a 4xx status code
func (o *GetDomainIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get domain Id o k response has a 5xx status code
func (o *GetDomainIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get domain Id o k response a status code equal to that given
func (o *GetDomainIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get domain Id o k response
func (o *GetDomainIDOK) Code() int {
	return 200
}

func (o *GetDomainIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /domain/{id}][%d] getDomainIdOK %s", 200, payload)
}

func (o *GetDomainIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /domain/{id}][%d] getDomainIdOK %s", 200, payload)
}

func (o *GetDomainIDOK) GetPayload() *models.GetDomainIDOKBody {
	return o.Payload
}

func (o *GetDomainIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetDomainIDOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
