// Code generated by go-swagger; DO NOT EDIT.

package user

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// NewPostUserIDParams creates a new PostUserIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostUserIDParams() *PostUserIDParams {
	return &PostUserIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostUserIDParamsWithTimeout creates a new PostUserIDParams object
// with the ability to set a timeout on a request.
func NewPostUserIDParamsWithTimeout(timeout time.Duration) *PostUserIDParams {
	return &PostUserIDParams{
		timeout: timeout,
	}
}

// NewPostUserIDParamsWithContext creates a new PostUserIDParams object
// with the ability to set a context for a request.
func NewPostUserIDParamsWithContext(ctx context.Context) *PostUserIDParams {
	return &PostUserIDParams{
		Context: ctx,
	}
}

// NewPostUserIDParamsWithHTTPClient creates a new PostUserIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostUserIDParamsWithHTTPClient(client *http.Client) *PostUserIDParams {
	return &PostUserIDParams{
		HTTPClient: client,
	}
}

/*
PostUserIDParams contains all the parameters to send to the API endpoint

	for the post user ID operation.

	Typically these are written to a http.Request.
*/
type PostUserIDParams struct {

	// Body.
	Body *models.UserUpdateBody

	/* ID.

	   要修改的用户 ID
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post user ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUserIDParams) WithDefaults() *PostUserIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post user ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUserIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post user ID params
func (o *PostUserIDParams) WithTimeout(timeout time.Duration) *PostUserIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post user ID params
func (o *PostUserIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post user ID params
func (o *PostUserIDParams) WithContext(ctx context.Context) *PostUserIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post user ID params
func (o *PostUserIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post user ID params
func (o *PostUserIDParams) WithHTTPClient(client *http.Client) *PostUserIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post user ID params
func (o *PostUserIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post user ID params
func (o *PostUserIDParams) WithBody(body *models.UserUpdateBody) *PostUserIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post user ID params
func (o *PostUserIDParams) SetBody(body *models.UserUpdateBody) {
	o.Body = body
}

// WithID adds the id to the post user ID params
func (o *PostUserIDParams) WithID(id int64) *PostUserIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post user ID params
func (o *PostUserIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostUserIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
