// Code generated by workspace-cli-generator. DO NOT EDIT.

package brute_force

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var deleteEventParams DeleteEventParams
var DeleteEventCustomAttrJSON string

var DeleteEventCmd = &cobra.Command{
	Use:   "delete_event",
	Short: "删除所选的事件",
	Long:  `删除所选的事件`,
	Run: func(cmd *cobra.Command, args []string) {
		if DeleteEventCustomAttrJSON != "" {
			if err := json.Unmarshal([]byte(DeleteEventCustomAttrJSON), &deleteEventParams.CustomAttr); err != nil {
				cmd.PrintErrln("Error parsing custom-attr:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "BruteForceService.DeleteEvent", deleteEventParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.AuthMethod, "auth-method", nil, "auth_method")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.Category, "category", nil, "爆破类型")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.Comment, "comment", nil, "comment")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.CreatedAt, "created-at", nil, "爆破开始时间")
	// custom_attr is complex type []map[string]interface{}, use JSON string
	DeleteEventCmd.Flags().StringVar(&DeleteEventCustomAttrJSON, "custom-attr", "", "主机业务属性 (JSON, e.g. [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}])")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.Description, "description", nil, "爆破描述")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.FailureCount, "failure-count", nil, "failure_count")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.FinishedAt, "finished-at", nil, "finished_at")
	DeleteEventCmd.Flags().Float64SliceVar(&deleteEventParams.Gids, "gids", nil, "gids")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.HostComment, "host-comment", nil, "主机备注")
	DeleteEventCmd.Flags().Float64SliceVar(&deleteEventParams.HostId, "host-id", nil, "主机 ID")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.HostIp, "host-ip", nil, "主机 IP")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.HostName, "host-name", nil, "主机名称")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.HostState, "host-state", nil, "主机状态")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.HostTags, "host-tags", nil, "主机标签")
	DeleteEventCmd.Flags().Float64SliceVar(&deleteEventParams.Ids, "ids", nil, "事件 ID")
	DeleteEventCmd.Flags().IntSliceVar(&deleteEventParams.Level, "level", nil, "风险等级(1-低危，2-中危，3-高危，4-严重)")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.LocationCode, "location-code", nil, "location_code")
	DeleteEventCmd.Flags().Float64SliceVar(&deleteEventParams.Oid, "oid", nil, "机构 ID")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.RemoteAddrType, "remote-addr-type", nil, "远程IP类型，intranet(内网)、internet(外网)")
	DeleteEventCmd.Flags().BoolVar(&deleteEventParams.SelectAll, "select-all", false, "是否选中所有")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.SourceIp, "source-ip", nil, "source_ip")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.StartedAt, "started-at", nil, "started_at")
	DeleteEventCmd.Flags().Float64SliceVar(&deleteEventParams.StatEventId, "stat-event-id", nil, "事件统计 ID")
	DeleteEventCmd.Flags().IntSliceVar(&deleteEventParams.State, "state", nil, "处置状态(1-有风险，2-已忽略，3-已处理)")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.SuccessCount, "success-count", nil, "success_count")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.UserName, "user-name", nil, "user_name")
	DeleteEventCmd.Flags().StringSliceVar(&deleteEventParams.WhiteRuleId, "white-rule-id", nil, "白名单规则 ID")
}

// DeleteEventParams 请求参数
type DeleteEventParams struct {
	AuthMethod     []string                 `json:"auth_method"`      // auth_method
	Category       []string                 `json:"category"`         // 爆破类型
	Comment        []string                 `json:"comment"`          // comment
	CreatedAt      []string                 `json:"created_at"`       // 爆破开始时间
	CustomAttr     []map[string]interface{} `json:"custom_attr"`      // 主机业务属性
	Description    []string                 `json:"description"`      // 爆破描述
	FailureCount   []string                 `json:"failure_count"`    // failure_count
	FinishedAt     []string                 `json:"finished_at"`      // finished_at
	Gids           []float64                `json:"gids"`             // gids
	HostComment    []string                 `json:"host_comment"`     // 主机备注
	HostId         []float64                `json:"host_id"`          // 主机 ID
	HostIp         []string                 `json:"host_ip"`          // 主机 IP
	HostName       []string                 `json:"host_name"`        // 主机名称
	HostState      []string                 `json:"host_state"`       // 主机状态
	HostTags       []string                 `json:"host_tags"`        // 主机标签
	Ids            []float64                `json:"ids"`              // 事件 ID
	Level          []int                    `json:"level"`            // 风险等级(1-低危，2-中危，3-高危，4-严重)
	LocationCode   []string                 `json:"location_code"`    // location_code
	Oid            []float64                `json:"oid"`              // 机构 ID
	RemoteAddrType []string                 `json:"remote_addr_type"` // 远程IP类型，intranet(内网)、internet(外网)
	SelectAll      bool                     `json:"select_all"`       // 是否选中所有
	SourceIp       []string                 `json:"source_ip"`        // source_ip
	StartedAt      []string                 `json:"started_at"`       // started_at
	StatEventId    []float64                `json:"stat_event_id"`    // 事件统计 ID
	State          []int                    `json:"state"`            // 处置状态(1-有风险，2-已忽略，3-已处理)
	SuccessCount   []string                 `json:"success_count"`    // success_count
	UserName       []string                 `json:"user_name"`        // user_name
	WhiteRuleId    []string                 `json:"white_rule_id"`    // 白名单规则 ID
}
