// Code generated by go-swagger; DO NOT EDIT.

package audit_log

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAuditlogActionParams creates a new GetAuditlogActionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAuditlogActionParams() *GetAuditlogActionParams {
	return &GetAuditlogActionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuditlogActionParamsWithTimeout creates a new GetAuditlogActionParams object
// with the ability to set a timeout on a request.
func NewGetAuditlogActionParamsWithTimeout(timeout time.Duration) *GetAuditlogActionParams {
	return &GetAuditlogActionParams{
		timeout: timeout,
	}
}

// NewGetAuditlogActionParamsWithContext creates a new GetAuditlogActionParams object
// with the ability to set a context for a request.
func NewGetAuditlogActionParamsWithContext(ctx context.Context) *GetAuditlogActionParams {
	return &GetAuditlogActionParams{
		Context: ctx,
	}
}

// NewGetAuditlogActionParamsWithHTTPClient creates a new GetAuditlogActionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAuditlogActionParamsWithHTTPClient(client *http.Client) *GetAuditlogActionParams {
	return &GetAuditlogActionParams{
		HTTPClient: client,
	}
}

/*
GetAuditlogActionParams contains all the parameters to send to the API endpoint

	for the get auditlog action operation.

	Typically these are written to a http.Request.
*/
type GetAuditlogActionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get auditlog action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuditlogActionParams) WithDefaults() *GetAuditlogActionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get auditlog action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuditlogActionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get auditlog action params
func (o *GetAuditlogActionParams) WithTimeout(timeout time.Duration) *GetAuditlogActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auditlog action params
func (o *GetAuditlogActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auditlog action params
func (o *GetAuditlogActionParams) WithContext(ctx context.Context) *GetAuditlogActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auditlog action params
func (o *GetAuditlogActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auditlog action params
func (o *GetAuditlogActionParams) WithHTTPClient(client *http.Client) *GetAuditlogActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auditlog action params
func (o *GetAuditlogActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuditlogActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
