// Code generated by go-swagger; DO NOT EDIT.

package custom_poc

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/chaitin/workspace-cli/products/xray/models"
)

// PostCustompocReader is a Reader for the PostCustompoc structure.
type PostCustompocReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCustompocReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostCustompocOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /custompoc] PostCustompoc", response, response.Code())
	}
}

// NewPostCustompocOK creates a PostCustompocOK with default headers values
func NewPostCustompocOK() *PostCustompocOK {
	return &PostCustompocOK{}
}

/*
PostCustompocOK describes a response with status code 200, with default header values.

Response
*/
type PostCustompocOK struct {
	Payload *models.PostCustompocOKBody
}

// IsSuccess returns true when this post custompoc o k response has a 2xx status code
func (o *PostCustompocOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post custompoc o k response has a 3xx status code
func (o *PostCustompocOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post custompoc o k response has a 4xx status code
func (o *PostCustompocOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post custompoc o k response has a 5xx status code
func (o *PostCustompocOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post custompoc o k response a status code equal to that given
func (o *PostCustompocOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post custompoc o k response
func (o *PostCustompocOK) Code() int {
	return 200
}

func (o *PostCustompocOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /custompoc][%d] postCustompocOK %s", 200, payload)
}

func (o *PostCustompocOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /custompoc][%d] postCustompocOK %s", 200, payload)
}

func (o *PostCustompocOK) GetPayload() *models.PostCustompocOKBody {
	return o.Payload
}

func (o *PostCustompocOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostCustompocOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
