// Code generated by workspace-cli-generator. DO NOT EDIT.

package suspicious_operation

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getEventListByHostParams GetEventListByHostParams
var GetEventListByHostCustomAttrJSON string
var GetEventListByHostOrderByJSON string

var GetEventListByHostCmd = &cobra.Command{
	Use:   "get_event_list_by_host",
	Short: "返回按 主机 聚合的可疑操作列表",
	Long:  `返回按 主机 聚合的可疑操作列表`,
	Run: func(cmd *cobra.Command, args []string) {
		if GetEventListByHostCustomAttrJSON != "" {
			if err := json.Unmarshal([]byte(GetEventListByHostCustomAttrJSON), &getEventListByHostParams.CustomAttr); err != nil {
				cmd.PrintErrln("Error parsing custom-attr:", err)
				return
			}
		}
		if GetEventListByHostOrderByJSON != "" {
			if err := json.Unmarshal([]byte(GetEventListByHostOrderByJSON), &getEventListByHostParams.OrderBy); err != nil {
				cmd.PrintErrln("Error parsing order-by:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "SuspiciousOperationService.GetEventListByHost", getEventListByHostParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.Comment, "comment", nil, "用户自定义备注")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.ContainerHashId, "container-hash-id", nil, "容器Id")
	GetEventListByHostCmd.Flags().IntVar(&getEventListByHostParams.Count, "count", 20, "数量")
	// custom_attr is complex type []map[string]interface{}, use JSON string
	GetEventListByHostCmd.Flags().StringVar(&GetEventListByHostCustomAttrJSON, "custom-attr", "", "主机业务属性 (JSON, e.g. [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}])")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.Egid, "egid", nil, "有效用户组ID")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.Egname, "egname", nil, "有效用户组名")
	GetEventListByHostCmd.Flags().Float64SliceVar(&getEventListByHostParams.Euid, "euid", nil, "有效用户ID")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.Euname, "euname", nil, "有效用户名")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.Gid, "gid", nil, "用户组ID")
	GetEventListByHostCmd.Flags().Float64SliceVar(&getEventListByHostParams.Gids, "gids", nil, "业务组ID")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.Gname, "gname", nil, "用户组名")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.HostComment, "host-comment", nil, "主机备注")
	GetEventListByHostCmd.Flags().Float64SliceVar(&getEventListByHostParams.HostId, "host-id", nil, "主机ID, 用于主机详情页面")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.HostIp, "host-ip", nil, "主机IP")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.HostName, "host-name", nil, "主机名称")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.HostState, "host-state", nil, "主机状态")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.HostTags, "host-tags", nil, "主机标签")
	GetEventListByHostCmd.Flags().Float64SliceVar(&getEventListByHostParams.Ids, "ids", nil, "事件 ID, 用于事件详情页面")
	GetEventListByHostCmd.Flags().Float64SliceVar(&getEventListByHostParams.Level, "level", nil, "风险等级(1-低危，2-中危，3-高危，4-严重)")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.NetApp, "net-app", nil, "网络应用")
	GetEventListByHostCmd.Flags().IntVar(&getEventListByHostParams.Offset, "offset", 0, "偏移量")
	GetEventListByHostCmd.Flags().Float64SliceVar(&getEventListByHostParams.Oid, "oid", nil, "机构 ID")
	// order_by is object type, use JSON string
	GetEventListByHostCmd.Flags().StringVar(&GetEventListByHostOrderByJSON, "order-by", "", "排序规则 (JSON, e.g. {\"column\": \"level\", \"order\": \"ASC\"})")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.RuleName, "rule-name", nil, "规则名称")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.SessionId, "session-id", nil, "会话ID")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.SshClientIp, "ssh-client-ip", nil, "ssh登陆地址")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.SshUser, "ssh-user", nil, "ssh登录用户")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.StartTime, "start-time", nil, "开始时间")
	GetEventListByHostCmd.Flags().Float64SliceVar(&getEventListByHostParams.StatEventId, "stat-event-id", nil, "事件统计 ID")
	GetEventListByHostCmd.Flags().Float64SliceVar(&getEventListByHostParams.State, "state", nil, "处置状态(1-有风险，2-已忽略，3-已处理)")
	GetEventListByHostCmd.Flags().Float64SliceVar(&getEventListByHostParams.Uid, "uid", nil, "用户ID")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.Uname, "uname", nil, "用户名")
	GetEventListByHostCmd.Flags().StringSliceVar(&getEventListByHostParams.WhiteRuleId, "white-rule-id", nil, "白名单规则 ID")
}

// GetEventListByHostParams 请求参数
type GetEventListByHostParams struct {
	Comment         []string                 `json:"comment"`           // 用户自定义备注
	ContainerHashId []string                 `json:"container_hash_id"` // 容器Id
	Count           int                      `json:"count"`             // 数量
	CustomAttr      []map[string]interface{} `json:"custom_attr"`       // 主机业务属性
	Egid            []string                 `json:"egid"`              // 有效用户组ID
	Egname          []string                 `json:"egname"`            // 有效用户组名
	Euid            []float64                `json:"euid"`              // 有效用户ID
	Euname          []string                 `json:"euname"`            // 有效用户名
	Gid             []string                 `json:"gid"`               // 用户组ID
	Gids            []float64                `json:"gids"`              // 业务组ID
	Gname           []string                 `json:"gname"`             // 用户组名
	HostComment     []string                 `json:"host_comment"`      // 主机备注
	HostId          []float64                `json:"host_id"`           // 主机ID, 用于主机详情页面
	HostIp          []string                 `json:"host_ip"`           // 主机IP
	HostName        []string                 `json:"host_name"`         // 主机名称
	HostState       []string                 `json:"host_state"`        // 主机状态
	HostTags        []string                 `json:"host_tags"`         // 主机标签
	Ids             []float64                `json:"ids"`               // 事件 ID, 用于事件详情页面
	Level           []float64                `json:"level"`             // 风险等级(1-低危，2-中危，3-高危，4-严重)
	NetApp          []string                 `json:"net_app"`           // 网络应用
	Offset          int                      `json:"offset"`            // 偏移量
	Oid             []float64                `json:"oid"`               // 机构 ID
	OrderBy         map[string]interface{}   `json:"order_by"`          // 排序规则
	RuleName        []string                 `json:"rule_name"`         // 规则名称
	SessionId       []string                 `json:"session_id"`        // 会话ID
	SshClientIp     []string                 `json:"ssh_client_ip"`     // ssh登陆地址
	SshUser         []string                 `json:"ssh_user"`          // ssh登录用户
	StartTime       []string                 `json:"start_time"`        // 开始时间
	StatEventId     []float64                `json:"stat_event_id"`     // 事件统计 ID
	State           []float64                `json:"state"`             // 处置状态(1-有风险，2-已忽略，3-已处理)
	Uid             []float64                `json:"uid"`               // 用户ID
	Uname           []string                 `json:"uname"`             // 用户名
	WhiteRuleId     []string                 `json:"white_rule_id"`     // 白名单规则 ID
}
