// Code generated by workspace-cli-generator. DO NOT EDIT.

package baseline_v2

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getCredentialListParams GetCredentialListParams
var GetCredentialListCustomAttrJSON string
var GetCredentialListOrderByJSON string

var GetCredentialListCmd = &cobra.Command{
	Use:   "get_credential_list",
	Short: "获取凭证列表",
	Long:  `获取凭证列表`,
	Run: func(cmd *cobra.Command, args []string) {
		if GetCredentialListCustomAttrJSON != "" {
			if err := json.Unmarshal([]byte(GetCredentialListCustomAttrJSON), &getCredentialListParams.CustomAttr); err != nil {
				cmd.PrintErrln("Error parsing custom-attr:", err)
				return
			}
		}
		if GetCredentialListOrderByJSON != "" {
			if err := json.Unmarshal([]byte(GetCredentialListOrderByJSON), &getCredentialListParams.OrderBy); err != nil {
				cmd.PrintErrln("Error parsing order-by:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "BaselineV2Service.GetCredentialList", getCredentialListParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	GetCredentialListCmd.Flags().StringSliceVar(&getCredentialListParams.Address, "address", nil, "请求地址")
	GetCredentialListCmd.Flags().IntVar(&getCredentialListParams.Count, "count", 20, "每页记录数量, 默认为 20")
	GetCredentialListCmd.Flags().StringSliceVar(&getCredentialListParams.CreatedAt, "created-at", nil, "创建时间")
	// custom_attr is complex type []map[string]interface{}, use JSON string
	GetCredentialListCmd.Flags().StringVar(&GetCredentialListCustomAttrJSON, "custom-attr", "", "主机业务属性 (JSON, e.g. [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}])")
	GetCredentialListCmd.Flags().Float64SliceVar(&getCredentialListParams.Gids, "gids", nil, "业务组 ID")
	GetCredentialListCmd.Flags().StringSliceVar(&getCredentialListParams.HostComment, "host-comment", nil, "主机备注")
	GetCredentialListCmd.Flags().Float64SliceVar(&getCredentialListParams.HostId, "host-id", nil, "主机ID, 用于主机详情页面")
	GetCredentialListCmd.Flags().StringSliceVar(&getCredentialListParams.HostIp, "host-ip", nil, "主机IP")
	GetCredentialListCmd.Flags().StringSliceVar(&getCredentialListParams.HostName, "host-name", nil, "主机名称")
	GetCredentialListCmd.Flags().StringSliceVar(&getCredentialListParams.HostState, "host-state", nil, "主机状态")
	GetCredentialListCmd.Flags().StringSliceVar(&getCredentialListParams.HostTags, "host-tags", nil, "主机标签")
	GetCredentialListCmd.Flags().IntVar(&getCredentialListParams.Offset, "offset", 0, "页偏移, 默认为 0")
	// order_by is object type, use JSON string
	GetCredentialListCmd.Flags().StringVar(&GetCredentialListOrderByJSON, "order-by", "", "排序规则 (JSON, e.g. {\"column\": \"level\", \"order\": \"ASC\"})")
	GetCredentialListCmd.Flags().StringSliceVar(&getCredentialListParams.Protocol, "protocol", nil, "监听的协议(TCP, UnixSocket)")
	GetCredentialListCmd.Flags().StringSliceVar(&getCredentialListParams.Type, "type", nil, "凭证类型(mysql，postgresql，oracle, weblogic)")
	GetCredentialListCmd.Flags().StringSliceVar(&getCredentialListParams.UpdatedAt, "updated-at", nil, "修改时间")
}

// GetCredentialListParams 请求参数
type GetCredentialListParams struct {
	Address     []string                 `json:"address"`      // 请求地址
	Count       int                      `json:"count"`        // 每页记录数量, 默认为 20
	CreatedAt   []string                 `json:"created_at"`   // 创建时间
	CustomAttr  []map[string]interface{} `json:"custom_attr"`  // 主机业务属性
	Gids        []float64                `json:"gids"`         // 业务组 ID
	HostComment []string                 `json:"host_comment"` // 主机备注
	HostId      []float64                `json:"host_id"`      // 主机ID, 用于主机详情页面
	HostIp      []string                 `json:"host_ip"`      // 主机IP
	HostName    []string                 `json:"host_name"`    // 主机名称
	HostState   []string                 `json:"host_state"`   // 主机状态
	HostTags    []string                 `json:"host_tags"`    // 主机标签
	Offset      int                      `json:"offset"`       // 页偏移, 默认为 0
	OrderBy     map[string]interface{}   `json:"order_by"`     // 排序规则
	Protocol    []string                 `json:"protocol"`     // 监听的协议(TCP, UnixSocket)
	Type        []string                 `json:"type"`         // 凭证类型(mysql，postgresql，oracle, weblogic)
	UpdatedAt   []string                 `json:"updated_at"`   // 修改时间
}
