// Code generated by workspace-cli-generator. DO NOT EDIT.

package sensitive_file

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getEventListParams GetEventListParams
var GetEventListCustomAttrJSON string
var GetEventListOrderByJSON string

var GetEventListCmd = &cobra.Command{
	Use:   "get_event_list",
	Short: "获取敏感文件事件列表",
	Long:  `获取敏感文件事件列表`,
	Run: func(cmd *cobra.Command, args []string) {
		if GetEventListCustomAttrJSON != "" {
			if err := json.Unmarshal([]byte(GetEventListCustomAttrJSON), &getEventListParams.CustomAttr); err != nil {
				cmd.PrintErrln("Error parsing custom-attr:", err)
				return
			}
		}
		if GetEventListOrderByJSON != "" {
			if err := json.Unmarshal([]byte(GetEventListOrderByJSON), &getEventListParams.OrderBy); err != nil {
				cmd.PrintErrln("Error parsing order-by:", err)
				return
			}
		}

		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "SensitiveFileService.GetEventList", getEventListParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
	GetEventListCmd.Flags().StringSliceVar(&getEventListParams.Action, "action", nil, "动作")
	GetEventListCmd.Flags().StringSliceVar(&getEventListParams.Comment, "comment", nil, "用户自定义备注")
	GetEventListCmd.Flags().IntVar(&getEventListParams.Count, "count", 20, "数量")
	GetEventListCmd.Flags().StringSliceVar(&getEventListParams.CreatedAt, "created-at", nil, "事件创建事件")
	// custom_attr is complex type []map[string]interface{}, use JSON string
	GetEventListCmd.Flags().StringVar(&GetEventListCustomAttrJSON, "custom-attr", "", "主机业务属性 (JSON, e.g. [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}])")
	GetEventListCmd.Flags().Float64SliceVar(&getEventListParams.Gids, "gids", nil, "业务组 ID 列表")
	GetEventListCmd.Flags().StringSliceVar(&getEventListParams.HostComment, "host-comment", nil, "主机备注")
	GetEventListCmd.Flags().Float64SliceVar(&getEventListParams.HostId, "host-id", nil, "主机 ID")
	GetEventListCmd.Flags().StringSliceVar(&getEventListParams.HostIp, "host-ip", nil, "主机 IP")
	GetEventListCmd.Flags().StringSliceVar(&getEventListParams.HostName, "host-name", nil, "主机名称")
	GetEventListCmd.Flags().StringSliceVar(&getEventListParams.HostState, "host-state", nil, "主机状态")
	GetEventListCmd.Flags().StringSliceVar(&getEventListParams.HostTags, "host-tags", nil, "主机标签")
	GetEventListCmd.Flags().Float64SliceVar(&getEventListParams.Level, "level", nil, "事件等级(1-低危，2-中危，3-高危，4-严重)")
	GetEventListCmd.Flags().IntVar(&getEventListParams.Offset, "offset", 0, "偏移量")
	GetEventListCmd.Flags().Float64SliceVar(&getEventListParams.Oid, "oid", nil, "机构 ID")
	// order_by is object type, use JSON string
	GetEventListCmd.Flags().StringVar(&GetEventListOrderByJSON, "order-by", "", "排序规则 (JSON, e.g. {\"column\": \"level\", \"order\": \"ASC\"})")
	GetEventListCmd.Flags().StringSliceVar(&getEventListParams.Path, "path", nil, "文件路径")
	GetEventListCmd.Flags().Float64SliceVar(&getEventListParams.State, "state", nil, "事件状态(1-有风险，2-已忽略，3-已处理)")
	GetEventListCmd.Flags().StringSliceVar(&getEventListParams.WhiteRuleId, "white-rule-id", nil, "白名单规则 ID")
}

// GetEventListParams 请求参数
type GetEventListParams struct {
	Action      []string                 `json:"action"`        // 动作
	Comment     []string                 `json:"comment"`       // 用户自定义备注
	Count       int                      `json:"count"`         // 数量
	CreatedAt   []string                 `json:"created_at"`    // 事件创建事件
	CustomAttr  []map[string]interface{} `json:"custom_attr"`   // 主机业务属性
	Gids        []float64                `json:"gids"`          // 业务组 ID 列表
	HostComment []string                 `json:"host_comment"`  // 主机备注
	HostId      []float64                `json:"host_id"`       // 主机 ID
	HostIp      []string                 `json:"host_ip"`       // 主机 IP
	HostName    []string                 `json:"host_name"`     // 主机名称
	HostState   []string                 `json:"host_state"`    // 主机状态
	HostTags    []string                 `json:"host_tags"`     // 主机标签
	Level       []float64                `json:"level"`         // 事件等级(1-低危，2-中危，3-高危，4-严重)
	Offset      int                      `json:"offset"`        // 偏移量
	Oid         []float64                `json:"oid"`           // 机构 ID
	OrderBy     map[string]interface{}   `json:"order_by"`      // 排序规则
	Path        []string                 `json:"path"`          // 文件路径
	State       []float64                `json:"state"`         // 事件状态(1-有风险，2-已忽略，3-已处理)
	WhiteRuleId []string                 `json:"white_rule_id"` // 白名单规则 ID
}
